### ISSUE TITLE
Option to specify aggregator pod name

### ISSUE THREAD

**Issue by leodotcloud** [vmware-tanzu/sonobuoy#1000]
Related issue from the past: https://github.com/vmware-tanzu/sonobuoy/issues/782

**What I would like to see:**
As a user, I would like to run multiple instances of sonobuoy aggregator in the same namespace with different plugin configurations.

Currently, it's not possible because the aggregator pod is selected either via the selector label or by the default pod name. (See logic here: https://github.com/vmware-tanzu/sonobuoy/blob/v0.16.3/pkg/plugin/aggregation/update.go#L247)

Possible options:
- Specify the pod name from the CLI 
- Specify the selector label from the CLI
- Figure out the name using downward API

In my use case, I am using the sonobuoy for just running the aggregator. So I am not sure how the any of the above changes might affect the other sub commands of sonobuoy.

Notes:
- I am aware of using different namespaces to launch sonobuoy, but that's not possible in my use case.

**Comment by johnSchnake** [comment]
Could you elaborate on your use case a bit? I'm not sure I follow since you say:
>  I am using the sonobuoy for just running the aggregator
but that you want to run multiple copies
> with different plugin configurations.

So are you running plugins? If so, why not just run all the plugins within a single run of Sonobuoy? If not running plugins, why are you needing to run different configurations of Sonobuoy? Without plugins there is still some value to Sonobuoy since it queries info about your cluster, but I dont know why you would need various settings to be run separately and in parallel.

**Comment by leodotcloud** [comment]
Use case:
Use sonobuoy aggregator to collect logs from all the plugin pods. (You can see the plugin config here: https://github.com/rancher/system-charts/blob/dev/charts/rancher-cis-benchmark/v0.0.1/templates/configmap.yaml#L46). The plugin is launching kube-bench to run a security scan.

Currently, I am having some hacky logic to ensure there is only one security scan running at a time, i.e, a single sonobuoy master/aggregator instance. But, technically there is nothing wrong in running multiple scans with different settings (for example, different set of checks).

**Comment by johnSchnake** [comment]
I don't have a big issue taking something like the label and making it a config option. I don't really think it is such a common use case that I'd want to make it into a CLI option though.

However, the real organization issue this introduces is some commands (for one, `sonobuoy status`) look for that aggregator but don't currently take any sort of config; it expects the `namespace` to be the only necessary bit to define where/how to find the aggregator.

I'll make a slightly larger scoped ticket about 'make all the hardcoded values configurable' effectively and we can investigate what still remains.

**Comment by leodotcloud** [comment]
> I'll make a slightly larger scoped ticket about 'make all the hardcoded values configurable' effectively and we can investigate what still remains.

@johnSchnake thank you! Once you have an idea/design on how to proceed, I can definitely pitch in for this config option with a PR.
