### ISSUE TITLE
No tests seems to be performed with default configuration

### ISSUE THREAD

**Issue by ArseniiPetrovich** [vmware-tanzu/sonobuoy#1003]
**What steps did you take and what happened:**
See the command log => https://gist.github.com/ArseniiPetrovich/b61a834946e3f5d9ababb80ad76f1f79

**What did you expect to happen:**
A set of E2E test to be performed

**Anything else you would like to add:**
I've tried to run the very basic test over my cluster, but it failed.

**Environment:**

- Sonobuoy version: 0.16.1
- Kubernetes version: (use `kubectl version`):
- Kubernetes installer & version:
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"211047e9a1922595eaa3a1127ed365e9299a6c23", GitTreeState:"clean", BuildDate:"2019-10-15T12:02:12Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: Server on GCP platform installed using KOPS
- OS (e.g. from `/etc/os-release`):  Ubuntu 18.04.3 LTS
- Sonobuoy tarball (which contains * below): https://drive.google.com/file/d/1iBXclKjUFBn3gOksD4aBiebcXXn_ae3a/view?usp=sharing

**Comment by johnSchnake** [comment]
Requested access to the tarball.

My assumption is that you ran into the bash runner issue. You're trying to use the golang runner but the cluster is v1.14.8 so that is the version of the conformance image that you'll use. As a result you dont have the golang-runner and may occasionally get problems in the bash script (like "`` is not a valid pid") which causes the bash script to bail without saving any results.

**Comment by johnSchnake** [comment]
Most likely you just need to rerun; I've seen some folks have bad luck and hit that pid issue 2-3 times in a row though. No idea what causes it as I'm not an expert on the internals of those bash utilities; I know I've seen it on clusters in the wild and on local `kind` clusters.

**Comment by ArseniiPetrovich** [comment]
Hello, @johnSchnake! Sorry, I though I already granted an access to the tarball, but please, check it once again - now you should have it.
Regarding the go runner - it was just one of my attempts. I saw this => https://github.com/vmware-tanzu/sonobuoy/issues/910 issue and decided to try. I've tried both variants with and without `E2E_USE_GO_RUNNER=true` multiple times - no luck :(

**Comment by johnSchnake** [comment]
If you look in the podlogs for the e2e pod you see ```/run_e2e.sh: line 65: wait: `': not a pid or valid job spec
```

This is that little nasty bug that impacted the bash runner I mentioned. I dont know what causes some people to hit it more than others; that bash code seemed relatively stable until around v1.13 and v1.14 and we started seeing it more and more.

Sorry there isn't more to do about it; if you want/are able you can always build a custom test image that pulls in the go runner. See the blog here if you are interested in doing that: https://sonobuoy.io/custom-e2e-image/

**Comment by ArseniiPetrovich** [comment]
@johnSchnake 
Am I right that there is no instructions on where to get the Go runner to replace the bash script?

**Comment by johnSchnake** [comment]
Mostly; the code is located here: https://github.com/kubernetes/kubernetes/tree/master/cluster/images/conformance/go-runner

You can either just go there and do a `go build` (be sure to set GOOS/GOARCH as necessary since you'll be running in a linux container)

Also, if you look here: https://github.com/kubernetes/kubernetes/tree/master/cluster/images/conformance

you'll see how to use make to build it:
```
# First, build the binaries by running make from the root directory
$ make WHAT="test/e2e/e2e.test vendor/github.com/onsi/ginkgo/ginkgo cmd/kubectl cluster/images/conformance/go-runner"
```

Of course, if you just need the go runner then trim that down to:
```
$ make WHAT="cluster/images/conformance/go-runner"
```

**Comment by ArseniiPetrovich** [comment]
@johnSchnake I'm really sorry to disturb you, but I got no luck building a custom image.
First of all let me check with you that I understand the building procedure correctly. My plan:
```
export REGISTRY=eu.gcr.io/arsenii-petrovich/conformance
export k8sVersion=$(kubectl version -o json|jq .serverVersion.gitVersion -r) #v1.14.8
export VERSION=$k8sVersion

git clone https://github.com/kubernetes/kubernetes
cd kubernetes/cluster/images/conformance
make WHAT="cluster/images/conformance/go-runner"
curl https://raw.githubusercontent.com/kubernetes/kubernetes/master/cluster/images/conformance/run_e2e.sh -o run.sh && chmod +x run.sh

cat << EOF > Dockerfile
FROM gcr.io/google-containers/conformance:${k8sVersion}
COPY run.sh /run.sh
COPY gorunner /gorunner
EOF

 sonobuoy gen plugin --name=my-e2e \
  --image=$REGISTRY/custom-conformance:v0 \
  --cmd=/run.sh > custom-conformance.yaml
```
Am I getting anything wrong? Because on make step I get the following error:
```
ubuntu@selfportal:~/kubernetes/cluster/images/conformance$ make WHAT="cluster/images/conformance/go-runner"
cp -r ./* /tmp/conformancerdmtdC
cp /home/ubuntu/kubernetes/cluster/images/conformance/../../../_output/dockerized/bin/linux/amd64/ginkgo /tmp/conformancerdmtdC
cp: cannot stat '/home/ubuntu/kubernetes/cluster/images/conformance/../../../_output/dockerized/bin/linux/amd64/ginkgo': No such file or directory
Makefile:44: recipe for target 'build' failed
make: *** [build] Error 1
```
Any help would me much appreciated. Thanks!

**Comment by ArseniiPetrovich** [comment]
Okay, here is the updated instruction that worked for me:
```
export REGISTRY=eu.gcr.io/arsenii-petrovich/conformance
export k8sVersion=$(kubectl version -o json|jq .serverVersion.gitVersion -r) #v1.14.8
export VERSION=$k8sVersion

git clone https://github.com/kubernetes/kubernetes
cd kubernetes
make WHAT="cluster/images/conformance/go-runner"
cd _output/bin
curl https://raw.githubusercontent.com/kubernetes/kubernetes/master/cluster/images/conformance/run_e2e.sh -o run.sh && chmod +x run.sh

cat << EOF > Dockerfile
FROM gcr.io/google-containers/conformance:${k8sVersion}
COPY run.sh /run.sh
COPY go-runner /gorunner
EOF

docker build . -t $REGISTRY:v0 && docker push $REGISTRY:v0

 sonobuoy gen plugin --name=my-e2e \
  --image=$REGISTRY/custom-conformance:v0 \
  --cmd=/run.sh > custom-conformance.yaml

sonobuoy run --plugin custom-conformance.yaml  
```
Make sure to set appropriate repo variable and ensure that your docker is authenticated to push there.  
Hope this helps someone! :)
