### ISSUE TITLE
Pls help to produce the sonobuoy for arm64 

### ISSUE THREAD

**Issue by lubinszARM** [vmware-tanzu/sonobuoy#1005]
**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Deploy Sonobuoy on arm64 server is successful. And the test result seems OK.
All images for arm64 are ready, such as: 
sonobuoy/sonobuoy:v0.16.4
gcr.io/heptio-images/sonobuoy-plugin-systemd-logs:latest
...

But, I don't see an official release binary for arm64 in https://github.com/vmware-tanzu/sonobuoy/releases

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
In fact, the arm64 binary can be generated by the command of 'make' on x86 host.
The arm64 binary is located in build/linux/arm64/

**Environment:**
Arm64 , ubuntu bionic
- Sonobuoy version:  v0.16.4
- Kubernetes version: (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by johnSchnake** [comment]
So the releases in github are just bundled with the binary; not the images.

If you look at https://hub.docker.com/r/sonobuoy/sonobuoy/tags you can see that we do push the arm64 images for sonobuoy.

Are you requesting an arm64 local client? If you're just deploying onto arm64 then all you should need is that we publish the arm64 image.

**Comment by johnSchnake** [comment]
Also, can I ask what you're recommendation for setting up an arm64 cluster would be? You surely have more experience on that platform than I do so I wonder what you'd recommend for a fast/easy test machine/cluster would be.

**Comment by lubinszARM** [comment]
> So the releases in github are just bundled with the binary; not the images.
> 
> If you look at https://hub.docker.com/r/sonobuoy/sonobuoy/tags you can see that we do push the arm64 images for sonobuoy.
> 
> Are you requesting an arm64 local client? If you're just deploying onto arm64 then all you should need is that we publish the arm64 image.

So, can we add the arm64 binary into the release page? https://github.com/vmware-tanzu/sonobuoy/releases

**Comment by lubinszARM** [comment]
> Also, can I ask what you're recommendation for setting up an arm64 cluster would be? You surely have more experience on that platform than I do so I wonder what you'd recommend for a fast/easy test machine/cluster would be.

We are using sonobuoy as the conformance test tool for edge-computing@Arm64.
For both architectures(x86/arm64), there is no difference in our deployment(k8s+sonobuoy). In addition to we need to manually compile sonobuoy binary for Arm64, and for x86, we can get binary  directly from your official github website.

Please see our document as reference: https://docs.google.com/document/d/19SNlK-R6FUg08NvtdiiZNbI1vOq7La28mJnBOJUJNTk/edit?ts=5d41b7be

**Comment by discordianfish** [comment]
Strech goal: Can someone make this work out the box? :)
Looks like just running `sonobuoy run` against a arm64 cluster isn't working:
```
kubectl -n sonobuoy logs sonobuoy
exec /sonobuoy: exec format error
```

```
kubectl -n sonobuoy describe pod sonobuoy |grep Image
    Image:         sonobuoy/sonobuoy:v0.56.16
```
No multiarch image?

**Comment by discordianfish** [comment]
Ok looks like sonobuoy/sonobuoy:v0.56 is multi-arch but sonobuoy/sonobuoy:v0.56.16 is not. Somebody might want to fix that.

**Comment by discordianfish** [comment]
@johnSchnake still not fixed btw.

**Comment by discordianfish** [comment]
And v0.56 leads to:

```
  Warning  Failed     64s (x3 over 103s)  kubelet            Failed to pull image "registry.k8s.io/conformance:v1.27.1-rc1": rpc error: code = NotFound desc = failed to pull and unpack image "registry.k8s.io/conformance:v1.27.1-rc1": failed to resolve reference "registry.k8s.io/conformance:v1.27.1-rc1": registry.k8s.io/conformance:v1.27.1-rc1: not found
```

?!

**Comment by discordianfish** [comment]
I realize it took the conformance image tag from the server version and I'm running k3s v1.27.1-rc1(+k3s...) for which there is no upstream release so filled https://github.com/k3s-io/k3s/issues/7560 - y'all might chat what the right solution here is.
