### ISSUE TITLE
Make constants configurable

### ISSUE THREAD

**Issue by johnSchnake** [vmware-tanzu/sonobuoy#1006]
There still exist some values which are hardcoded into Sonobuoy but in various edge cases would ideally be configurable.

The approach would be something along the lines of:
 - review codebase and see what hardcoded values exist (e.g. default label to put on the sonobuoy run)
 - add these into the config structure; unsure if a nested structure would be ideal so it is organized and we can pull these 'default values' out easily in one chunk or if just adding them as as top-level values to simplify the structure is best
 - add the config as a flag to the commands which dont currently accept it (e.g. `sonobuoy status`)
 - pass around the options as necessary. This is, perhaps, the biggest impact of the change since those values may be used in deeply nested code flows meaning it would impact the signature of various methods along the way. We'll just have to investigate and see.

cc @leodotcloud

**Comment by johnSchnake** [comment]
xref #1000

**Comment by vladimirvivien** [comment]
@wilsonehusin we probably should keep this one open.
