### ISSUE TITLE
First launch with sonobuoy requests for a configuration

### ISSUE THREAD

**Issue by Mr-Reca** [vmware-tanzu/sonobuoy#1015]
**What steps did you take and what happened:**
I'm trying to run sonobuoy in an on-prem Kubernetes cluster. I downloaded the binary (on master node) and I'm trying to run it. It's always showing me this error:

> ERRO[0000] could not create sonobuoy client: failed to get rest config: invalid configuration: no configuration has been provided

I'm looking for some documentation about its requirements or additional configuration and nothing appeared.

What should I do? Do I need to run it on a pod?
Thank you so much,

**What did you expect to happen:**
Run compliance tests with sonobuoy

**Anything else you would like to add:**
I have configured `$KUBECONFIG` and kubectl, helm, docker & sonobuoy are on `$PATH`. I also tried using `--kubeconfig` flag. I used this commands:
```
sonobuoy images pull
sonobuoy run --wait
sonobuoy version
```

**Environment:**

- Sonobuoy version: v0.16.4
- Kubernetes version: (use `kubectl version`): v1.15.3
- Kubernetes installer & version: 
- Cloud provider or hardware configuration: hardware (KTHW)
- OS (e.g. from `/etc/os-release`):  Ubuntu 16.04.6 LTS
- Sonobuoy tarball (which contains * below)

**Comment by zubron** [comment]
Hi @Mr-Reca. Sorry to hear that you're having issues getting started with Sonobuoy!

We have a section in our docs about the [prerequisites](https://sonobuoy.io/docs/v0.16.4/index.html#prerequisites) to get started and it seems like you already have those configured. You don't need to run Sonobuoy in a pod, you just need to have a valid kubeconfig available for the Sonobuoy CLI tool to use.

The error that you are seeing can be triggered by an invalid kubeconfig. Can you confirm that it is valid by running the following command?
```
kubectl cluster-info
```
For that you will need to either have `$KUBECONFIG` configured, or provide it using the `--kubeconfig` flag.

Thanks!

**Comment by zubron** [comment]
Just as a follow up, you don't need to run Sonobuoy _on_ the cluster itself (you mentioned you're downloaded it to a master node). You can run it from anywhere that is configured to access that cluster.

**Comment by Mr-Reca** [comment]
Hi @zubron, 

Thank you so much for you response. At the moment, only the master is configured to interact with the cluster. I have a master node and a worker node, and they both seem to work. I have deployed some apps to test it, `nginxinc/kubernetes-ingress` and some other pod. 

This is the output of the command (run from the master node):

```
Kubernetes master is running at http://localhost:8080
CoreDNS is running at http://localhost:8080/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.

```

**Comment by zubron** [comment]
Thanks for running that and providing the output. I'm having some issues debugging this. Internally we use the Kubernetes go client to take either a given kubeconfig or read it from the environment and create a REST config to interact with the cluster. The error is being returned when trying to get this config which suggests that there's an issue with the kubeconfig that's being provided. I expected that an issue with that config would give an error when running `kubectl cluster-info` though. :confused: 

Could you possibly run the following command to help debug this further? It explicitly uses a kubeconfig and has a very high verbosity setting which should hopefully give us a bit more insight into what is going on when trying to parse the provided kubeconfig.

```
sonobuoy -v 10 version --kubeconfig <path_to_your_kubeconfig>
```

This could potentially produce a lot of logs which you may not want to include here. If that's the case, you can send them to me as a DM on the Kubernetes slack (username bridgetmcerlean), or email them to me (bmcerlean@vmware.com).

**Comment by Mr-Reca** [comment]
Good morning @zubron 

I've just restarted the machine because of some security updates and now it's working... I think that my kubeconfig file was misconfigured (or maybe my cluster), so I'll close the issue.

Thank you so much for your time.

**Comment by zubron** [comment]
Glad you were able to solve your problem. If you have any other questions, just let us know :)
