### ISSUE TITLE
Running Sonobuoy test from docker security private registry images

### ISSUE THREAD

**Issue by kobemtl** [vmware-tanzu/sonobuoy#1020]
Hi, I am trying to running Sonobuoy test from docker security private registry images. I've been follow [Manually specify the images ](https://cormachogan.com/2019/07/24/validating-kubernetes-cluster-conformance-with-sonobuoy/) and it works fine. But the job gonna run in Jenkins pipeline. I need to wait until the test finish to continue the reset of stages. With this way, I don't think it's possible. Let me know if I am wrong please. 

Then I tried using --sonobuoy-image and --kube-conformance-image. By this way I could use --wait. Problem is our docker registry is not public. Then I got unauthorized error when pulling the image. I check there is no parameter for username password login. 

Can anybody help me on this please? 

Much appreciate it.

**Comment by johnSchnake** [comment]
Absolutely; this is actually do-able now and that document should be updated.

So on the step where you run `kubectl apply -f config.yaml` you can now run `sonobuoy run -f config.yaml --wait`

The PR that accomplished that is here https://github.com/vmware-tanzu/sonobuoy/pull/925

Let me know if you need more info but if I read correctly, this should solve your issue.

**Comment by kobemtl** [comment]
Thanks a log John. That works fine and I should check the document more carefully.
