### ISSUE TITLE
Ability to pass kubectl path to sonobuoy

### ISSUE THREAD

**Issue by gogineni99** [vmware-tanzu/sonobuoy#1024]
**Describe the solution you'd like**
Would like to run sonobuoy on build server like Jenkins or any server where kubectl is not in path variable. As part of the build pipeline we copy/install kubectl but do not have permissions to set it in PATH.
Would like to pass the location of kubectl as config parameter similar to --kubeconfig so sonobuoy can execute kubectl commands using this path of kubectl

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Sonobuoy version: v0.16.4
- Kubernetes version: (use `kubectl version`): v1.16.3
- Kubernetes installer & version: v1.16.3
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by johnSchnake** [comment]
Sonobuoy uses the `client-go` library for interacting with the Kubernetes API, not `kubectl`.

You do not require `kubectl` in the PATH to run Sonobuoy. It used to be the case that a user may _want_ kubectl, but that was just so you could generate a file with `sonobuoy gen ... > genOutput.yaml` then run it with `kubectl apply -f genOutput.yaml`. However, `sonobuoy run` now supports the `-f` flag for passing in a file as well.

I'm going to close this issue but if you want to reopen it and clarify your problem I'd be happy to help.
