### ISSUE TITLE
Flags for `run` do not override any values when a manifest is passed with `-f`

### ISSUE THREAD

**Issue by zubron** [vmware-tanzu/sonobuoy#1027]
There is an issue where custom values specified via command line flags do not override content that is in a generated manifest (the file you are passing with `-f`)

_Originally posted by @zubron in https://github.com/vmware-tanzu/sonobuoy/issues/984#issuecomment-561608412_

This may be the intended behaviour but it is confusing for users. If they specify both, we should either prevent them from doing that, or give a warning that the command line flags will have no effect.

**Comment by johnSchnake** [comment]
Yea; this is intended behavior because we actually can’t go from the file to a GenConfig object to later edit.

If they specify a file then we need to just error if they specify other flags/options.
