### ISSUE TITLE
Consider modifying the output flags for `sonobuoy results`

### ISSUE THREAD

**Issue by johnSchnake** [vmware-tanzu/sonobuoy#1030]
**Describe the solution you'd like**
Ticket is for the evaluation (and resolution if simple enough) of the output flags for the sonobuoy results command.

For now we support a few modes; `sonobuoy results` defaults to `report` mode but detailed and dump are also allowed.

Report and dump are pretty straightforward since they generate a human readable report or dump the raw results file respectively.

The `detailed` mode is the one in question for me. When we have tests we end up outputting a stream of `json` objects. When we have a file (like for the systemd logs plugin) we print the filename and the file contents.

We should probably just split this up into more predictable behavior:
 `--mode json` which will print a stream of json objects; if they are files then we probably wouldn't print the raw files in that mode.
  `--mode files` which would print the filenames/contents
  and maybe `--mode file-contents` which would be a shorthand for `--mode files --skip-prefix`

**Anything else you would like to add:**
Open to other ideas/discussion on this ticket before implementing. But right now the `--mode=detailed` is not very descriptive and to have to use `--mode=detailed --skip-prefix` to get just the file contents seems unintuitive and clunky.

**Environment:**

- Sonobuoy version: 
- Kubernetes version: (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by TheChirpyWitch** [comment]
Hi @johnSchnake ! I would like to contribute to Sonobuoy, is it okay if I take up this issue?
