### ISSUE TITLE
e2e Test Fails

### ISSUE THREAD

**Issue by kmriyad** [vmware-tanzu/sonobuoy#1086]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
./sonobuoy run --e2e-skip "Alpha|Disruptive|Feature|Flaky|Kubectl|should function for node-pod communication"
Running plugins: e2e, systemd-logs
INFO[0001] created object                                name=heptio-sonobuoy namespace= resource=namespaces
INFO[0002] created object                                name=sonobuoy-serviceaccount namespace=heptio-sonobuoy resource=serviceaccounts
INFO[0002] created object                                name=sonobuoy-serviceaccount-heptio-sonobuoy namespace= resource=clusterrolebindings
INFO[0002] created object                                name=sonobuoy-serviceaccount namespace= resource=clusterroles
INFO[0002] created object                                name=sonobuoy-config-cm namespace=heptio-sonobuoy resource=configmaps
INFO[0002] created object                                name=sonobuoy-plugins-cm namespace=heptio-sonobuoy resource=configmaps
INFO[0002] created object                                name=sonobuoy namespace=heptio-sonobuoy resource=pods
INFO[0002] created object                                name=sonobuoy-master namespace=heptio-sonobuoy resource=services

./sonobuoy status
         PLUGIN      STATUS      RESULT   COUNT
            e2e           complete   unknown       1
   systemd-logs   complete    passed         1
   systemd-logs   complete                         8
Sonobuoy has completed. Use `sonobuoy retrieve` to get results.

./sonobuoy e2e 202003010030_sonobuoy_ab2000a1-0fb2-tbr6-bat4-28bd0t7x7d4f.tar.gz
ERRO[0000] could not get tests from archive: failed to find results file "plugins/e2e/results/global/junit_01.xml" in archive

./sonobuoy  results 202003010030_sonobuoy_ab2000a1-0fb2-tbr6-bat4-28bd0t7x7d4f
.tar.gz --plugin e2e
Plugin: e2e
Status: unknown
Total: 0
Passed: 0
Failed: 0
Skipped: 0

cat e2e.txt
+ set +x
+ /usr/local/bin/ginkgo '--focus=\[Conformance\]' '--skip=Alpha|Disruptive|Feature|Flaky|Kubectl|should function for node-pod communication' --noColor=true /usr/local/bin/e2e.test -- --disable-log-dump --repo-root=/kubernetes --provider=local --report-dir=/tmp/results --kubeconfig=
+ tee /tmp/results/e2e.log
/run_e2e.sh: line 65: wait: `': not a pid or valid job spec

**What did you expect to happen:**
A successful e2e test

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Sonobuoy version: v0.15.3
- Kubernetes version: (use `kubectl version`):
     Client Version: v1.13.4
     Server Version: v1.14.10
- Kubernetes installer & version:  v1.14.10
- Cloud provider or hardware configuration: 
      AWS - c5.4xlarge
      CPU: 16vCPU
      Memory: 32GiB
- OS (e.g. from `/etc/os-release`): 
      $ cat /etc/redhat-release
      CentOS Linux release 7.7.1908 (Core)
- Sonobuoy tarball (which contains * below)
[202003010030_sonobuoy_ab2000a1-0fb2-tbr6-bat4-28bd0t7x7d4f.tar.gz](https://github.com/vmware-tanzu/sonobuoy/files/4293351/202003010030_sonobuoy_ab2000a1-0fb2-tbr6-bat4-28bd0t7x7d4f.tar.gz)

**Comment by johnSchnake** [comment]
`/run_e2e.sh: line 65: wait: `': not a pid or valid job spec`

is a well known issue that impacts clusters/test runs for versions < 1.16.x

You can see that it impacted us as well here: https://github.com/vmware-tanzu/sonobuoy/issues/746

It has been fixed upstream. You can either:
 - upgrade to a newer version of k8s to avoid the issue
 - rerun whenever you encounter this failure mode
 - build/maintain a custom test image which includes the patch but uses the older set of tests.

Good luck and let me know if you need any more guidance.
