### ISSUE TITLE
Some tests are skipped and some are passed in e2e plugin

### ISSUE THREAD

**Issue by vishal8k** [vmware-tanzu/sonobuoy#1087]
I finished running the test using the default plugin "e2e" with default configurations. When I was going through the result in the file _**"tar.gx file/plugins/e2e/sonobuoy_results.yaml"**_ I was able to see that about 204 tests were passed and 3382 were skipped. I want to know why some were executed and some were skipped? Is there any documentation that explains clearly about the different checks run by this plugin? I'm unable to find one.

I'm using AKS cluster. 
Kubernetes version: 1.14.8

**Comment by johnSchnake** [comment]
Absolutely:  https://sonobuoy.io/docs/v0.17.2/faq/#why-were-so-many-tests-skipped

Feel free to follow up if you have more questions.

**Comment by vishal8k** [comment]
@johnSchnake Just one more question. Running the general conformance testing alone is enough to know whether my cluster satisfies all the industry best practices right? Should I run the test with a cloud provider specific configuration? which in my case is Azure. As far as I researched that might be a tough task it seems.
