### ISSUE TITLE
Is Cloud provider specific testing significant?

### ISSUE THREAD

**Issue by vishal8k** [vmware-tanzu/sonobuoy#1088]
I've run the std conformance testing with the two default plugins "e2e and systemd" and everything went well. On further study about the product I found out that sonobuoy supports cloud specific test. My question is whether is it definitely advisable to go for cloud specific tests or is it just an additional feature that one can include if needed? As far as I researched setting up and running a cloud specific test did not seem an easy task. What is the advantages that I get when I run a cloud specific test rather than a normal one?

**Comment by johnSchnake** [comment]
No, it isn't really significant for most users. Personally I've never run cloud specific tests in years of running Sonobuoy. Each cloud provider has its own set of flags/configs/etc that it requires and I'm not sure they're that well documented outside of the code itself.

If you want to try and run them (for some reason) I'd reach out in the slack for k8s and see if there is a provider specific channel.
