### ISSUE TITLE
Remote Kubernetes Cluster

### ISSUE THREAD

**Issue by rplanteras** [vmware-tanzu/sonobuoy#1089]
Hello, Sorry but I dont know where to posts questions.
I want to test a remote cluster using Sonobuoy, is it possible? My Sonobuoy is installed in sever 1 and my kubernetes cluster in another server.

**Comment by zubron** [comment]
Hi @rplanteras! Yes, Sonobuoy is designed to be able to test clusters remotely. As long as you have the environment variable `KUBECONFIG` set to the path of a valid admin kubeconfig file in "server 1" you will be able to run Sonobuoy against your cluster. You can also specify a kubeconfig file by using the `--kubeconfig` flag to commands.

Check out our docs for our getting started guide: https://sonobuoy.io/docs/v0.17.2/

We also have a channel on the Kubernetes Slack where you can also ask questions: https://kubernetes.slack.com/messages/sonobuoy

I'm going to close this issue, but if you have any problems with the instructions given, feel free to reopen. Good luck!

**Comment by rplanteras** [comment]
> 
> 
> Hi @rplanteras! Yes, Sonobuoy is designed to be able to test clusters remotely. As long as you have the environment variable `KUBECONFIG` set to the path of a valid admin kubeconfig file in "server 1" you will be able to run Sonobuoy against your cluster. You can also specify a kubeconfig file by using the `--kubeconfig` flag to commands.
> 
> Check out our docs for our getting started guide: https://sonobuoy.io/docs/v0.17.2/
> 
> We also have a channel on the Kubernetes Slack where you can also ask questions: https://kubernetes.slack.com/messages/sonobuoy
> 
> I'm going to close this issue, but if you have any problems with the instructions given, feel free to reopen. Good luck!


Hello Bridget,

Thank you for the answer.
I also confirmed when i tried to copy the config file from Kubernetes master serve to my Sonobuoy server.

btw, i would like to join slack. Can i ask for invitation to kubernetes workspace in slack? Thanks.
How can i join slack?

**Comment by zubron** [comment]
You can sign up for the Kubernetes slack here: https://slack.k8s.io/

**Comment by rplanteras** [comment]
Many thanks, Bridget.
