### ISSUE TITLE
Failed to fetch "v1.15.10-eks-bac369"

### ISSUE THREAD

**Issue by brianpham** [vmware-tanzu/sonobuoy#1107]
**What steps did you take and what happened:**

I am seeing this error when trying to run `sonobuoy images pull`. I wanted to test to see if this command would work because I am seeing the same error when running `sonobuoy run --wait`

```
INFO[0001] Image: sonobuoy/sonobuoy:v0.17.2 present locally
INFO[0001] Pulling image: gcr.io/google-containers/conformance:v1.15.10-eks-bac369 ...
ERRO[0003] failed with following error after 1 retries:
ERRO[0003] Error response from daemon: manifest for gcr.io/google-containers/conformance:v1.15.10-eks-bac369 not found: manifest unknown: Failed to fetch "v1.15.10-eks-bac369" from request "/v2/google-containers/conformance/manifests/v1.15.10-eks-bac369".
```

**What did you expect to happen:**
All images should pull successfully. 

**Anything else you would like to add:**

Sonobuoy Version: v0.17.2
MinimumKubeVersion: 1.15.0
MaximumKubeVersion: 1.17.99
GitSHA: eb9343dbd96ebc225d076630be5c348a57dfc430

**Environment:**

- Sonobuoy version: v0.17.2
- Kubernetes version: 
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-23T14:21:54Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.10-eks-bac369", GitCommit:"bac3690554985327ae4d13e42169e8b1c2f37226", GitTreeState:"clean", BuildDate:"2020-02-26T01:12:54Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}```

**Comment by zubron** [comment]
Hi @brianpham! The version of the conformance image you should run depends on the Kubernetes version you are using, and Sonobuoy will attempt to pull the conformance image that matches your server version. In this case, your server version is `v1.15.10-eks-bac369` so it attempted to pull `gcr.io/google-containers/conformance:v1.15.10-eks-bac369`. Given that an image doesn't exist for that version, you will need to specify the conformance image Sonobuoy should use. I don't know if any EKS specific images exist, but you can probably use the v1.15.10 image.

You can specify either the full image path, or the version to use:
```
sonobuoy run --kube-conformance-image gcr.io/google-containers/conformance:v1.15.10

sonobuoy run --kube-conformance-image-version v1.15.10
```

Hope this helps! I'm going to close this issue, but if you have any problems with the details given, feel free to reopen.

**Comment by brianpham** [comment]
Thanks @zubron. This works.
