### ISSUE TITLE
Error found when executing sonobuoy in an offline environment.

### ISSUE THREAD

**Issue by rplanteras** [vmware-tanzu/sonobuoy#1109]
I created a procedure based on the information i got from "https://github.com/vmware-tanzu/sonobuoy/issues/1028#" to use sonobuoy in an offline environment. Now, i receive information from user of the procedure i created that they encountered an error. But i could not point as to what is the cause.

I would like to ask, what could have caused the following errors below?

<pre>
[root@XXXXX ~]# sonobuoy status --kubeconfig $HOME/bin/config
ERRO[0000] error attempting to run sonobuoy: missing status annotation "sonobuoy.hept.io/status"

[root@XXXXX ~]# sonobuoy logs -d --kubeconfig $HOME/bin/config
namespace="sonobuoy" pod="sonobuoy" container="kube-sonobuoy"
time="2020-04-22T07:22:55Z" level=info msg="Scanning plugins in ./plugins.d (pwd: /)"
time="2020-04-22T07:22:55Z" level=info msg="Scanning plugins in /etc/sonobuoy/plugins.d (pwd: /)"
time="2020-04-22T07:22:55Z" level=info msg="Directory (/etc/sonobuoy/plugins.d) does not exist"
time="2020-04-22T07:22:55Z" level=info msg="Scanning plugins in ~/sonobuoy/plugins.d (pwd: /)"
time="2020-04-22T07:22:55Z" level=info msg="Directory (~/sonobuoy/plugins.d) does not exist"
time="2020-04-22T07:23:25Z" level=error msg="could not get api group resources: Get https://<ipaddress>:443/api?timeout=32s: dial tcp <ipaddress>443: i/o timeout"
</pre>

**Comment by zubron** [comment]
Hi @rplanteras. Can you confirm that your kubeconfig file is configured correctly? Looking at the logs, it seems that the server URL is missing, as seen in this log line: `Get https://:443/api?timeout=32s`. Given that the API server URL is missing, Sonobuoy is unable to perform queries against the cluster.

You can check your kubeconfig file using kubectl as follows:
```
kubectl cluster-info --kubeconfig $HOME/bin/config
```

If this is successful, you should see output like the following:
```
Kubernetes master is running at https://127.0.0.1:32769
KubeDNS is running at https://127.0.0.1:32769/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
```

**Comment by rplanteras** [comment]
Hello @zubron. Im sorry for the confusion, in "Get https://**[IPv6 Address]**:443/api?timeout=32s" , there is an ipv6 address. Sorry it was omitted.

**Comment by rplanteras** [comment]
Can you also enlighten me with this error:
<pre>
[root@uhn7klrc6rbmb001 ~]# sonobuoy status --kubeconfig $HOME/bin/config
ERRO[0000] error attempting to run sonobuoy: missing status annotation "sonobuoy.hept.io/status"
</pre>

**Comment by zubron** [comment]
Thanks for the explanation, @rplanteras. 

The error about the status annotation is related to an annotation that is placed on the main sonobuoy pod and is updated during the course of a run with information about the current state of the plugins that are being run. Sonobuoy uses that annotation to determine the overall status for a run so if it is missing, then the sonobuoy CLI will not be able to determine the status which is why it resulted in an error. It is not set when the pod is created, it is only [added once the initial set up for the sonobuoy aggregation process has finished](https://github.com/vmware-tanzu/sonobuoy/blob/master/pkg/discovery/discovery.go#L116-L124).

I understand that you omitted the IP address, but even so, that error still indicates that there were issues connecting to the API server. Looking at the logs from your first post, it shows that it happened very early in the running of the sonobuoy process on that pod. Without seeing more logs, my guess is that the connection to the API server failed, and as a result it couldn't create a client to perform actions on the cluster, such as adding the status annotation to the sonobuoy pod. Were there more log entries following the `could not get api group resources` error where running `sonobuoy logs`?

I would try deleting and re-running sonobuoy. If you encounter the same error, it's more likely to indicate an issue with your cluster or kubeconfig file you might want to check (perhaps with some simpler non-sonobuoy workloads).

**Comment by rplanteras** [comment]
Thank you for your reply, @zubron . Im very sorry for disturbing you. Please see sonobuoy logs output below.

<pre>
[root@sonobuoy-host ~]# sonobuoy logs -d --kubeconfig $HOME/bin/config
namespace="sonobuoy" pod="sonobuoy" container="kube-sonobuoy"
time="2020-04-22T07:22:55Z" level=info msg="Scanning plugins in ./plugins.d (pwd: /)"
time="2020-04-22T07:22:55Z" level=info msg="Scanning plugins in /etc/sonobuoy/plugins.d (pwd: /)"
time="2020-04-22T07:22:55Z" level=info msg="Directory (/etc/sonobuoy/plugins.d) does not exist"
time="2020-04-22T07:22:55Z" level=info msg="Scanning plugins in ~/sonobuoy/plugins.d (pwd: /)"
time="2020-04-22T07:22:55Z" level=info msg="Directory (~/sonobuoy/plugins.d) does not exist"
time="2020-04-22T07:23:25Z" level=error msg="could not get api group resources: Get https://[ipv6 address]:443/api?timeout=32s: dial tcp [ipv6 address]:443: i/o timeout"
time="2020-04-22T07:23:25Z" level=info msg="no-exit was specified, sonobuoy is now blocking"

</pre>

**Comment by rplanteras** [comment]
@zubron 

"It is not set when the pod is created, it is only added once the initial set up for the sonobuoy aggregation process has finished." -> Does this mean that even though sonobuoy pod was created, it is not an assurance that annotation is set?

**Comment by rplanteras** [comment]
@zubron 

"Without seeing more logs, my guess is that the connection to the API server failed," -> In our case, the environment is an air-gapped environment. We don't expect our server to connect to the internet.

**Comment by zubron** [comment]
No need to apologise :) It can be difficult to debug these issues.

> "It is not set when the pod is created, it is only added once the initial set up for the sonobuoy aggregation process has finished." -> Does this mean that even though sonobuoy pod was created, it is not an assurance that annotation is set?

Yes, that is correct. The pod is created without the annotation and is only added by the sonobuoy process running in the pod later.

> "Without seeing more logs, my guess is that the connection to the API server failed," -> In our case, the environment is an air-gapped environment. We don't expect our server to connect to the internet.

Apologies, when I say API server, I mean the Kubernetes API server in your cluster which should be accessible at the IP address which you omitted in the logs. It is the server in your kubeconfig which is being accessed with the request `Get https://[ipv6 address]:443/api?timeout=32s`.
I've actually just noticed that you are using an IPv6 address. I'm not aware of any testing that we've done using IPv6 so I'm wondering if that is causing an issue when trying to make requests :confused: Does your set up only support IPv6? Do you have an IPv4 address that you could try instead in the kubeconfig?

**Comment by rplanteras** [comment]
> 
> 
> No need to apologise :) It can be difficult to debug these issues.
> 
> > "It is not set when the pod is created, it is only added once the initial set up for the sonobuoy aggregation process has finished." -> Does this mean that even though sonobuoy pod was created, it is not an assurance that annotation is set?
> 
> Yes, that is correct. The pod is created without the annotation and is only added by the sonobuoy process running in the pod later.
> 
> > "Without seeing more logs, my guess is that the connection to the API server failed," -> In our case, the environment is an air-gapped environment. We don't expect our server to connect to the internet.
> 
> Apologies, when I say API server, I mean the Kubernetes API server in your cluster which should be accessible at the IP address which you omitted in the logs. It is the server in your kubeconfig which is being accessed with the request `Get https://[ipv6 address]:443/api?timeout=32s`.
> I've actually just noticed that you are using an IPv6 address. I'm not aware of any testing that we've done using IPv6 so I'm wondering if that is causing an issue when trying to make requests 😕 Does your set up only support IPv6? Do you have an IPv4 address that you could try instead in the kubeconfig?

In my understanding, it is sonobuoy pod that makes requests to access Kubernetes API server in the cluster. Is it correct?

**Comment by rplanteras** [comment]
> The error about the status annotation is related to an annotation that is placed on the main sonobuoy pod and is updated during the course of a run with information about the current state of the plugins that are being run. Sonobuoy uses that annotation to determine the overall status for a run so if it is missing, then the sonobuoy CLI will not be able to determine the status which is why it resulted in an error. It is not set when the pod is created, it is only [added once the initial set up for the sonobuoy aggregation process has finished](https://github.com/vmware-tanzu/sonobuoy/blob/master/pkg/discovery/discovery.go#L116-L124).

What probably caused the annotation to be missing?

**Comment by zubron** [comment]
> In my understanding, it is sonobuoy pod that makes requests to access Kubernetes API server in the cluster. Is it correct?

Yes, that is correct.

> What probably caused the annotation to be missing?

The annotation is missing because Sonobuoy could not connect to the Kubernetes API service and so didn't start correctly. It is necessary for Sonobuoy to communicate with the Kubernetes API service to perform its operation so without that it couldn't proceed. It stopped before it could put the annotation on the sonobuoy pod or start any of the the tests.

**Comment by rplanteras** [comment]
> 
> 
> > In my understanding, it is sonobuoy pod that makes requests to access Kubernetes API server in the cluster. Is it correct?
> 
> Yes, that is correct.
> 
> > What probably caused the annotation to be missing?
> 
> The annotation is missing because Sonobuoy could not connect to the Kubernetes API service and so didn't start correctly. It is necessary for Sonobuoy to communicate with the Kubernetes API service to perform its operation so without that it couldn't proceed. It stopped before it could put the annotation on the sonobuoy pod or start any of the the tests.

Thank you very much for your answers @zubron .
Im sorry for having so many questions.
I am planning to confirm sonobuoy pod's communication. 
What i am thinking to do are the steps below:
1. connect to sonobuoy pod
2. execute curl to api servers
The api server that i will try to connect to is the results of "kubectl cluster-info --kubeconfig $HOME/bin/config"

Is my plan okay? or do you have a suggestion how could i confirm sonobuoy can connect to kubernetes api manually?

**Comment by zubron** [comment]
Yes, you can verify that you can communicate with the API server from the Sonobuoy pod. `curl` is not installed in the Sonobuoy container image so you will need to install that first using `apt`.

Even if you can connect to the API server using `curl`, you will still need to delete and recreate your Sonobuoy after to restart the Sonobuoy process. Once restarted it will try to connect to the API server again. There is no way to attempt the connection again from the Sonobuoy process running in the pod once it has failed.

**Comment by rplanteras** [comment]
Hello @zubron. I noticed something in my test environment.
Please see image below.

![env](https://user-images.githubusercontent.com/40653393/80600676-57ee9080-8a5f-11ea-9313-2a61fc322d90.png)

I have private registry where images are pushed for sonobuoy to used. I also have sonobuoy server where i want to execute sonobuoy run (sonobuoy commands). 
1. If i run sonobuoy in sonobuoy server, i could not successfully exeute sonobuoy run.
2. if i run sonobuoy in private registry, where images are found (since its my private registry), i can successfully execue sonobuoy run. 
Any thoughts?

**Comment by zubron** [comment]
Hi @rplanteras. In the failing run, you can see again that it's producing the same error as before "could not get api group resources". It's failing to make a request to the API server at 10.96.0.1 and because that step is failing, the sonobuoy run stops and it does not add the status annotation.

How are running sonobuoy on each of these machines? Can you compare the output from `sonobuoy gen` on both the sonobuoy server, and the private registry machines and check that they are the same?

If they are the same, it is the same workload being deployed on the cluster and so should behave the same. It won't matter which machine it was deployed from. If they are the same, then that suggests an issue with configuration in your cluster, and is not a Sonobuoy issue.

If they are different, it might help us understand what the problem is.

**Comment by rplanteras** [comment]
> 
> 
> Hi @rplanteras. In the failing run, you can see again that it's producing the same error as before "could not get api group resources". It's failing to make a request to the API server at 10.96.0.1 and because that step is failing, the sonobuoy run stops and it does not add the status annotation.
> 
> How are running sonobuoy on each of these machines? Can you compare the output from `sonobuoy gen` on both the sonobuoy server, and the private registry machines and check that they are the same?

I run sonobuoy gen default-image-config and both servers (sonobuoy server and private registry server) have the same output.

> 
> If they are the same, it is the same workload being deployed on the cluster and so should behave the same. It won't matter which machine it was deployed from. If they are the same, then that suggests an issue with configuration in your cluster, and is not a Sonobuoy issue.
> 

Yes, i am expecting they should have the same behavior.

> If they are different, it might help us understand what the problem is.

**Comment by rplanteras** [comment]
Here are the logs when executing sonobuoy run in both servers.

[master-node-private-registry-server.txt](https://github.com/vmware-tanzu/sonobuoy/files/4555258/master-node-private-registry-server.txt)
[master-node-sonobuoy-server.txt](https://github.com/vmware-tanzu/sonobuoy/files/4555259/master-node-sonobuoy-server.txt)


When adding namespace, in sonobuoy run run from private registry, there is a label when namespaces was added,
<pre>
Apr 28 19:14:39 master-node journal: INFO: 2020/04/28 23:14:39.135329 EVENT AddNamespace 
{"metadata":
{"creationTimestamp":"2020-04-28T23:14:39Z",
"labels":{"e2e-framework":"pods","e2e-run":"37cd4b5e-1e64-457a-bd0f-01ea1349b307"},
"name":"pods-4410",
"resourceVersion":"274040",
"selfLink":"/api/v1/namespaces/pods-4410",
"uid":"b2b6271e-3b2c-47a6-9ae2-75528de10e9c"},
"spec":{"finalizers":["kubernetes"]},"status":{"phase":"Active"}}
</pre>

in sonobuoy server, no label was added.
<pre>
Apr 28 19:01:47 master-node journal: INFO: 2020/04/28 23:01:47.786056 EVENT AddNamespace 
{"metadata":
{"creationTimestamp":"2020-04-28T23:01:47Z",

"name":"sonobuoy-offline-certified-conformance-mode-sonobuoy-server",
"resourceVersion":"272115",
"selfLink":"/api/v1/namespaces/sonobuoy-offline-certified-conformance-mode-sonobuoy-server",
"uid":"05d44207-941c-49b0-aeb7-9bb1caecb567"},
"spec":{"finalizers":["kubernetes"]},"status":{"phase":"Active"}}
</pre>

**Comment by zubron** [comment]
> I run sonobuoy gen default-image-config and both servers (sonobuoy server and private registry server) have the same output.

Can you confirm that the output of `sonobuoy gen` (no other arguments) is the same on both machines? When you run that you will see the kubernetes manifest that sonobuoy creates.
 
If you look at the namespaces that are created, the one with the label is one that is created as part of the e2e tests. The other is the namespaces created by Sonobuoy. If you look in the private-registry-server logs, there are two namespaces created.

**Comment by rplanteras** [comment]
> 
> 
> > I run sonobuoy gen default-image-config and both servers (sonobuoy server and private registry server) have the same output.
> 
> Can you confirm that the output of `sonobuoy gen` (no other arguments) is the same on both machines? When you run that you will see the kubernetes manifest that sonobuoy creates.
> 
> If you look at the namespaces that are created, the one with the label is one that is created as part of the e2e tests. The other is the namespaces created by Sonobuoy. If you look in the private-registry-server logs, there are two namespaces created.

It was a mistak @zubron. A copied wrong line in logs. SOrry for that. As for the output of sonobuoy gen in both servers, they have the same output.

**Comment by zubron** [comment]
> they have the same output except for the config.json.

How do the contents of `config.json` differ between the two outputs?

**Comment by rplanteras** [comment]
> 
> 
> > they have the same output except for the config.json.
> 
> How do the contents of `config.json` differ between the two outputs?

Its only the UUID.
Now i am experiencing the error in both servers (private registry and sonobuoy server).
I did not change any configuration, i just keep on trying to test execute sonbuoy run. :(

**Comment by rplanteras** [comment]
Its normal right that when executing sonobuoy run, it will pull images for conformance and sonobuoy (in quick mode) in kubernetes master node.

**Comment by zubron** [comment]
The default image pull policy is `IfNotPresent` so if those images are not on the node where sonobuoy is running, then yes they will be pulled.

If you are experiencing the error with both servers, when it previously worked with one, then this seems to be an issue with your cluster configuration rather than Sonobuoy, sorry :(

**Comment by zubron** [comment]
Are you having issues running any other workloads on your cluster? It might be better to work with something simpler to debug the networking issue.

**Comment by rplanteras** [comment]
For my kubernetes cluster, i just setup the environment based on some resources from internet just for testing. I have not tested kubernetes cluster with other workloads. Below are some details of my kubernetes cluster.

<pre>
[root@master-node ~]# kubectl get pods -A
NAMESPACE                                                     NAME                                  READY   STATUS    RESTARTS   AGE
kube-system                                                   coredns-66bff467f8-r7nqd              1/1     Running   2          2d
kube-system                                                   coredns-66bff467f8-srpmb              1/1     Running   2          2d
kube-system                                                   etcd-master-node                      1/1     Running   2          2d
kube-system                                                   kube-apiserver-master-node            1/1     Running   51         2d
kube-system                                                   kube-controller-manager-master-node   1/1     Running   3          2d
kube-system                                                   kube-proxy-75nlb                      1/1     Running   2          47h
kube-system                                                   kube-proxy-9q24v                      1/1     Running   2          47h
kube-system                                                   kube-proxy-pm7vm                      1/1     Running   2          2d
kube-system                                                   kube-scheduler-master-node            1/1     Running   3          2d
kube-system                                                   weave-net-84dqb                       2/2     Running   8          2d
kube-system                                                   weave-net-9lspj                       2/2     Running   5          47h
kube-system                                                   weave-net-n6zcx                       2/2     Running   5          47h

</pre>

<pre>

[root@master-node ~]# kubectl get namespaces
NAME                                                          STATUS   AGE
default                                                       Active   2d
kube-node-lease                                               Active   2d
kube-public                                                   Active   2d
kube-system                                                   Active   2d
[root@master-node ~]# 
</pre>

**Comment by rplanteras** [comment]
> then



> The default image pull policy is `IfNotPresent` so if those images are not on the node where sonobuoy is running, then yes they will be pulled.

IN my understanding, he node where sonobuoy is running is referring to the master node of the k8s cluster, right?

**Comment by zubron** [comment]
No, by default Sonobuoy can run on any node where pods can run on a cluster. Some of the plugins sonobuoy runs may run on specific nodes but that has to be configured.

**Comment by rplanteras** [comment]
Hello @zubron , do you think running on IPv6 environment affects sonobuoy?

**Comment by zubron** [comment]
Hi @rplanteras. I'm not aware of any testing that has been done with an IPv6 environment so unfortunately I don't know.

Sonobuoy uses the kubernetes client-go package for loading the kubeconfig and creating the client to communicate with the API server so hopefully would be able to take advantage of the IPv6 support there.

**Comment by rplanteras** [comment]
@zubron 

I'm sorry this might be a stupid question, but im not sure about the source code details. "kubernetes client-go package" is included in sonobuoy image? I know client-go is part of kubernetes, but willsonobuoy use it? Basically, i have an air-gapped environment.

**Comment by rplanteras** [comment]
@zubron 

Is it sonobuoy pod that access the kubernetes api or the sonobuoy application (executable file downloaded to execute sonobuoy commands)?

**Comment by rplanteras** [comment]
Error on "could not get api group resources" occurs here at the very early part of the function Run.

https://github.com/vmware-tanzu/sonobuoy/blob/master/pkg/discovery/discovery.go#L65
https://github.com/vmware-tanzu/sonobuoy/blob/1a3181860ccce0cffa83453364452bf1cdaf6d43/pkg/dynamic/client.go#L50

**Comment by zubron** [comment]
Hi @rplanteras!

Yes, `client-go` is the Golang library provided by the Kubernetes project for interacting with Kubernetes clusters. That's what we use in Sonobuoy for interacting with the cluster that it's running on. It will use it to create the pods and other resources on the cluster, and then update those resources during the run.

Both the CLI application that you run and the pod will make use of this library.

This the same error that you were originally seeing. Are you seeing it when using the CLI or in the pod logs?

**Comment by rplanteras** [comment]
I use the following commands in sonobuoy server.

b. sonobuoy logs  ( in sonobuoy server)

<pre>
[root@uhn7klrc6rbmb001 ~]# sonobuoy logs --kubeconfig /root/bin/config -n sonobuoy-test
namespace="sonobuoy-test" pod="sonobuoy" container="kube-sonobuoy"
time="2020-05-01T06:27:40Z" level=info msg="Scanning plugins in ./plugins.d (pwd: /)"
time="2020-05-01T06:27:40Z" level=info msg="Scanning plugins in /etc/sonobuoy/plugins.d (pwd: /)"
time="2020-05-01T06:27:40Z" level=info msg="Directory (/etc/sonobuoy/plugins.d) does not exist"
time="2020-05-01T06:27:40Z" level=info msg="Scanning plugins in ~/sonobuoy/plugins.d (pwd: /)"
time="2020-05-01T06:27:40Z" level=info msg="Directory (~/sonobuoy/plugins.d) does not exist"
time="2020-05-01T06:28:10Z" level=error msg="could not get api group resources: Get https://[240b:c0e0:101:5dc0:b464:2:0:8001]:443/api?timeout=32s: dial tcp [240b:c0e0:101:5dc0:b464:2:0:8001]:443: i/o timeout"
time="2020-05-01T06:28:10Z" level=info msg="no-exit was specified, sonobuoy is now blocking"
[root@uhn7klrc6rbmb001 ~]#

</pre>
<pre>
c. sonobuoy status ( in sonobuoy server)

[root@uhn7klrc6rbmb001 ~]# sonobuoy status --kubeconfig /root/bin/config -n sonobuoy-test
ERRO[0000] error attempting to run sonobuoy: missing status annotation "sonobuoy.hept.io/status"
[root@uhn7klrc6rbmb001 ~]#
</pre>

**Comment by rplanteras** [comment]
> This the same error that you were originally seeing. Are you seeing it when using the CLI or in the pod logs?

I was not able to check using kubectl logs command.

**Comment by rplanteras** [comment]
With this error "time="2020-05-01T06:28:10Z" level=error msg="could not get api group resources: Get https://[240b:c0e0:101:5dc0:b464:2:0:8001]:443/api?timeout=32s: dial tcp [240b:c0e0:101:5dc0:b464:2:0:8001]:443: i/o timeout" i would like to determine who ctried to get the api resources, is it sonobuoy cli execution or sonobuoy pod? based on the logs shown above, pod logs also shows the error, meaning the pod tried to access the api server. I dont quite get the flow of the execution of sonobuoy run command.

**Comment by zubron** [comment]
When you run `sonobuoy logs` it is retrieving the logs for any pods that belong to it.

With the error you are seeing, that is coming from the sonobuoy pod.

When you use `sonobuoy run`, it creates a manifest with the resources to create on the cluster, and uses a client (created using the Kubernetes client-go library) to deploy that manifest and create the resources on the cluster. You can see this manifest that will be used by using the `sonobuoy gen` command. 

Part of this manifest is to create the main sonobuoy pod. The command run on the sonobuoy pod also creates a client using the client-go library to interact with the cluster. It needs this client to start the plugins (creating Pods or DaemonSets), and also perform actions against the resources in the Sonobuoy namespace such as querying data about the pods, and adding labels and annotations to the pods.

**Comment by rplanteras** [comment]
> creates a client using the client-go library to interact with the cluster
client-go library is found in kubernetes, right? I would like to confirm, where will sonobuoy get this library or is it included in sonobuoy image?

**Comment by zubron** [comment]
It is a library provided by the Kubernetes project: https://github.com/kubernetes/client-go

It is a Golang library and we use it in the sonobuoy project. The `sonobuoy` executable which we build (which is used as the CLI tool and in the sonobuoy image), uses this library and it is built into that executable.

**Comment by rplanteras** [comment]
> When you use `sonobuoy run`, it creates a manifest with the resources to create on the cluster, and uses a client (created using the Kubernetes client-go library) to deploy that manifest and create the resources on the cluster. 
Is my understanding correct, that sonobuoy pod is included in this resources that will be created in the cluster? Also, in my case, sonobuoy pod was created but was not able to create the necessary resource such as the hept.io/sonobuoy annotation. Is it correct?

> You can see this manifest that will be used by using the `sonobuoy gen` command.
Yes, i tried to generate and got the manifest.
