### ISSUE TITLE
Apply an image pull timeout for the main Sonobuoy image 

### ISSUE THREAD

**Issue by dlutton** [vmware-tanzu/sonobuoy#1118]
**Describe the solution you'd like**
Currently, the image pull timeout only applies to images for plugins. For the main Sonobuoy pod, the logic for waiting for will loop until it can find either the "complete" or "failed" status annotation on the pod. Since that pod never starts due to the image pull error it will never reach that state.  I'd like this to bail out after some time like the plugins do.

**Anything else you would like to add:**
Running the below command with a fake registry name will cause the Sonobuoy to run for 1 day (due to the --wait flag) only to find out it couldn't pull the main Sonobuoy image.  It doesn't take into consideration issues with starting the main Sonobuoy pod.
`['sonobuoy', 'run', '--wait', '--kubeconfig', '/home/dlutton/.kube/config', '--skip-preflight', '--plugin', 'e2e', '--e2e-focus', 'Docker Containers', '--e2e-repo-config', 'my-custom-registry.yaml', '--kube-conformance-image', 'my-custom-registry/conformance:v1.18.0', '--sonobuoy-image', 'my-custom-registry/sonobuoy:v0.18.0']  
`

**Environment:**

- Sonobuoy version: 0.18.0
- Kubernetes version: (use `kubectl version`): 1.17.5
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`): Debian GNU/Linux 10 (buster)

**Comment by wilsonehusin** [comment]
I have been looking for a way to manage this through configuration, but the closest thing I can find is having a `kubelet` with `--runtime-request-timeout duration` which I'm not entirely sure if it's a good idea.

An alternative I can think of is by scanning Pod event. A deployment with fake registry / container name shows the following message:
`
Failed to pull image "fake-image/sonobuoy:v0.19.0": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/fake-image/sonobuoy:v0.19.0": failed to resolve reference "docker.io/fake-image/sonobuoy:v0.19.0": pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
`

If we can rely on this message, especially the "pull access denied" part, then maybe this is an approach we can work on.

Any thoughts? @vladimirvivien
