### ISSUE TITLE
sonobuoy failed with admission webhook and CustomResourceConversionWebhook

### ISSUE THREAD

**Issue by RameshJampana** [vmware-tanzu/sonobuoy#1145]
**What steps did you take and what happened:**
wget https://github.com/vmware-tanzu/sonobuoy/releases/download/v0.18.3/sonobuoy_0.18.3_linux_amd64.tar.gz
tar -xvzf sonobuoy_0.18.3_linux_amd64.tar.gz
mv sonobuoy /usr/bin/
chmod +x /usr/bin/sonobuoy

sonobuoy run --mode certified-conformance --kube-conformance-image gcr.io/google-containers/conformance:v1.18.4 -v 5 --wait

e2e test failed

# sonobuoy status
         PLUGIN     STATUS   RESULT   COUNT
            e2e          complete   failed       1
   systemd-logs   complete   passed       2

[root@controller# sonobuoy results 202007141012_sonobuoy_dca12d27-83bf-403a-b11d-14165bb59e6e.tar.gz
Plugin: e2e
Status: failed
Total: 4992
Passed: 252
Failed: 25
Skipped: 4715
Failed tests:
[sig-api-machinery] AdmissionWebhook [Privileged:ClusterAdmin] should not be able to mutate or prevent deletion of webhook configuration objects [Conformance]
[sig-api-machinery] CustomResourceConversionWebhook [Privileged:ClusterAdmin] should be able to convert a non homogeneous list of CRs [Conformance]
[sig-api-machinery] CustomResourceConversionWebhook [Privileged:ClusterAdmin] should be able to convert from CR v1 to CR v2 [Conformance]
[sig-api-machinery] AdmissionWebhook [Privileged:ClusterAdmin] should be able to deny pod and configmap creation [Conformance]
[sig-api-machinery] AdmissionWebhook [Privileged:ClusterAdmin] patching/updating a mutating webhook should work [Conformance]
[sig-api-machinery] AdmissionWebhook [Privileged:ClusterAdmin] should honor timeout [Conformance]
[sig-network] Services should be able to change the type from ClusterIP to ExternalName [Conformance]
[sig-api-machinery] AdmissionWebhook [Privileged:ClusterAdmin] should mutate pod and apply defaults after mutation [Conformance]
[sig-api-machinery] AdmissionWebhook [Privileged:ClusterAdmin] should be able to deny custom resource creation, update and deletion [Conformance]
[sig-api-machinery] AdmissionWebhook [Privileged:ClusterAdmin] should deny crd creation [Conformance]
[sig-storage] Downward API volume should provide podname only [NodeConformance] [Conformance]
[sig-storage] Projected configMap should be consumable in multiple volumes in the same pod [NodeConformance] [Conformance]
[sig-cli] Kubectl client Update Demo should scale a replication controller  [Conformance]
[k8s.io] Kubelet when scheduling a busybox command that always fails in a pod should have an terminated reason [NodeConformance] [Conformance]
[sig-api-machinery] AdmissionWebhook [Privileged:ClusterAdmin] should mutate custom resource with pruning [Conformance]
[sig-apps] Deployment RecreateDeployment should delete old pods and create new ones [Conformance]
[sig-api-machinery] AdmissionWebhook [Privileged:ClusterAdmin] should unconditionally reject operations on fail closed webhook [Conformance]
[sig-api-machinery] AdmissionWebhook [Privileged:ClusterAdmin] should mutate custom resource with different stored version [Conformance]
[sig-api-machinery] AdmissionWebhook [Privileged:ClusterAdmin] should be able to deny attaching pod [Conformance]
[sig-api-machinery] AdmissionWebhook [Privileged:ClusterAdmin] should mutate custom resource [Conformance]
[sig-api-machinery] AdmissionWebhook [Privileged:ClusterAdmin] patching/updating a validating webhook should work [Conformance]
[sig-api-machinery] AdmissionWebhook [Privileged:ClusterAdmin] listing validating webhooks should work [Conformance]
[sig-apps] Daemon set [Serial] should rollback without unnecessary restarts [Conformance]
[sig-api-machinery] AdmissionWebhook [Privileged:ClusterAdmin] should mutate configmap [Conformance]
[sig-api-machinery] AdmissionWebhook [Privileged:ClusterAdmin] listing mutating webhooks should work [Conformance]

Plugin: systemd-logs
Status: passed
Total: 2
Passed: 2
Failed: 0
Skipped: 0

**What did you expect to happen:**
e2e test success

**Anything else you would like to add:**
CNI used KUBE-OVN

**Environment:**

- Sonobuoy version: 
sonobuoy_0.18.3
- Kubernetes version: (use `kubectl version`):

Client Version: v1.18.4
Server Version: v1.18.4

- Kubernetes installer & version:
kubeadm version: &version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-17T11:39:11Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
MEM-15 G
DISK-35 G
- OS (e.g. from `/etc/os-release`): 
 Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-957.el7.x86_64
      Architecture: x86-64

- Sonobuoy tarball (which contains * below)

**Comment by RameshJampana** [comment]
@zubron ,
can you plz check this

**Comment by zubron** [comment]
Hi @RameshJampana. Conformance test failures do not indicate an issue with Sonobuoy, rather they are showing that some behaviour in your cluster is not working correctly. Please see our guide on [debugging test failures](https://sonobuoy.io/docs/v0.18.3/faq/#how-do-i-determine-why-my-tests-failed) which details how to isolate test failures and where to find the logs for the test in the results tarball.

Given that this is not a problem with Sonobuoy, I am going to close this issue.

**Comment by RameshJampana** [comment]
@zubron 
We are seeing AdmissionWebhook tests in conformance mode are failing with below error,
Unexpected error:
    <*errors.errorString | 0xc000093fe0>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
occurred

Our k8s environment uses proxy and is this causing these failures? Please let us know whether Sonobouy runs behind the proxy? or we need any argument to pass while running with proxy.
attached tar file for the latest run with 20 tc failures(all related to admission web hook and crd)
please let me know if any inputs required to debug this .

[202007221857_sonobuoy_cba7f067-ec9b-43d3-9507-546cbb643d34.tar.gz](https://github.com/vmware-tanzu/sonobuoy/files/4989726/202007221857_sonobuoy_cba7f067-ec9b-43d3-9507-546cbb643d34.tar.gz)

**Comment by zubron** [comment]
Hi - I'm not aware of any specific issues related to environments that use a proxy. However, the Sonobuoy team are not the authors of these tests so unfortunately we can't offer specific guidance about what these tests are doing.

I noticed the DaemonSet test failed due to one of the nodes being unavailable, so I would also inspect your cluster logs to determine why a node was unavailable during the test run.

I looked for Kubernetes issues related to the AdmissionWebhook tests and found this comment on an issue: https://github.com/kubernetes/kubernetes/issues/88958#issuecomment-597062875

It _could_ be that the CNI you are using (kube-ovn) is not recommended for use with kubeadm. I would verify that it is intended to work with kubeadm and if not, you could try using one of the CNIs suggested in that comment (Calico or Weave Net).

Unfortunately, I am not experienced with this level of cluster configuration so can't offer any further guidance.

**Comment by jwz-ecust** [comment]
Any solution to solve the failure of admission webhook and customresourceconversionwebhook?

**Comment by jwz-ecust** [comment]
I also encountered the same failure, the k8s version is 1.20.1.

**Comment by IMOKURI** [comment]
I think you need to set following domains to no_proxy environment variables for kube-apiserver.

- `.svc`
- `.cluster.local`

Edit `/etc/kubernetes/manifests/kube-apiserver.yaml` on master nodes.

Because kube-apiserver connects webhook service via https with `.svc` domain.
