### ISSUE TITLE
e2e runs failed on Openshift4.4 platform

### ISSUE THREAD

**Issue by piyushkv1** [vmware-tanzu/sonobuoy#1147]
**What steps did you take and what happened:**
Running sonobuoy conformance tests with Openshift 4.4 platform. Precheck failed with because dns pods are not running under kube-system. This is specific to Openshift4.x release. Till Openshift 3.x release, dns pods were deployed under kube-system.

# ./sonobuoy run --wait
ERRO[0000] Preflight checks failed
ERRO[0000] no dns pods found with the labels [k8s-app=kube-dns, k8s-app=coredns] in namespace kube-system
ERRO[0000] namespace already exists

**What did you expect to happen:**
Check dns pods under openshift-dns in case of Openshift platform, since they are deployed under openshift-dns namespace.

**Anything else you would like to add:**
# oc get pods --all-namespaces |grep dns
openshift-dns-operator                                  dns-operator-78f55bd79d-jtth7                                     2/2     Running            0          2d15h
openshift-dns                                           dns-default-255rn                                                 2/2     Running            0          2d15h
openshift-dns                                           dns-default-2dkhf                                                 2/2     Running            0          2d15h
openshift-dns                                           dns-default-dw598                                                 2/2     Running            0          2d15h
openshift-dns                                           dns-default-tjg62                                                 2/2     Running            0          2d15h
openshift-dns                                           dns-default-vgsl4                                                 2/2     Running            0          2d15h
openshift-dns                                           dns-default-x247h                                                 2/2     Running            0          2d15h

**Environment:**

- Sonobuoy version: 
Sonobuoy Version: v0.18.3
MinimumKubeVersion: 1.16.0
MaximumKubeVersion: 1.18.99
GitSHA: 3e8a10e5145f21840b308b76487f3e10b9c1261d
- Kubernetes version: (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0-4-g38212b5", GitCommit:"d89e458c3dff553f9a732b282830bfa9b4e0ab9b", GitTreeState:"clean", BuildDate:"2020-06-29T04:50:06Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.1+166b070", GitCommit:"166b070", GitTreeState:"clean", BuildDate:"2020-06-30T21:47:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
- Kubernetes installer & version:
- Cloud provider or hardware configuration: vsphere
- OS (e.g. from `/etc/os-release`): 
# cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
- Sonobuoy tarball (which contains * below)

**Comment by zubron** [comment]
Hi @piyushkv1,

Sonobuoy does not automatically detect where the DNS pods are running, however you can override the namespace and the labels to use when looking for them with the flags `--dns-namespace` (default: `kube-system`)  and `--dns-pod-labels` (default: `k8s-app=kube-dns,k8s-app=coredns`).

Sonobuoy also just checks for the presence of these pods during its preflight checks. You can also opt to skip those checks using `--skip-preflight`.

I'm going to close this issue, but if you have any problem with this or think that something else needs to be addressed, feel free to reopen.

**Comment by jwhb** [comment]
In OpenShift 4 the namespace and labels of CoreDNS pods depends on the type of infrastructure.
This works for OpenShift on vSphere:

```bash
sonobuoy run --wait --dns-namespace=openshift-vsphere-infra --dns-pod-labels=app=vsphere-infra-coredns
```
