### ISSUE TITLE
Can I introduce customized tag similar to [NodeConformance] [Conformance] ? 

### ISSUE THREAD

**Issue by amitkrperf** [vmware-tanzu/sonobuoy#1150]
Sonobuoy which used  "Conformance" image for running the conformance tests. In order to run selective tests, currently there are two ways ( based on my current understanding) : 
1. Use the available test tags like, [NodeConformance] , [Conformance] etc. 
2. Use expressions which would be search using regex. 

We are building a pipeline which needs to run conformance tests on the cluster and we also want to build the capability in which we could run a fraction of the current conformance test based on requirements, eg, service related tests, pods related test. We intend to use our own customized tag instead of using regex expressions: 
1. Service related tests - [MYSVC] 
2. Pods related tests - [MYPODS] 

A wrong selected regex can cause a a large difference in the number of tests being selected ( "Pod" starts 80 tests while "Pods" start 27 tests ) . We would rather prefer to tag specific tests which we want to run. 

Later, we would want to extend this capability to all the other e2e tests, as well. 

**Environment:**

- Sonobuoy version: v0.18.3
- Kubernetes version: (use `kubectl version`): 1.15 
- Kubernetes installer & version: 1.15 
- Cloud provider or hardware configuration: Environment running in an AWS cluster
- OS (e.g. from `/etc/os-release`): Debian GNU/Linux 9
- Sonobuoy tarball (which contains * below) - N/A

**Comment by zubron** [comment]
Hi @amitkrperf,

The tags on the tests are controlled within the tests and framework in the Kubernetes e2e test image that Sonobuoy runs. The tests and the images are created by the Kubernetes community, not the Sonobuoy team. 

When running tests based on tags such as [Conformance], [NodeConformance] etc, those are provided to the E2E as regexes - they aren't treated any differently. Sonobuoy provides some hardcoded "modes" which are just regexes which include those tags in the regex passed through to the E2E test framework.

I don't think it's possible to define your own tags without modification to the E2E tests and framework in the Kubernetes project.

To help overcome the issue of mistakenly running the wrong set of tests and ensuring your regex is targeting the correct set of tests, you can use the "dry run" mode by passing the flag `--plugin-env e2e.E2E_DRYRUN=true`. In this mode, the test framework will not run any test, but instead will mark any tests that _would_ have been run as passing. Once complete, you can use `sonobuoy results` along with a tool like [jq](https://stedolan.github.io/jq/) to extract the names of the tests that would have been run:

```
sonobuoy run -p e2e --plugin-env e2e.E2E_DRYRUN=true  # <optional --e2e-focus argument>
results=$(sonobuoy retrieve)
sonobuoy results $results --mode detailed | jq '. | select(.status=="passed") | .name'
```

Hopefully this information is of some help to you.
