### ISSUE TITLE
Improve the message used when a plugin timeout occurs

### ISSUE THREAD

**Issue by zubron** [vmware-tanzu/sonobuoy#1152]
**Describe the solution you'd like**
When a plugin times out, it is terminated by Sonobuoy and the error message for the plugin is `timeout waiting for results`. This message can be confusing for users as it assumes some internal knowledge of how Sonobuoy runs its plugins and how it retrieves results. This message could be expanded to give more details about the fact that the plugin was terminated and how there are no results available to view. We include more details in the logs from the main aggregator pod, however if a user just looks at the results from the tarball, that context is not included.

**Comment by vladimirvivien** [comment]
@zubron Hi. What does a `plugin times out` mean? Is it when the plugin does not report progress ?

**Comment by vladimirvivien** [comment]
Keep open.

**Comment by johnSchnake** [comment]
Going to make a small improvement here and call it a day. I think we can just modify some strings and it will be somewhat helpful. We don't have to change the actual error handling or anything to get some benefit.

**Comment by johnSchnake** [comment]
https://github.com/vmware-tanzu/sonobuoy/pull/1303
