### ISSUE TITLE
Sonobuoy Documentation

### ISSUE THREAD

**Issue by mohjam2004** [vmware-tanzu/sonobuoy#1153]
Thanx for your excellent tool.
How can I find detailed documentation of what kind of tests and their description are done in default mode and plugins of sonobuoy run? I have found some docs but they are only summary.
I have another question. Is sonobuoy compatible with RKE (Rancher kubernetes engine)?
I'll be glad if you send me an invitation to slack channel to mohjam2004@yahoo.com.
Regards

**Comment by zubron** [comment]
Hi @mohjam2004,

> How can I find detailed documentation of what kind of tests and their description are done in default mode and plugins of sonobuoy run? 

You can find the documentation for the e2e plugin here: https://sonobuoy.io/docs/v0.18.4/e2eplugin/

The conformance tests themselves that are run by the e2e plugin are maintained by the Kubernetes community and you can find overall details about conformance testing here: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/conformance-tests.md

You can find a full list of the tests and description in the Kubernetes repo here: https://github.com/kubernetes/kubernetes/blob/master/test/conformance/testdata/conformance.yaml
The list of conformance tests will change for each release however so be sure to view the branch that corresponds with the version of Kubernetes you are using.

> Is sonobuoy compatible with RKE

Sonobuoy itself will be compatible. The CLI creates and deploys a workload on your cluster (which you can view by looking at the output from `sonobuoy gen`). As for whether it will pass the E2E tests, I'm not sure. Looking at the list of [Certified Kubernetes offerings](https://github.com/cncf/k8s-conformance), RKE was certified for [v1.17](https://github.com/cncf/k8s-conformance/tree/master/v1.17/rke).

> I'll be glad if you send me an invitation to slack channel

The easiest way to get access to the Kubernetes slack is to request an invite here: https://slack.k8s.io/
Once you join, you can find the sonobuoy team in [#sonobuoy](https://kubernetes.slack.com/messages/sonobuoy).

I'm going to close this issue, but feel free to reopen or create a new issue if you have further problems!
