### ISSUE TITLE
A couple of issues with images

### ISSUE THREAD

**Issue by CDespeaux** [vmware-tanzu/sonobuoy#1156]
**What steps did you take and what happened:**
I tried running the conformance test on Kubernetes v1.18.3+k3s1 with sonobuoy v0.18.4.
I ran into issues where a number of tests failed with "Failed to pull image <image>" where the image to be pulled is not listed as one of the required images produced by the sonobuoy images command.  These include:

gcr.io/kubernetes-e2e-test-images/pets/redis-installer:1.2
gcr.io/kubernetes-e2e-test-images/pets/zookeeper-installer:1.3
gcr.io/google_samples/gb-redisslave:nonexistent

I'll point out that that last image also apparently doesn't exist, as I could not pull it from docker.

We've since moved to kubernetes v1.18.6+k3s1.

I pulled the redis-installer and zookeeper-installer from docker and pushed them to our private registry.  They exist in the e2eRegistry defined in my custom repo config yaml file I am passing to sonobuoy with the --e2e-repo-config option, yet when I run the conformance test now I am now seeing "Failed to pull image \"gcr.io/kubernetes-e2e-test-images/pets/redis-installer:1.2\"", which won't work in my air-gapped environment.  Apparently, my custom repo config isn't overriding where sonobuoy looks for gcr.io-based images.  What label should I be using for gcr.io?   

**What did you expect to happen:**

I wouldn't expect sonobuoy to try to pull images that were not listed in the sonobuoy images output.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Sonobuoy version: v0.18.4
- Kubernetes version: (use `kubectl version`):
$ kubectl version --kubeconfig kubeconfig
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T21:03:42Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6+k3s1", GitCommit:"6f56fa1d68a5a48b8b6fdefa8eb7ead2015a4b3a", GitTreeState:"clean", BuildDate:"2020-07-16T20:46:15Z", GoVersion:"go1.13.11", Compiler:"gc", Platform:"linux/amd64"}
- Kubernetes installer & version: Rancher v.2.4.5
- Cloud provider or hardware configuration:  Openstack VMs
- OS (e.g. from `/etc/os-release`):  RHEL 7.8

**Comment by zubron** [comment]
Hi :wave: 

The registry configuration that you specify with Sonobuoy overrides the registry information used by the Kubernetes E2E framework: https://github.com/kubernetes/kubernetes/blob/v1.18.6/test/utils/image/manifest.go

**Comment by CDespeaux** [comment]
Hi Bridget,

Thank you for saving me from myself.  At one point I started running with the --e2e-focus for each SIG, not realizing that was now including tests that were not part of the conformance test.
