### ISSUE TITLE
Unable to Pull Image - k8s.gcr.io/conformance:v1.16.13-eks-2ba888

### ISSUE THREAD

**Issue by robinku07** [vmware-tanzu/sonobuoy#1163]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
I was trying to run the E2E test for NetworkPolicy 
sonobuoy run --e2e-focus "NetworkPolicy" --e2e-skip ""

After sometime we are getting the below error message:-
  Normal   Started    7m15s                   kubelet, ip-192-168-7-195.us-east-2.compute.internal  Started container sonobuoy-worker
  Normal   BackOff    6m (x5 over 7m14s)      kubelet, ip-192-168-7-195.us-east-2.compute.internal  Back-off pulling image "k8s.gcr.io/conformance:v1.16.13-eks-2ba888"
  Normal   Pulling    5m48s (x4 over 7m16s)   kubelet, ip-192-168-7-195.us-east-2.compute.internal  Pulling image "k8s.gcr.io/conformance:v1.16.13-eks-2ba888"
  Warning  Failed     5m47s (x4 over 7m15s)   kubelet, ip-192-168-7-195.us-east-2.compute.internal  Failed to pull image "k8s.gcr.io/conformance:v1.16.13-eks-2ba888": rpc error: code = Unknown desc = Error response from daemon: manifest for k8s.gcr.io/conformance:v1.16.13-eks-2ba888 not found
  Warning  Failed     5m47s (x4 over 7m15s)   kubelet, ip-192-168-7-195.us-east-2.compute.internal  Error: ErrImagePull
  Warning  Failed     2m13s (x21 over 7m14s)  kubelet, ip-192-168-7-195.us-east-2.compute.internal  Error: ImagePullBackOff
**What did you expect to happen:**
sonobuoy able to fetch the image and run the test.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Sonobuoy version: 0.18.4
- Kubernetes version: (use `kubectl version`): 1.16
- Kubernetes installer & version: 1.16
- Cloud provider or hardware configuration: AWS EKS
- OS (e.g. from `/etc/os-release`): Amazon Linux
- Sonobuoy tarball (which contains * below)

**Comment by walbertus** [comment]
Face the same issue with a similar error.

You need to add the flag `--kube-conformance-image-version 1.16.13` to bypass this issue.
