### ISSUE TITLE
Remove version number in names of released files

### ISSUE THREAD

**Issue by lzhecheng** [vmware-tanzu/sonobuoy#1165]
**Describe the solution you'd like**
I have a suggestion. If version number is removed in released files, users can always download the latest ones with the same link. It is helpful especially for CI.

E.g. link to current latest sonobuoy for linux:
https://github.com/vmware-tanzu/sonobuoy/releases/latest/download/sonobuoy_0.19.0_linux_amd64.tar.gz
If version number is removed:
https://github.com/vmware-tanzu/sonobuoy/releases/latest/download/sonobuoy_linux_amd64.tar.gz

Other project:
E.g. link to clusterctl for linux:
https://github.com/kubernetes-sigs/cluster-api/releases/latest/download/clusterctl-linux-amd64
https://github.com/kubernetes-sigs/cluster-api/releases

I am not sure why sonobuoy doesn't do like this. If there are any reasons, could you pleaes share them?

Thank you!

**Comment by vladimirvivien** [comment]
@lzhecheng 
Hi, thanks for reaching out. The Sonobuoy releases follow adopted standard practice of including the version number as part of the archive file name that is to be downloaded.  Unfortunately there is no easy way in use the latest URL from GitHub to point to the generated artifacts.

**Comment by lzhecheng** [comment]
@vladimirvivien, thank you for explanation! Then is it possible to put it on sonobuoy.io to download, like sonobuoy.io/download/sonobuoy_linux_amd64.tar.gz?
This is just a suggestion :) I understand it will add extra cost for cloud service.

**Comment by vladimirvivien** [comment]
@lzhecheng The content of sonobuoy.io is generated automatically and depends on what's available from GitHub.  So not at the moment.

**Comment by lzhecheng** [comment]
@vladimirvivien Thanks! I am closing this issue.
