### ISSUE TITLE
Not able to pull e2e images for pods to start 

### ISSUE THREAD

**Issue by chowmean** [vmware-tanzu/sonobuoy#1166]
Not able to pull image for e2e getting below error, are the images renamed or moved recently?

```
error streaming logs from container [e2e]: container "e2e" in pod "sonobuoy-e2e-job-18ca45e14eca4eea" is waiting to start: trying and failing to pull imageerror streaming logs from container [e2e]: container "e2e" in pod "sonobuoy-e2e-job-18ca45e14eca4eea" is waiting to start: trying and failing to pull imagenamespace="sonobuoy" pod="sonobuoy-e2e-job-18ca45e14eca4eea" container="sonobuoy-worker"
```

**Environment:**

- Sonobuoy version: 0.16.5
- Kubernetes version: (use `kubectl version`): v1.16
- Kubernetes installer & version: v1.16
- Cloud provider or hardware configuration: AWS
- OS (e.g. from `/etc/os-release`): Ubuntu 16
- Sonobuoy tarball (which contains * below) 0.16.5

**Comment by vladimirvivien** [comment]
@chowmean hi. 
What is the exact version if your cluster? Some patch versions of Kubernetes do not have released test images. So you have to specify the nearest minor version using the `--kube-conformance-image-version` flag when starting sonobuoy.

**Comment by vladimirvivien** [comment]
@chowmean Hi. Was this resolved for you ?

**Comment by chowmean** [comment]
Yes thanks a lot.

**Comment by chowmean** [comment]
@vladimirvivien should I add this in a doc somewhere? I am sure many people will be facing this issue?
