### ISSUE TITLE
Systemd plugin error causes run with --wait to exit immediately

### ISSUE THREAD

**Issue by cranzy** [vmware-tanzu/sonobuoy#1167]
**What steps did you take and what happened:**
I'm running the conformance tests for kube v1.18.8; the e2e plugin tests PASS with no issues; however the systemd plugin is constantly failing causing the test run with **--wait** flag to exit immediately after that happens.

**What did you expect to happen:**
The e2e tests to continue running until completion.

**Anything else you would like to add:**
Is there a way **--wait** to continue waiting even if error occurs in the s**ystemd plugin** . Disabling the systemd would work for me as well, as long as it doesn't affect the **--kube-conformance-image-version="$KUBE_IMAGE_VERSION"** run.
The error in the systemd plugin is:

`{"error":"No pod was scheduled on node ip-172-31-0-133.us-west-2.compute.internal within 10.498342517s. Check tolerations for plugin systemd-logs"}`
[202009110329_sonobuoy_4e076b74-dbd1-423f-a572-91fcbe323bd3.tar.gz](https://github.com/vmware-tanzu/sonobuoy/files/5221542/202009110329_sonobuoy_4e076b74-dbd1-423f-a572-91fcbe323bd3.tar.gz)

**Environment:**

- Sonobuoy version: 
Sonobuoy Version: v0.19.0
MinimumKubeVersion: 1.17.0
MaximumKubeVersion: 1.19.99
GitSHA: e03f9ee353717ccc5f58c902633553e34b2fe46a

- Kubernetes version: (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-09T19:10:58Z", GoVersion:"go1.15.1", Compiler:"gc", Platform:"darwin/amd64"}

- Cloud provider or hardware configuration:
AWS
- OS (e.g. from `/etc/os-release`): 
UBUNTU Bionic
- Sonobuoy tarball (which contains * below)

**Comment by vladimirvivien** [comment]
@cranzy Thank you for reaching out.
One workaround you could try to avoid running the systemd-logs plugin is to start your Sonobuoy run job with by specifying which plugin to run as follows: 
```
sonobuoy run --plugin e2e
```
The previous will run only the sonobuoy e2e plugin.

**Comment by cranzy** [comment]
@vladimirvivien If I run your suggested command `sonobuoy run --plugin e2e` is this still a valid conformance test run?

**Comment by vladimirvivien** [comment]
Yes. It justs runs the test plugin and skips log collection using systemd logs plugin
