### ISSUE TITLE
sonobuoy delete ---wait starvation scenario

### ISSUE THREAD

**Issue by jayunit100** [vmware-tanzu/sonobuoy#1170]
**What steps did you take and what happened:**

`sonobuoy delete --wait` seems to hang forever in certain cases....

- `sonobuoy run --e2e-focus "Conformance"`
- wait about a minute
-  `sonobuoy delete --wait` in a separate terminal
- youll notice that the wait never completes, even though all namespaces are gone.
- also in my caes, i saw that a child namespace didnt get deleted when i ran `delete`. 

Am assuming sonobuoy parent container would want to clean up the child e2e namespaces immediately on deletion.  

**What did you expect to happen:**

`sonobuoy delete --wait` will return once the entire `sonobuoy` namespace is gone.

**Comment by jayunit100** [comment]
additionally 

```
sonobuoy delete
```

returns an exit cod 0 EVEN IF THERE ARE NOW SONOBUOY RESOURCES hmmm

**Comment by jayunit100** [comment]
```

sonobuoy             Terminating   9m47s
➜  windows git:(master) ✗ kubectl get pods -n sonobuoy
No resources found in sonobuoy namespace.
➜  windows git:(master) ✗
```

**Comment by jayunit100** [comment]
NOTE: That IN THIS CLUSTER NAMESPACE DELETION DOESNT WORK AT ALL :) 

sorry @zubron this might be another one of my non bugs :)

**Comment by jayunit100** [comment]
@vladimirvivien

**Comment by vladimirvivien** [comment]
@jayunit100 is this a bug or a non-bug ?

**Comment by jayunit100** [comment]
imo it feels like a bug.  sonobuoy delete --wait should log if its running into problems and it cant finish its job after a a while ?

**Comment by vladimirvivien** [comment]
Let's keep this open to revisit.

**Comment by johnSchnake** [comment]
>  like say once every minute "still waiting on namespace deletion" or whatever

There are _some_ options for this, we definitely waffled back and forth about wanting output or not.

```
      --wait int[=60]                Wait for resources to be deleted before completing. 0 indicates do not wait. By providing --wait the default is to wait for 1 hour.
      --wait-output WaitOutputMode   Whether to enable spinner on Sonobuoy. Valid modes are Silent and Spinner (default Silent)
```

The spinner mode was useful to see that it is still running and can help prevent CI systems from reporting a lack of activity while it waits.

Everyone can have different ideas about how much output is the right amount, but it sounds like here you're suggesting a level we might call 'periodic' where its typically silent but gives periodic output on the status of the wait. Not a bad idea but I want to make sure our answer to these problems aren't to just keep adding more options which will rarely get used.

Other items on this ticket to think about though too.
