### ISSUE TITLE
deleting a node where sonobuoy pod lives -> namespace frozen

### ISSUE THREAD

**Issue by jayunit100** [vmware-tanzu/sonobuoy#1171]
**What steps did you take and what happened:**

deleted the node that sonobuoy pod was running on , just to see what happened.

**What did you expect to happen:**

the namespace `sonobuoy` was never deletable, and the sonobuoy pod was in Terminating state for ever

**Anything else you would like to add:**

```
E1008 22:59:20.231511       1 namespace_controller.go:162] deletion of namespace sonobuoy failed: unexpected items still remain in namespace: sonobuoy for gvr: /v1, Resource=pods
```

this is on k8s 1.18.3
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2020-01-14T00:09:19Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}

**Comment by vladimirvivien** [comment]
@jayunit100 did you happen to capture the log for the pod as it went in terminating state? Also, did you try to use sonobuoy delete to properly remove sonobuoy components as a unit?  Removing the pod directly may have broken things.

Nevertheless, we'll look into this.

**Comment by johnSchnake** [comment]
Is this a sonobuoy issue or a k8s issue? Seems like something wonky with k8s metadata that the pod gets stuck in the terminating state but I'm not sure that any fix would be on our side. TBD.

**Comment by vladimirvivien** [comment]
This can be closed.
