### ISSUE TITLE
CLI text update to better reflect Sonobuoy features/functionalities

### ISSUE THREAD

**Issue by vladimirvivien** [vmware-tanzu/sonobuoy#1172]
**Describe the solution you'd like**
Currently, many corners of the Sonobuoy CLI reflects its early assumptions and purpose of testing and conformance.  Sonobuoy has evolved since to be more of a generic job launcher on Kubernetes.  The text in the CLI should be updated to better reflect these features.

 * [ ] Update CLI command help text
 * [ ] Update CLI user messages
 * [ ] Update log messages

**Comment by johnSchnake** [comment]
We can do a sweep for relevant fixes; be sure to put any specific changes you wanted though.

**Comment by johnSchnake** [comment]
May want to wait until #1315 is farther along/done in order to do this just once. As we move those plugins it will become more clear which flags are misleading, need reworded, generalized, etc.
