### ISSUE TITLE
sonobuoy run --wait hangs on k3s environment on raspberry pis

### ISSUE THREAD

**Issue by CloudGrimm** [vmware-tanzu/sonobuoy#1174]
**What steps did you take and what happened:**
I am trying to run tests on my k8s infrastructure running on raspberry pis using sonobuoy as described on the how to get started.

![image](https://user-images.githubusercontent.com/22336209/96111556-a266ab00-0ee1-11eb-83cb-ce8e269b31f3.png)

**What did you expect to happen:**
have k8s tests run on the edge.

**Environment:**

- Sonobuoy version: v0.19.0
- Kubernetes version: (use `kubectl version`): v1.19.2
- Kubernetes installer & version: v.1.18.9+k3s1
- OS (e.g. from `/etc/os-release`): Raspberry Pi OS

**Comment by wilsonehusin** [comment]
hi @CloudGrimm, thanks for reporting the issue! we currently support `arm64`, so I would expect Sonobuoy to work on Raspberry Pi 4. Is your hardware `arm64`?

![image](https://user-images.githubusercontent.com/14004487/97207492-52a4a100-1777-11eb-912a-57ac3d637d57.png)

**Comment by CloudGrimm** [comment]
Yes it is, a raspberry pi 4 model B

**Comment by wilsonehusin** [comment]
@CloudGrimm does `docker pull sonobuoy/sonobuoy:v0.19.0` work in your setup?
