### ISSUE TITLE
sonobuoy Browser User Interface

### ISSUE THREAD

**Issue by m4rcoschmucki** [vmware-tanzu/sonobuoy#1180]
Hi all

I was able to install sonoboy and run it without errors/failures:

```
sonobuoy results $results

	Plugin: e2e
	Status: passed
	Total: 5232
	Passed: 303
	Failed: 0
	Skipped: 4929

	Plugin: systemd-logs
	Status: passed
	Total: 6
	Passed: 6
	Failed: 0
	Skipped: 0
```

But how can I access the Browser-User-Interface?

Many thanks for your feedback.

Regards,
Marco

**Comment by wilsonehusin** [comment]
hey @m4rcoschmucki, welcome to Sonobuoy! congratulations on the passing run 😄 

I think this might be helpful for you: [Sonobuoy snapshot layout / detailed result contents](https://sonobuoy.io/docs/v0.19.0/snapshot/).

There should be a JUnit XML file under `$results/plugins/e2e/results/global/junit_01.xml` or if you prefer the YAML version, it will be under `$results/plugins/e2e/sonobuoy_results.yaml`

**Comment by m4rcoschmucki** [comment]
Hi wilsonehsuin,

Thank you for your answer.
But these files are not really user friendly and not good to read in my opinion.
In addition, I've asked about the Browser-User-Interface, do you know about it?

**Comment by vladimirvivien** [comment]
@m4rcoschmucki currently, Sonobuoy does not have a UI.  We are exploring ways to bring more user-friendliness when access data generated by Sonobuoy plugins.
