### ISSUE TITLE
How to ignore certificate error?

### ISSUE THREAD

**Issue by udhos** [vmware-tanzu/sonobuoy#1182]
**What steps did you take and what happened:**
sonobuoy run --wait
ERRO[0001] could not create sonobuoy client: couldn't get sonobuoy api helper: could not get api group resources: Get "https://xxxxxxx.us-east-1.eks.amazonaws.com/api?timeout=32s": x509: certificate signed by unknown authority

**What did you expect to happen:**
See sonobuoy output.

**Anything else you would like to add:**
How can i tell sonobuoy to ignore certificate errors?

**Environment:**
- Sonobuoy version: v0.19.0
- Kubernetes version: (use `kubectl version`): 1.17.9
- Kubernetes installer & version: EKS
- Cloud provider or hardware configuration: AWS
- OS (e.g. from `/etc/os-release`):  Amazon Linux 2
- Sonobuoy tarball (which contains * below): sonobuoy_0.19.0_linux_amd64.tar.gz

**Comment by vladimirvivien** [comment]
@udhos There is no way to tell sonobuoy to ignore an error.  Are you customizing the certs setup ?

**Comment by udhos** [comment]
@vladimirvivien Due to limitations in our corp vpn, we have to use kubectl with `--insecure-skip-tls-verify=true`. I know it is gross, but we are unable to fix it anytime soon. I hoped that there was a similar option for sonobuoy.

**Comment by vladimirvivien** [comment]
@udhos in that case, you may need to create a cluster entry that skips the tls check in your kubeconfig file.  See https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/#define-clusters-users-and-contexts . 

Then, make sure Sonobuoy uses the right cluster/context.

**Comment by udhos** [comment]
It worked, thanks!
