### ISSUE TITLE
avoid running sonobuoy on windows nodes until supported

### ISSUE THREAD

**Issue by jayunit100** [vmware-tanzu/sonobuoy#1187]
**What steps did you take and what happened:**

By default, it looks like the sonobuoy pod will happily try to run on a windows node:

```
sonobuoy run --e2e-focus="guestbook"
```
results in
```
 sonobuoy                sonobuoy                                      ●             0/1                                0 ImagePullBackOff             100.1.2.14              win-h0c364gqvjh              107s     
```

**What did you expect to happen:**

Sonobuoy would target linux nodes since it doesnt yet support windows execution

**Anything else you would like to add:**

**Environment:**

- Sonobuoy version: 1.19.0

**Comment by wilsonehusin** [comment]
@jayunit100 just to make sure I understand your intent -- your request is to change the _default behavior_, not necessarily creating a new implementation structure, correct? alternatively can you achieve this today with `--aggregator-node-selector`?

**Comment by jayunit100** [comment]
I think that only solves the problem for aggregator.

We need this in sonobuoy pods as well bc otherwise they croak in a mixed mode cluster bc they schedule to windows nodes

**Comment by vladimirvivien** [comment]
@wilsonehusin I think there might be a need for `--plugin-node-selector` modifies the plugin pods.  I guess a work around (a way to test this) is to do a `sonobuoy gen` then modify the yaml and update the plugin section to include the selector.

**Comment by vladimirvivien** [comment]
Not stale
