### ISSUE TITLE
Sonobuoy failed to run CIS scans on new TKG clusters 

### ISSUE THREAD

**Issue by jzvmw** [vmware-tanzu/sonobuoy#1197]
The scans got stuck with `time="2020-11-25T16:10:49Z" level=error msg="error loading sonobuoy configuration: Configured plugin kube-benchtkg does not exist"` and didn't have annotation: sonobuoy.hept.io/status either

**Comment by vladimirvivien** [comment]
@jzvmw do you have any additional info on this?

**Comment by johnSchnake** [comment]
If I can get a full tarball or instructions on how to repro I can help address this.

From the outset it sounds like at some point some YAML was saved in CI/code as the "sonobuoy config" and then something was modified but not full/correctly. This led to sonobuoy thinking it should have that plugin, but it doesnt.
