### ISSUE TITLE
sonobuoy test plugin e2e failed

### ISSUE THREAD

**Issue by GH-Djeff** [vmware-tanzu/sonobuoy#1207]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
##############################################################
Hello,
i've run "sonobuoy run --wait" for an hour and the status is failed for plugin e2e
sonobuoy results $results
Plugin: systemd-logs
Status: passed
Total: 3
Passed: 3
Failed: 0
Skipped: 0

Plugin: e2e
Status: failed
Total: 1
Passed: 0
Failed: 1
Skipped: 0

Failed tests:
timeout waiting for results
Can you help me with that please
Here joint the log file

#####################################

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Sonobuoy version: 
Sonobuoy Version: v0.20.0
MinimumKubeVersion: 1.17.0
MaximumKubeVersion: 1.99.99
GitSHA: f6e19140201d6bf2f1274bf6567087bc25154210
API Version check skipped due to missing `--kubeconfig` or other error

- Kubernetes version: (use `kubectl version`):
-Client Version: v1.20.1
Server Version: v1.20.1
- Kubernetes installer & version: 1.20
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`): 
PRETTY_NAME="Debian GNU/Linux bullseye/sid"
NAME="Debian GNU/Linux"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

- Sonobuoy tarball (which contains * below)
- sonobuoy_0.20.0_linux_amd64.tar.gz
[202101081844_sonobuoy_049b2577-4551-44ff-82ed-e3c17dda4839.tar.gz](https://github.com/vmware-tanzu/sonobuoy/files/5789631/202101081844_sonobuoy_049b2577-4551-44ff-82ed-e3c17dda4839.tar.gz)

**Comment by wilsonehusin** [comment]
@GH-Djeff thanks for submitting the issue!

It seems that Sonobuoy aggregator failed to retrieve results from the e2e test runner. Can you please run it again and while the status is running, find the pod name with e2e (i.e. `kubectl -n sonobuoy get pods` and find the one with `sonobuoy-e2e-<sha>`) and look at the description to see if everything is operating normally (i.e. `kubectl -n sonobuoy describe sonobuoy-e2e-<sha>`).

**Comment by GH-Djeff** [comment]
@wilsonehusin 
I run it again, unfortunately it failed.
Here are the result on the commands you telle me to run 
#####################################
21 [13:57:44] root@km1: /home/djeff  # sonobuoy run --wait
INFO[0000] created object                                name=sonobuoy namespace= resource=namespaces
INFO[0001] created object                                name=sonobuoy-serviceaccount namespace=sonobuoy resource=serviceaccounts
INFO[0001] created object                                name=sonobuoy-serviceaccount-sonobuoy namespace= resource=clusterrolebindings
INFO[0001] created object                                name=sonobuoy-serviceaccount-sonobuoy namespace= resource=clusterroles
INFO[0001] created object                                name=sonobuoy-config-cm namespace=sonobuoy resource=configmaps
INFO[0001] created object                                name=sonobuoy-plugins-cm namespace=sonobuoy resource=configmaps
INFO[0003] created object                                name=sonobuoy namespace=sonobuoy resource=pods
INFO[0003] created object                                name=sonobuoy-aggregator namespace=sonobuoy resource=services
ERRO[1204] error attempting to run sonobuoy: waiting for run to finish: Pod entered a fatal terminal status: failed
####################################################################################
Every 2.0s: sonobuoy status                                                                                                                                                         km1: Sat Jan  9 14:21:19 2021

         PLUGIN     STATUS   RESULT   COUNT
            e2e     failed                1
   systemd-logs   complete                1
   systemd-logs    running                2

Sonobuoy has failed. You can see what happened with `sonobuoy logs`.
#################################################################################
Every 2.0s: kubectl -n sonobuoy get pods -owide                                                                                                                                     km1: Sat Jan  9 14:21:40 2021

NAME                                                      READY   STATUS    RESTARTS   AGE   IP              NODE   NOMINATED NODE   READINESS GATES
sonobuoy                                                  1/1     Running   0          22m   10.102.127.30   kn1    <none>           <none>
sonobuoy-e2e-job-f6d679d6afd44a5c                         0/2     Error     0          21m   10.64.132.220   km1    <none>           <none>
sonobuoy-systemd-logs-daemon-set-6d11ea3767484d37-htpzm   2/2     Running   2          21m   192.168.1.50    km1    <none>           <none>
sonobuoy-systemd-logs-daemon-set-6d11ea3767484d37-jqdr2   2/2     Running   2          21m   192.168.1.52    kn2    <none>           <none>
sonobuoy-systemd-logs-daemon-set-6d11ea3767484d37-rhxlb   2/2     Running   0          21m   192.168.1.51    kn1    <none>           <none>
################################################################################################

7 [14:18:35] root@km1: /home/djeff  # kubectl -n sonobuoy describe pod sonobuoy-e2e-job-f6d679d6afd44a5c
Name:         sonobuoy-e2e-job-f6d679d6afd44a5c
Namespace:    sonobuoy
Priority:     0
Node:         km1/192.168.1.50
Start Time:   Sat, 09 Jan 2021 14:00:14 +0100
Labels:       component=sonobuoy
              sonobuoy-component=plugin
              sonobuoy-plugin=e2e
              sonobuoy-run=f6d679d6afd44a5c
              tier=analysis
Annotations:  cni.projectcalico.org/podIP:
              cni.projectcalico.org/podIPs:
              sonobuoy-driver: Job
              sonobuoy-plugin: e2e
Status:       Failed
IP:           10.64.132.220
IPs:
  IP:  10.64.132.220
Containers:
  e2e:
    Container ID:  docker://f9aa62811d59efea231c7bbb22ebf2865b1d7dc9bc36533ece004bb5de2602de
    Image:         k8s.gcr.io/conformance:v1.20.1
    Image ID:      docker-pullable://k8s.gcr.io/conformance@sha256:9f165f5d6393246eae4ea77cfc99d7f39b7475bd7650c72759d44f1f2cd3bafe
    Port:          <none>
    Host Port:     <none>
    Command:
      /run_e2e.sh
    State:          Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Sat, 09 Jan 2021 14:03:51 +0100
      Finished:     Sat, 09 Jan 2021 14:14:03 +0100
    Ready:          False
    Restart Count:  0
    Environment:
      E2E_FOCUS:          \[Conformance\]
      E2E_SKIP:           \[Disruptive\]|NoExecuteTaintManager
      E2E_PARALLEL:       false
      E2E_USE_GO_RUNNER:  true
      E2E_EXTRA_ARGS:     --progress-report-url=http://localhost:8099/progress
    Mounts:
      /tmp/results from results (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from sonobuoy-serviceaccount-token-pdbj4 (ro)
  sonobuoy-worker:
    Container ID:  docker://ed4988baee372f93acbb9146842068dc69f21c6b5d5d3d83b95dff32d73560ae
    Image:         sonobuoy/sonobuoy:v0.20.0
    Image ID:      docker-pullable://sonobuoy/sonobuoy@sha256:ee14fd553315d41a72f705ad4e792809fa3c99f0fa73fec4c3af3d3da8d13ee5
    Port:          <none>
    Host Port:     <none>
    Command:
      /sonobuoy
    Args:
      worker
      global
      -v
      5
      --logtostderr
    State:          Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Sat, 09 Jan 2021 14:04:07 +0100
      Finished:     Sat, 09 Jan 2021 14:20:36 +0100
    Ready:          False
    Restart Count:  0
    Environment:
      NODE_NAME:                (v1:spec.nodeName)
      RESULTS_DIR:             /tmp/results
      RESULT_TYPE:             e2e
      AGGREGATOR_URL:          https://[10.102.127.30]:8080
      CA_CERT:                 -----BEGIN CERTIFICATE-----
                               MIIB8TCCAZegAwIBAgIBATAKBggqhkjOPQQDAjBgMQwwCgYDVQQGEwNVU0ExFjAU
                               BgNVBAcTDVBhbG8gQWx0bywgQ0ExDzANBgNVBAoTBlZNd2FyZTERMA8GA1UECxMI
                               U29ub2J1b3kxFDASBgNVBAMTC3Nvbm9idW95LWNhMB4XDTIxMDEwOTEzMDAxMFoX
                               DTIxMDExMTEzMDAxMFowYDEMMAoGA1UEBhMDVVNBMRYwFAYDVQQHEw1QYWxvIEFs
                               dG8sIENBMQ8wDQYDVQQKEwZWTXdhcmUxETAPBgNVBAsTCFNvbm9idW95MRQwEgYD
                               VQQDEwtzb25vYnVveS1jYTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABHrdke33
                               BtrupJxltT/RwmO4d/J5T4bmVlmL6T2w7bPnw0+4Kei7jVLKLddz524aK6aaBmH5
                               PqjL8FTroXZ1ay2jQjBAMA4GA1UdDwEB/wQEAwICBDAPBgNVHRMBAf8EBTADAQH/
                               MB0GA1UdDgQWBBSOvhWM+YjWgWcpJNwJR6od5UBsdjAKBggqhkjOPQQDAgNIADBF
                               AiEA+WitgVQD52shXdJ8Ti7e6kPqAzCd8q21wp0TDhiKi18CIFyxIohyBIFVcvsp
                               6BEt0g5R8Svq9WS21FyGHAPeH+AG
                               -----END CERTIFICATE-----

      CLIENT_CERT:             <set to the key 'tls.crt' in secret 'sonobuoy-plugin-e2e-f6d679d6afd44a5c'>  Optional: false
      CLIENT_KEY:              <set to the key 'tls.key' in secret 'sonobuoy-plugin-e2e-f6d679d6afd44a5c'>  Optional: false
      SONOBUOY_PROGRESS_PORT:  8099
    Mounts:
      /tmp/results from results (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from sonobuoy-serviceaccount-token-pdbj4 (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  results:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  sonobuoy-serviceaccount-token-pdbj4:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  sonobuoy-serviceaccount-token-pdbj4
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     CriticalAddonsOnly op=Exists
                 kubernetes.io/e2e-evict-taint-key op=Exists
                 node-role.kubernetes.io/master:NoSchedule op=Exists
                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  22m   default-scheduler  Successfully assigned sonobuoy/sonobuoy-e2e-job-f6d679d6afd44a5c to km1
  Normal  Pulling    20m   kubelet            Pulling image "k8s.gcr.io/conformance:v1.20.1"
  Normal  Pulled     18m   kubelet            Successfully pulled image "k8s.gcr.io/conformance:v1.20.1" in 2m9.676360582s
  Normal  Created    18m   kubelet            Created container e2e
  Normal  Started    18m   kubelet            Started container e2e
  Normal  Pulled     18m   kubelet            Container image "sonobuoy/sonobuoy:v0.20.0" already present on machine
  Normal  Created    18m   kubelet            Created container sonobuoy-worker
  Normal  Started    18m   kubelet            Started container sonobuoy-worker
############################################################################################
Here joint the sonobuoy lo fily
[sonobuoy.log](https://github.com/vmware-tanzu/sonobuoy/files/5791167/sonobuoy.log)

**Comment by wilsonehusin** [comment]
@GH-Djeff can you describe more about your cluster? From the logs it seems that Sonobuoy launched the jobs properly and your cluster is failing for Kubernetes conformance. In other words, at the moment I don't think this is a bug in Sonobuoy.

**Comment by GH-Djeff** [comment]
Hello,
it's a little 3 nodes Kubernetes cluster with 8GB and 8 vCPU per node.
The OS is Debian 
The cluster is for testing purpose.
The cluster is not on the cloud but in my On premise virtual environment.
Maybe i don't have the minimum requirements. 
Can you check that for me please ?

Regards,
Djeff

**Comment by wilsonehusin** [comment]
@GH-Djeff sounds likely that your cluster setup is not complete. I would probably start from checking if the nodes are acknowledging each other (i.e. `kubectl get nodes -o wide` should show 3 nodes as you described). I would also recommend looking into [Kubernetes The Hard Way](https://github.com/kelseyhightower/kubernetes-the-hard-way) as a guide and joining Kubernetes Slack workspace and reach out to `#kubernetes-novice` 😃
