### ISSUE TITLE
Cluster version detection should omit everything after +

### ISSUE THREAD

**Issue by wilsonehusin** [vmware-tanzu/sonobuoy#1211]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

Running Sonobuoy on a distribution cluster has specific versions. For example, `1.20.0+gke.1` or `1.20.2+vmware.1`. Seems like in certain cases, Sonobuoy would fail to interpret the version number for pulling Conformance image.

**What did you expect to happen:**

Sonobuoy to recognize `-alpha.x` and `-beta.x` suffixes, but ignore `+vendor.x` suffix.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Sonobuoy version: 
- Kubernetes version: (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`): 
- Sonobuoy tarball (which contains * below)

**Comment by johnSchnake** [comment]
Looking at it, I tend to agree. The info that follows the `+` is supposed to be build metadata and not really a differentiator of the version at all.

The semver documentation states:

> Build metadata MAY be denoted by appending a plus sign and a series of dot separated identifiers immediately following the patch or pre-release version. Identifiers MUST comprise only ASCII alphanumerics and hyphens [0-9A-Za-z-]. Identifiers MUST NOT be empty. Build metadata MUST be ignored when determining version precedence. Thus two versions that differ only in the build metadata, have the same precedence. Examples: 1.0.0-alpha+001, 1.0.0+20130313144700, 1.0.0-beta+exp.sha.5114f85, 1.0.0+21AF26D3—-117B344092BD.

The sonobuoy has some comment regarding GKE builds having something like `x.y+` causing problems but it also seems like for choosing conformance images the major.minor.patch-prerelease is sufficient.

Anyone have a different understanding or experience?
