### ISSUE TITLE
Failed to pull image k8s.gcr.io/conformance:v1.20.2-34 during sonobuoy run

### ISSUE THREAD

**Issue by davecore82** [vmware-tanzu/sonobuoy#1213]
**What steps did you take and what happened:**

I'm trying to run the sonobuoy performance tests with `./sonobuoy run --e2e-focus="Feature:Performance" --wait` but the sonobuoy-e2e-job pod fails to pull its image with the error:

`Failed to pull image "k8s.gcr.io/conformance:v1.20.2-34": rpc error: code = NotFound desc = failed to pull and unpack image "k8s.gcr.io/conformance:v1.20.2-34": failed to resolve reference "k8s.gcr.io/conformance:v1.20.2-34": k8s.gcr.io/conformance:v1.20.2-34: not found`

I am using the tarball from https://github.com/vmware-tanzu/sonobuoy/releases/download/v0.20.0/sonobuoy_0.20.0_linux_amd64.tar.gz

**What did you expect to happen:**

I expect to be able to run that test out of the box by downloading the most recent tarball and running the test.

**Anything else you would like to add:**

I am running this in a microk8s environment on my laptop.

**Environment:**

- Sonobuoy version: v0.20.0
- Kubernetes version: (use `kubectl version`): v1.20.2-34+350770ed07a558
- Kubernetes installer & version: microk8s (`sudo snap install microk8s --classic`)
- Cloud provider or hardware configuration: Nitro AN515-53 V1.26 laptop
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04.2 LTS
- Sonobuoy tarball (which contains * below)
https://github.com/vmware-tanzu/sonobuoy/releases/download/v0.20.0/sonobuoy_0.20.0_linux_amd64.tar.gz

**Comment by wilsonehusin** [comment]
@davecore82, thanks for reporting the issue. Sonobuoy by default looks for conformance image which matches your cluster. I can see your `kubectl version` output starts with `v1.20.2-34...` which makes Sonobuoy think that the conformance image to pull is `v1.20.2-34` when it doesn't exist -- the right version would be `v1.20.2`.

In short, the solution is to run `sonobuoy run --kube-conformance-image-version v1.20.2`.

This makes me wonder though, has this ever worked for your setup? I'm not familiar with microk8s versioning scheme, but we don't typically ignore on `-` because we want to support pre-releases (e.g. `v1.20.0-alpha.2`).

**Comment by davecore82** [comment]
@wilsonehusin It's the first time I try to run Sonobuoy on microk8s.

Specifying the kube-conformance-image-version works. Thank you!

`./sonobuoy run --e2e-focus="Feature:Performance" --kube-conformance-image-version v1.20.2 --wait`

**Comment by davecore82** [comment]
@wilsonehusin   I just tried with a GKE cluster version 1.18.12-gke.1210 instead and I have the same issue with the gke version:

Failed to pull image "k8s.gcr.io/conformance:v1.18.12-gke.1210": rpc error: code = Unknown desc = Error response from daemon: manifest for k8s.gcr.io/conformance:v1.18.12-gke.1210 not found: manifest unknown: Failed to fetch "v1.18.12-gke.1210" from request "/v2/conformance/manifests/v1.18.12-gke.1210".

```
davecore@davecorelaptop:~/sonobuoy$ kubectl version

Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-17T02:13:01Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.12-gke.1210", GitCommit:"199a41188dc0ca5d6d95b1cc7e8ba96e05f9dd0a", GitTreeState:"clean", BuildDate:"2021-02-05T18:03:16Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by wilsonehusin** [comment]
@davecore82 thanks for reporting back. That's slightly unexpected because I've always thought that vendors use `+` to append their vendor build, at least that's what my memory serves from looking at what's reported by others. Does the `--kube-conformance-image-version` flag works with GKE as well?

**Comment by davecore82** [comment]
@wilsonehusin   Yes I used `--kube-conformance-image-version v1.18.12` and it pulled the image successfully.

**Comment by wilsonehusin** [comment]
I will keep this issue opened for now -- I think the reasonable fix for us is to guide users on troubleshooting this because it doesn't sound very likely to enforce all vendors with a scheme for their builds 😄 

Let me know if you have thoughts and thanks again for reporting!

**Comment by z0rc** [comment]
Would it be reasonable for sonobuoy to at least try to parse kubernetes server semver? From user perspective server version is still easily parseable and it would be better to have something like this when sonobuoy runs:
```
Kubernetes server version: v1.18.12-gke.1210
Assuming Kubernetes version v1.18.12 for conformance testing, if you believe this is wrong version, please specify correct version using '--kube-conformance-image-version' parameter.
```
This way user will be aware of which version is tested against, have better insight on why image pulls fail and knows how to fix this for their specific case.

For semver detection using simple regex `^v\d+\.\d+\.\d+` should be sufficient, given Kubernetes is set to follow it for foreseeable future.

**Comment by wilsonehusin** [comment]
I think we do parse the server semver https://github.com/vmware-tanzu/sonobuoy/blob/883fc9060c867dbe7dd8d9d926cae0ea3803f900/pkg/image/imageversion.go#L70-L115

However we had been operating with the thought that anything after `-` is pre-release (e.g. `v1.21.0-alpha.3+vendor`). I wonder if this change from GKE is new 🤔

**Comment by z0rc** [comment]
Another data point, AWS EKS does something similar:
```
% kubectl version
Client Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.4-dirty", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"dirty", BuildDate:"2021-03-15T09:58:13Z", GoVersion:"go1.16.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.6-eks-49a6c0", GitCommit:"49a6c0bf091506e7bafcdb1b142351b69363355a", GitTreeState:"clean", BuildDate:"2020-12-23T22:10:21Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```
