### ISSUE TITLE
Sonobuoy fails running plugin hosted behind https due to missing root certificates

### ISSUE THREAD

**Issue by fiunchinho** [vmware-tanzu/sonobuoy#1215]
**What steps did you take and what happened:**
When trying to use the sonobuoy docker image to run sonobuoy using a third party plugin hosted on Github with the `--plugin` flag, sonobuoy failed with `x509: certificate signed by unknown authority` because the Docker image has no root certificates installed.

**What did you expect to happen:**
Sonobuoy is able to fetch the plugin when using https.

**Environment:**

- Sonobuoy version: `v0.20.0`
- Kubernetes version: (use `kubectl version`):

**Comment by wilsonehusin** [comment]
hey @fiunchinho thanks for reaching out! I'm curious, can you elaborate more on which plugin and which step ended with x509 error?

Also, did you compile the binary yourself or did you get it from our releases page?

**Comment by fiunchinho** [comment]
Sure! We have our own plugin that runs some tests. The plugin `yaml` file is hosted on a Github repository so when running `sonobuoy run --plugin github.com/company/repo/plugin.yaml` we get an error `x509: certificate signed by unknown authority`. If I run `sonobuoy` from a custom docker image that contains root certificates, then everything works just fine.

We are using the sonobuoy docker image tagged as `v0.20.0`. You can easily get the same error running the docker image like `docker run --rm -it sonobuoy/sonobuoy:v0.20.0 bash` , and then trying to `sonobuoy run` a plugin which is hosted using https.

**Comment by wilsonehusin** [comment]
and it was running fine on v0.19?

😬 this might have something to do with go1.15 handling CAs differently

I'll try this in my morning, but if I recall correctly we were still able to do it with our plugins.

one more question while I'm still up: do you happen to be running it behind a proxy or some other indirection of network setup?

**Comment by fiunchinho** [comment]
> and it was running fine on v0.19?
> 
>  this might have something to do with go1.15 handling CAs differently
> 
> I'll try this in my morning, but if I recall correctly we were still able to do it with our plugins.
> 
> one more question while I'm still up: do you happen to be running it behind a proxy or some other indirection of network setup?

Did you manage to reproduce it? I'm not behind a proxy.

**Comment by wilsonehusin** [comment]
@fiunchinho I can't reproduce it unfortunately

```
❯ sonobuoy run --plugin https://raw.githubusercontent.com/vmware-tanzu/sonobuoy-plugins/master/cluster-inventory/cluster-inventory.yaml
INFO[0000] created object                                name=sonobuoy namespace= resource=namespaces
INFO[0000] created object                                name=sonobuoy-serviceaccount namespace=sonobuoy resource=serviceaccounts
INFO[0000] created object                                name=sonobuoy-serviceaccount-sonobuoy namespace= resource=clusterrolebindings
INFO[0000] created object                                name=sonobuoy-serviceaccount-sonobuoy namespace= resource=clusterroles
INFO[0000] created object                                name=sonobuoy-config-cm namespace=sonobuoy resource=configmaps
INFO[0000] created object                                name=sonobuoy-plugins-cm namespace=sonobuoy resource=configmaps
INFO[0000] created object                                name=sonobuoy namespace=sonobuoy resource=pods
INFO[0000] created object                                name=sonobuoy-aggregator namespace=sonobuoy resource=services

❯ sonobuoy status
              PLUGIN     STATUS   RESULT   COUNT
   cluster-inventory   complete                1

Sonobuoy plugins have completed. Preparing results for download.

❯ sonobuoy retrieve
202102231426_sonobuoy_000edabc-be4e-4f44-815b-1ade6ae7699f.tar.gz
```

**Comment by wilsonehusin** [comment]
oh I missed this part

> When trying to use the sonobuoy **docker image to run sonobuoy**...

I can reproduce it with:

```
$ docker run --rm -it sonobuoy/sonobuoy:v0.20.0 /sonobuoy run --plugin https://raw.githubusercontent.com/vmware-tanzu/sonobuoy-plugins/master/cluster-inventory/cluster-inventory.yaml
```

this is a use case we don't really support / consider to be honest. any reason that you went towards this path instead of running the CLI natively on your host?

**Comment by fiunchinho** [comment]
Our intention was to run it as a step on a [CI/CD tool called tekton](https://tekton.dev/) which uses Docker images as pipeline steps. I believe other tools on this space use a similar approach.

**Comment by wilsonehusin** [comment]
I see, that makes sense. We are switching our base image from `debian` to `distroless` and the change is already on master. Looks like this issue no longer exists on our `HEAD`. Next release is coming in a few days, but until then I suggest you try `sonobuoy/sonobuoy:master`.

```
docker run --network host --rm -v $HOME/.kube/config:/.kubeconfig -it sonobuoy/sonobuoy:master \
  /sonobuoy run --kubeconfig /.kubeconfig --sonobuoy-image sonobuoy/sonobuoy:master \
  --plugin https://raw.githubusercontent.com/vmware-tanzu/sonobuoy-plugins/master/cluster-inventory/cluster-inventory.yaml
```

The caveat of using `master` tag is that you need to explicitly say `--sonobuoy-image sonobuoy/sonobuoy:master` or it will be stuck on `ImagePullBackoff` trying to fetch a private tag.

**Comment by fiunchinho** [comment]
That's great. So if it's fixed on `master` I believe we can close this then. Thank you.

**Comment by wilsonehusin** [comment]
Thanks again for reporting back! @fiunchinho

**Comment by vladimirvivien** [comment]
Thanks @wilsonehusin for looking into this. That's awesome.
