### ISSUE TITLE
Airgapped image config does not override all container registries in e2e conformance tests

### ISSUE THREAD

**Issue by jcstryker** [vmware-tanzu/sonobuoy#1223]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

So in our cluster we use an OPA Gatekeeper based admission webhook to enforce the sourcing of images from an internal mirror.

This puts us in the "airgapped" use case for sonobuoy. So we use the `--e2e-repo-config` flag to map the test images to internal sources.

However it seems that not all image registries are being overwritten, we have a few failing tests due to the use of outside images e.g.

- `Kubernetes e2e suite.[sig-apps] Deployment deployment should support rollover [Conformance]`
```
ReplicaFailure,Status:True,Reason:FailedCreate,Message:admission webhook "validation.gatekeeper.sh" denied the request: [denied by repo-is-artifactory] container <redis-slave> has an invalid image repo <gcr.io/google_samples/gb-redisslave:nonexistent>, allowed repos are
```
- `Kubernetes e2e suite.[sig-apps] Deployment deployment should support proportional scaling [Conformance]`
```
ReplicaFailure,Status:True,Reason:FailedCreate,Message:admission webhook "validation.gatekeeper.sh" denied the request: [denied by repo-is-artifactory] container <httpd> has an invalid image repo <webserver:404>, allowed repos are
```
- `Kubernetes e2e suite.[sig-apps] Daemon set [Serial] should rollback without unnecessary restarts [Conformance]`
```
Mar 18 21:03:23.674: INFO: At 2021-03-18 20:57:44 +0000 UTC - event for daemon-set: {daemonset-controller } FailedCreate: Error creating: admission webhook "validation.gatekeeper.sh" denied the request: [denied by repo-is-artifactory] container <app> has an invalid image repo <foo:non-existent>, allowed repos are 
```
- `Kubernetes e2e suite.[sig-api-machinery] AdmissionWebhook [Privileged:ClusterAdmin] should mutate pod and apply defaults after mutation [Conformance]`
```
Message: "admission webhook \"validation.gatekeeper.sh\" denied the request: [denied by repo-is-artifactory] container <webhook-added-init-container> has an invalid image repo <webhook-added-image>, allowed repos are 
```
Using this repo config yaml (produced by `sonobuoy gen default-image-config`
```
buildImageRegistry: artifactory-k8sgcr.<mirror>/build-image
dockerGluster: artifactory-dockerhub.<mirror>/gluster
dockerLibraryRegistry: artifactory-dockerhub.<mirror>
e2eRegistry: artifactory-gcr.<mirror>/kubernetes-e2e-test-images
e2eVolumeRegistry: artifactory-gcr.<mirror>/kubernetes-e2e-test-images/volume
gcAuthenticatedRegistry: artifactory-gcr.<mirror>/authenticated-image-pulling
gcRegistry: artifactory-k8sgcr.<mirror>
gcrReleaseRegistry: artifactory-gcr.<mirror>/gke-release
promoterE2eRegistry: artifactory-k8sgcr.<mirror>/e2e-test-images
sigStorageRegistry: artifactory-k8sgcr.<mirror>/sig-storage
googleContainerRegistry: artifactory-gcr.<mirror>/google-containers
sampleRegistry: artifactory-gcr.<mirror>/google-samples
invalidRegistry: artifactory-dockerhub.<mirror>/invalid
privateRegistry: artifactory-gcr.<mirror>/k8s-authenticated-test
```

And this sonobuoy command

```
sonobuoy run --wait --wait-output spinner \
--plugin e2e \
--e2e-repo-config $repo_config_yaml \
--kube-conformance-image artifactory-k8sgcr.<mirror>/conformance:$k8s_version \ 
--sonobuoy-image artifactory-dockerhub.<mirror>/sonobuoy/sonobuoy:$sonobuoy_version
```

**What did you expect to happen:**

All e2e conformance tests pass

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

Without the constraint in place, all tests are passing. So we would expect the same with the contraint in place.

**Environment:**

- Sonobuoy version: 
```
Sonobuoy Version: v0.20.0
MinimumKubeVersion: 1.17.0
MaximumKubeVersion: 1.99.99
GitSHA: 
API Version:  v1.19.7
```
- Kubernetes version: (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.4-dirty", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"dirty", BuildDate:"2021-03-15T10:03:32Z", GoVersion:"go1.16.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:15:20Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes installer & version:
We are using kOps
```
Version 1.19.0 (git-04d36d7d92c72601efd918877fc180c846129ffb)
```
- Cloud provider or hardware configuration:
AWS
- OS (e.g. from `/etc/os-release`): 
Amazon Linux
- Sonobuoy tarball (which contains * below)

**Comment by johnSchnake** [comment]
I know a lot has changed with the airgap/etc logic in the past year. Let me take a look at it. Thanks for the report!

**Comment by johnSchnake** [comment]
So one of the goals of a recent change to Sonobuoy was to avoid being tied to the k8s test images in this region of code. However, it still requires understanding something about the registries those images come from due to this translation stuff.

The registry list is not static and changes over time, plus some of the logic here prevents stuff from being overridden (e.g. fake registry, registry with auth, etc).

This will take a bit more time to dissect the solution to but there is definitely a problem that we have to fix now or it will continue to get worse.

**Comment by jcstryker** [comment]
Understood, thanks. Yeah it seems like a tricky thing to keep up with.

Let me know if I can help test or get you more information on our use case.

**Comment by johnSchnake** [comment]
`Kubernetes e2e suite.[sig-api-machinery] AdmissionWebhook [Privileged:ClusterAdmin] should mutate pod and apply defaults after mutation [Conformance]` seems like a test that just breaks the airgap capabilities of users.   It sets up a mutating webhook and then changes the containers to hardcoded string values. As a result there isnt a way to override the registry.

Also, when I look up the upstream logic for this registry translation I also see that this inability to translate some registries is also broken. For example, you cant seem to override:
 - GcAuthenticatedRegistry: "gcr.io/authenticated-image-pulling"
 - PromoterE2eRegistry:     "k8s.gcr.io/e2e-test-images"
 - BuildImageRegistry:      "k8s.gcr.io/build-image"
 - InvalidRegistry:         "invalid.com/invalid"
 - GcHttpdRegistry:         "k8s.gcr.io/e2e-test-images"
 - MicrosoftRegistry:       "mcr.microsoft.com"
 
I'm going to raise this upstream. Even for them they can't seem to avoid drift between people adding new registries and ensuring the registry substitution works. IMO it seems like they should try something less fancy and just allow some regexp matching and straight substitution instead of an exact structure with yaml parsing.

Only one of your test failures was even included in the set of registries that are accounted for in this structure; the other ones are tests that just hardcoded values and went around the k8s logic for choosing images entirely. 👎

**Comment by johnSchnake** [comment]
https://github.com/kubernetes/kubernetes/pull/100753 Merged so this should be partially fixed upstream. Will have to review and see what else is lacking.

Do you know the easiest way to repro? I haven't tried extensively but it would be convenient if we could set some option on our kind cluster to simulate airgap or to turn off pulling from outside registries.

**Comment by jcstryker** [comment]
Hey thanks for pushing for this this fix, really appreciate it. After some searching I wasn't able to find an easy way to repro this without some work.

It seems the preferred way to accomplish this in vanilla Kubernetes is to use some form of admission controller. This can be with OPA Gatekeeper like in our clusters, or another lighter weight solution exists in [kube-image-bouncer](https://github.com/flavio/kube-image-bouncer/tree/master/rules)

Some references
https://discuss.kubernetes.io/t/restrict-cluster-or-namespace-to-only-use-a-specific-registry/11814
https://stackoverflow.com/questions/54463125/how-to-reject-docker-registries-in-kubernetes

**Comment by johnSchnake** [comment]
I'll have to take a look at those; thanks for the references. This is a common issue that is always hard to repro, hence the poor iteration times or incomplete solutions. If we could find a great way to repro then we could just add an automated run on the testgrid to ensure this works periodically. It would help keep people from introducing new tests that do this sort of thing.

**Comment by apoliakov2** [comment]
We are facing exactly the same issue in our k8s clusters. We have a gatekeeper based admission webhook which prevents downloading container images from public repos, so we provide a list of repos via `--e2e-repo-config`, but still even after updating to k8s 1.22 and using the e2e test image that includes the fix by @jcstryker it seems that some of the repos paths are not being overwritten. 

Here is our environment:

- Sonobuoy version:
```
Sonobuoy Version: v0.56.1
MinimumKubeVersion: 1.17.0
MaximumKubeVersion: 1.99.99
GitSHA: eedd1ecb188a49d4417bea96d1837f747647e7a4
GoVersion: go1.16.13
Platform: linux/amd64
API Version:  v1.22.10
```
- Kubernetes version:
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.10", GitCommit:"eae22ba6238096f5dec1ceb62766e97783f0ba2f", GitTreeState:"clean", BuildDate:"2022-05-24T12:56:35Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.10", GitCommit:"eae22ba6238096f5dec1ceb62766e97783f0ba2f", GitTreeState:"clean", BuildDate:"2022-05-24T12:50:52Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```
- The sonobuoy command that we use:
```
sonobuoy run --e2e-focus=FOCUS_TESTS_REGEX --e2e-skip=SKIPPED_TESTS_REGEX --plugin=e2e --sonobuoy-image {PRIVATE_REPO}/docker.io/sonobuoy/sonobuoy:v0.56.1 --kube-conformance-image {PRIVATE_REPO}/k8s.gcr.io/conformance:v1.22.10 --e2e-repo-config /tmp/custom_repo_config.yaml --systemd-logs-image {PRIVATE_REPO}/gcr.io/heptio-images/sonobuoy-plugin-systemd-logs:latest
```
- A mapping yaml file:
```
buildImageRegistry: {PRIVATE_REGISTRY}/k8s.gcr.io/build-image
dockerGluster: {PRIVATE_REGISTRY}/docker.io/gluster
dockerLibraryRegistry: {PRIVATE_REGISTRY}/docker.io/library
e2eRegistry: {PRIVATE_REGISTRY}/gcr.io/kubernetes-e2e-test-images
e2eVolumeRegistry: {PRIVATE_REGISTRY}/gcr.io/kubernetes-e2e-test-images/volume
gcRegistry: {PRIVATE_REGISTRY}/k8s.gcr.io
gcEtcdRegistry: {PRIVATE_REGISTRY}/k8s.gcr.io
promoterE2eRegistry: {PRIVATE_REGISTRY}/k8s.gcr.io/e2e-test-images
sigStorageRegistry: {PRIVATE_REGISTRY}/k8s.gcr.io/sig-storage
sampleRegistry: {PRIVATE_REGISTRY}/k8s.gcr.io/google-samples
invalidRegistry: {PRIVATE_REGISTRY}/k8s.gcr.io/invalid
```
I must note here that `sonobuoy gen default-image-config` produces a mapping without `sampleRegistry` nor with `invalidRegistry`, so I added them manually to the listm but that doesn't seem to help (not sure how important it is).
We are running our clusters in AWS.
Any help would be appreciated.
