### ISSUE TITLE
trying to process results on Windows fails

### ISSUE THREAD

**Issue by johnqa** [vmware-tanzu/sonobuoy#1229]
**What steps did you take and what happened:**
I am running sonobuoy from a Windows workstation (with Lens) and all is working fine.
I am getting a result file with `sonobuoy retrieve` but when I do `sonobuoy results` I get an error message:

```
sonobuoy results .\202104131725_sonobuoy_f084705d-9abd-4b19-826d-e5a6dac579fb.tar.gz --plugin e2e
time="2021-04-14T10:09:14+02:00" level=error msg="could not process archive: .\\202104131725_sonobuoy_f084705d-9abd-4b19-826d-e5a6dac579fb.tar.gz: failed to find file \"plugins/e2e/sonobuoy_results.yaml\" in archive"
```

If I copy the tarball on a linux workstation and use the same command it works.

**What did you expect to happen:**
I would expect for `sonobuoy results` to work on windows.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Sonobuoy version: v0.50.0 and v0.20.0
- Kubernetes version: (use `kubectl version`): v1.19.2
- Kubernetes installer & version: Rancher 2.5 / RKE
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`): RHEL 8

**Comment by vladimirvivien** [comment]
@johnqa there is no official support for running Sonobuoy binary on a Windows workstation. It's a feature we're still working ont.

**Comment by johnqa** [comment]
Great, if you are still working on it, you have now some extra feedback.

**Comment by johnSchnake** [comment]
I had, in the past, successfully ran on Windows. Just to make sure I understand:

- The node that the sonobuoy is on is Windows? Or Linux/Mac?
- Is your machine that you're running the CLI Windows?
- Did you untar the file and confirm the file was there as expected? If you can share the tarfile that would be ideal.

**Comment by johnqa** [comment]
Hi,

Indeed I have sonobuoy on a Windows machine and I run my cli on the same machine. Kubernetes nodes are RedHat.

I untared the file and it is where expected, moreover I have put the same tar.gz file in a Linux workstation with sonobuoy and it worked.

Could it be that sonobuoy depends on some archiving, untaring 3rd party apps that are not on Windows?

**Comment by johnSchnake** [comment]
I'll have to look into it, thanks a lot for the report. The CLI _should_ definitely work on windows, all the tar logic is in go and cross platform.  The main thing that _could_ happen is some path issues since the server is tar-ing up from a linux system and windows is untarring it so the path separators may be misunderstood but it should still be able to open it.

From the error message it makes a bit more sense now though; the newer sonobuoy results logic may not have been completely compatible with that case and it wasn't directly tested on windows since support there is limited.  Clear lead on the issue then though! 👍

**Comment by johnSchnake** [comment]
Now that we are all on github actions there are windows runners we can utilize easily. I'm continuing to work on windows related tasks and will get some sort of testing implemented so we can prevent this stuff from continuing to plague us.

xref #1254

**Comment by johnSchnake** [comment]
On the flipside this also has a problem when the agent node is windows and the client is mac/linux, though the error message is a bit different:

```
sonobuoy results ./windows.tar.gz
ERRO[0000] could not process archive: ./windows.tar.gz: no plugins specified by either the --plugin flag or tarball metadata
```

I created #1266 which shows some more of the pathing issues. All of these are related so once I fix one it will fix them all I think.
