### ISSUE TITLE
question: tests for cgroup2 resource limits

### ISSUE THREAD

**Issue by r10r** [vmware-tanzu/sonobuoy#1236]
Hi there,

we are currently developing https://github.com/lxc/lxcri an OCI compliant runtime wrapper for lxc.
I use sonobuoy to check the implementation and it does a great job here!

We're in progress of implementing the cgroup2 resource limits see https://github.com/lxc/lxcri/issues/33
I just want to ask whether there are any tests that actually check for cgroup2 resource limits?

Regards

**Comment by wilsonehusin** [comment]
🤔 i'm not sure if there is, but if you haven't already noticed, the default e2e plugin runs `k8s.gcr.io/conformance` image which is produced by Kubernetes open source project and [the source code for the tests can be found in `kubernetes/kubernetes` repository](https://github.com/kubernetes/kubernetes/tree/master/test/e2e).

if you're looking to develop specific tests for OCI, you can also [create your own custom plugins](https://sonobuoy.io/docs/v0.50.0/plugins/) 😄

**Comment by r10r** [comment]
>  the source code for the tests can be found in kubernetes/kubernetes repository.

Ok, I'll look through the tests in the kubernetes repository and see what I can find.

> if you're looking to develop specific tests for OCI, you can also create your own custom plugins 😄

Nice, I really want to do this - not just for OCI specific tests. 

I close this now and continue on https://github.com/lxc/lxcri/issues/33.
Thanks for your help!
