### ISSUE TITLE
[sig-network] Networking IPERF IPv4 [Performance] [TCP] e2e TC's are failed 

### ISSUE THREAD

**Issue by Raghavendrasp123** [vmware-tanzu/sonobuoy#1239]
Hi, 
We are observing test panic while running sonobuoy e2e test with focus CNI plugin "Calico".  Below is the snippet of logs  logs that we are seeing in our environment and full log is attached in the ticket. 

[sonobuoy_e2e_focus_calico.zip](https://github.com/vmware-tanzu/sonobuoy/files/6396368/sonobuoy_e2e_focus_calico.zip)
[sonobuoy_e2e_focus_calico.zip](https://github.com/vmware-tanzu/sonobuoy/files/6396369/sonobuoy_e2e_focus_calico.zip)

================
W0425 13:18:32.778882      19 metrics_grabber.go:105] Did not receive an external client interface. Grabbing metrics from ClusterAutoscaler is disabled.
Apr 25 13:18:32.807: INFO: 
Latency metrics for node worker-sbg-ui57bx3o-eknxbal-ibd-dev-cluster
Apr 25 13:18:32.807: INFO: Waiting up to 3m0s for all (but 0) nodes to be ready
STEP: Destroying namespace "tc-cal-sep-https-mimo-ipv4-nosvc-7880" for this suite.

•! Panic [49.536 seconds]
[sig-network] Networking SIEGE IPv4 [Performance] [HTTPS] [SeparateComputes] [MIMO] [Calico] [Feature:Networking-IPv4] [Slow] [TC_CAL_SEP_HTTPS_MIMO_IPV4_NOSVC]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/netperf/framework.go:23
   HTTPS Throughput between 2 servers and 8 clients without ClusterIP Service [It]
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/netperf/iperf.go:220

  Test Panicked
  runtime error: index out of range [1] with length 1
  /usr/local/go/src/runtime/panic.go:88

  Full Stack Trace
  k8s.io/kubernetes/test/e2e/network/netperf.validatePassCriteria(0x4e5d00c, 0x20, 0xc002fcc488, 0xc0032c3240)
  	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/netperf/pass_tc_criteria.go:101 +0x57da
  k8s.io/kubernetes/test/e2e/network/netperf.KPITest.func1()
  	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/netperf/iperf.go:380 +0x136a
  k8s.io/kubernetes/test/e2e.RunE2ETests(0xc003780900)
  	_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/e2e.go:130 +0x36c
  k8s.io/kubernetes/test/e2e.TestE2E(0xc003780900)
  	_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/e2e_test.go:145 +0x2b
  testing.tRunner(0xc003780900, 0x4fdaed8)
  	/usr/local/go/src/testing/testing.go:1123 +0xef
  created by testing.(*T).Run
  	/usr/local/go/src/testing/testing.go:1168 +0x2b3

**Comment by wilsonehusin** [comment]
- Have you validated that your CNI installation is correct? Sonobuoy helps you run these tests so that any failures can be surfaced. It's possible that your cluster setup isn't complete.
- Sonobuoy runs tests published by Kubernetes open source project, [the source of those tests can be found in `kubernetes/kubernetes` repository](https://github.com/kubernetes/kubernetes/tree/master/test/e2e). I encourage you to start looking at what the test is doing to troubleshoot your situation.

**Comment by Raghavendrasp123** [comment]
We have verified our setup, it is all good. It would be great if you help us to resolve this issue asap. Here I am attaching our complete logs of recent run for you reference. 
[sonobuoy-results.zip](https://github.com/vmware-tanzu/sonobuoy/files/6410187/sonobuoy-results.zip)


Apr 30 18:09:18.076: INFO: 
Latency metrics for node worker-sbg-hbnd1upp-ccdcluster-raghu
Apr 30 18:09:18.076: INFO: Waiting up to 3m0s for all (but 0) nodes to be ready
STEP: Destroying namespace "tc-cal-col-https-mimo-ipv4-svc-836" for this suite.

**•! Panic [194.352 seconds]
[sig-network] Networking SIEGE IPv4 [Performance] [HTTPS] [Colocation] [MIMO] [Calico] [Feature:Networking-IPv4] [Slow] [TC_CAL_COL_HTTPS_MIMO_IPV4_SVC]
**/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/netperf/framework.go:23
   HTTPS Throughput between 2 servers and 4 clients with ClusterIP Service [It]
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/netperf/iperf.go:220****

  Test Panicked
  runtime error: index out of range [1] with length 1
  /usr/local/go/src/runtime/panic.go:88
  Full Stack Trace
  k8s.io/kubernetes/test/e2e/network/netperf.validatePassCriteria(0x4e4edc7, 0x1e, 0xc0031722a8, 0xc003761020)
  	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/netperf/pass_tc_criteria.go:101 +0x57da
  k8s.io/kubernetes/test/e2e/network/netperf.KPITest.func1()
  	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/netperf/iperf.go:380 +0x136a
  k8s.io/kubernetes/test/e2e.RunE2ETests(0xc001bd3980)
  	_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/e2e.go:130 +0x36c
  k8s.io/kubernetes/test/e2e.TestE2E(0xc001bd3980)
  	_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/e2e_test.go:145 +0x2b
  testing.tRunner(0xc001bd3980, 0x4fdaed8)
  	/usr/local/go/src/testing/testing.go:1123 +0xef
  created by testing.(*T).Run
  	/usr/local/go/src/testing/testing.go:1168 +0x2b3

**Comment by johnSchnake** [comment]
As @wilsonehusin said, these tests are published by the upstream k8s community and not under our ownership. There isn't any particular experitise that we can bring to bear as we are not familiar with your setup, the specific tests in question, or (speaking for myself) IPERF IPv4 in general.

Try reaching out to the sig-networking channel on slack and see if someone there can help.

Good luck 👍
