### ISSUE TITLE
Conformance test failed - Timeout waiting for results

### ISSUE THREAD

**Issue by fabianKingKong** [vmware-tanzu/sonobuoy#1249]
**What steps did you take and what happened:**
I run the sonobuoy test with the following Command: `sonobuoy run --mode=certified-conformance` The plugin e2e gives me the following error:

`sonobuoy results 202105070816_sonobuoy_92844fe9-562e-4c83-b2fc-4a0b48999989.tar.gz`

Plugin: e2e
Status: failed
Total: 1
Passed: 0
Failed: 1
Skipped: 0
Failed tests:
timeout waiting for results

`sonobuoy results 202105070816_sonobuoy_92844fe9-562e-4c83-b2fc-4a0b48999989.tar.gz e2e --mode dump`
name: e2e
status: failed
meta:
  type: summary
items:
 name: timeout waiting for results
  status: timeout
  meta:
    file: errors/global/error.json
  details:
    error: timeout waiting for results

**What did you expect to happen:**

Successfull conformance Test like the systemd-logs plugin which is passed

**Anything else you would like to add:**
The test is passed with kubernetes 1.18.6 and docker as ContainerRuntime. This test is now with crio.

**Environment:**

- Sonobuoy version: sonobuoy_0.50.0_linux_amd64.tar.gz
- Kubernetes version: (use `kubectl version`):
`kubectl version`
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:03:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}

- Kubernetes installer & version: kubernets `1.20.4`

- Cloud provider or hardware configuration: 1x Clustermaster(node), 2x worker(nodes))
- OS (e.g. from `/etc/os-release`): 
`cat /etc/os-release`
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

- Sonobuoy tarball (which contains * below)
[202105070816_sonobuoy_92844fe9-562e-4c83-b2fc-4a0b48999989.tar.gz](https://github.com/vmware-tanzu/sonobuoy/files/6441849/202105070816_sonobuoy_92844fe9-562e-4c83-b2fc-4a0b48999989.tar.gz)

**Comment by johnSchnake** [comment]
You'll need to debug this as it is running to see why it enters this state. 

Looking at the namespace objects, I can see the sonobuoy worker is in a crash backoff loop:

```
"state": {
            "waiting": {
              "message": "back-off 5m0s restarting failed container=sonobuoy-worker pod=sonobuoy-systemd-logs-daemon-set-1e2dc2bf43c9461a-bx2ks_sonobuoy(219cc4d3-c050-48b5-9533-54a8066f08de)",
              "reason": "CrashLoopBackOff"
            }
          }
```

You also have a ton of these messages in run.log:

```
{"client_cert":"e2e","level":"info","msg":"received aggregator request","plugin_name":"e2e","time":"2021-05-07T11:08:25Z"}
```

So the worker was trying to send info back and repeatedly; I'm guessing it kept crashing asap and reporting an error or something. 

I am not familiar with crio and common error modes, but if you launch it, watch it fail in real time and watch the logs/status of the e2e pod(s) I bet it will become pretty clear.

Good luck.

**Comment by fabianKingKong** [comment]
Hello,
i restarted the test and i still dont unterstand where the error comes from. I attached you beside the .tar the logs of the e2e pod on the worker.

[202105110853_sonobuoy_3d3231aa-4e84-4119-a7ff-f352690d8a95.tar.gz](https://github.com/vmware-tanzu/sonobuoy/files/6493706/202105110853_sonobuoy_3d3231aa-4e84-4119-a7ff-f352690d8a95.tar.gz)
[worker_e2e_pod-logs.txt](https://github.com/vmware-tanzu/sonobuoy/files/6493707/worker_e2e_pod-logs.txt)

**Comment by fabianKingKong** [comment]
> Hello,
> i restarted the test and i still dont unterstand where the error comes from. I attached you beside the .tar the logs of the e2e pod on the worker.
> 
> [202105110853_sonobuoy_3d3231aa-4e84-4119-a7ff-f352690d8a95.tar.gz](https://github.com/vmware-tanzu/sonobuoy/files/6493706/202105110853_sonobuoy_3d3231aa-4e84-4119-a7ff-f352690d8a95.tar.gz)
> [worker_e2e_pod-logs.txt](https://github.com/vmware-tanzu/sonobuoy/files/6493707/worker_e2e_pod-logs.txt)

**Comment by fabianKingKong** [comment]
Hello,
 i restarted the test and i still dont unterstand where the error comes from. I attached you beside the .tar the logs of the e2e pod on the worker.
 [202105110853_sonobuoy_3d3231aa-4e84-4119-a7ff-f352690d8a95.tar.gz](https://github.com/vmware-tanzu/sonobuoy/files/6493706/202105110853_sonobuoy_3d3231aa-4e84-4119-a7ff-f352690d8a95.tar.gz)
 [worker_e2e_pod-logs.txt](https://github.com/vmware-tanzu/sonobuoy/files/6493707/worker_e2e_pod-logs.txt)
