### ISSUE TITLE
Sonobuoy gen default-image-config command don't consider "gcr.io/k8s-staging-csi" library thus  can't be changed to local registry

### ISSUE THREAD

**Issue by rajeshsingh624** [vmware-tanzu/sonobuoy#1264]
**What steps did you take and what happened:**
Sonobuoy gen default-image-config command don't consider "gcr.io/k8s-staging-csi" library thus  images can't be changed to local registry for airgap testing

Environment setup - airgap
Since, the Sonobuoy gen command didn't output the gcr.io/k8s-staging-csi, thus the related images were not pulled and moved to local registry.
```
[root@bootstrap sonobuoy]# sonobuoy gen default-image-config
buildImageRegistry: k8s.gcr.io/build-image
dockerGluster: docker.io/gluster
dockerLibraryRegistry: docker.io/library
e2eRegistry: gcr.io/kubernetes-e2e-test-images
e2eVolumeRegistry: gcr.io/kubernetes-e2e-test-images/volume
gcRegistry: k8s.gcr.io
promoterE2eRegistry: k8s.gcr.io/e2e-test-images
sigStorageRegistry: k8s.gcr.io/sig-storage
```

While running sonobuoy tests with --focus = [sig-storage], all the tests with tag [Driver: csi-hostpath], failed to execute as the relevant images are not getting pulled.

```
[root@ sonobuoy]# k get po -A | grep ImagePullBackOff  -i
csi-mock-volumes-9541    csi-mockplugin-0                                         0/3     ImagePullBackOff   0          2d15h
csi-mock-volumes-9541    csi-mockplugin-attacher-0                                0/1     ImagePullBackOff   0          2d15h
```
error:
```
May 14 09:59:23.324: INFO: At 2021-05-14 09:54:15 +0000 UTC - event for csi-hostpath-attacher-0: {kubelet plpd-pcn12-md-hc-0-5c58f9cddc-2x695} Failed: Failed to pull image "gcr.io/k8s-staging-csi/csi-attacher:v2.2.0": rpc error: code = Unknown desc = failed to pull and unpack image "gcr.io/k8s-staging-csi/csi-attacher:v2.2.0": failed to resolve reference "gcr.io/k8s-staging-csi/csi-attacher:v2.2.0": failed to do request: Head https://gcr.io/v2/k8s-staging-csi/csi-attacher/manifests/v2.2.0: dial tcp: lookup gcr.io on 127.0.0.53:53: read udp 127.0.0.1:59065->127.0.0.53:53: i/o timeout
```
```
May 14 09:59:23.324: INFO: At 2021-05-14 09:54:25 +0000 UTC - event for csi-hostpath-provisioner-0: {kubelet plpd-pcn12-md-hc-0-5c58f9cddc-2x695} Failed: Faile
d to pull image "gcr.io/k8s-staging-csi/csi-provisioner:v1.6.0": rpc error: code = Unknown desc = failed to pull and unpack image "gcr.io/k8s-staging-csi/csi-p
rovisioner:v1.6.0": failed to resolve reference "gcr.io/k8s-staging-csi/csi-provisioner:v1.6.0": failed to do request: Head https://gcr.io/v2/k8s-staging-csi/c
si-provisioner/manifests/v1.6.0: dial tcp: lookup gcr.io on 127.0.0.53:53: read udp 127.0.0.1:56735->127.0.0.53:53: i/o timeout
May 14 09:59:23.324: INFO: At 2021-05-14 09:54:26 +0000 UTC - event for csi-hostpath-provisioner-0: {kubelet plpd-pcn12-md-hc-0-5c58f9cddc-2x695} BackOff: Back
-off pulling image "gcr.io/k8s-staging-csi/csi-provisioner:v1.6.0"
```

**What did you expect to happen:**
There is no option for specifying the k8s-staging-csi in the custom-image-config, thus all images from it's library wasn't pulled to local registry.
Also, seems the test code is hardcoded to pull images,  from "gcr.io/k8s-staging-csi", thus this won't be able to pull from private registry.
Impact : it's impacting 100+ test.

**Environment:**
- Sonobuoy version:v0.20.0
- Kubernetes version: (use `kubectl version`):v1.18.6

**Comment by johnSchnake** [comment]
You're right on the nose; the tests hard-code the image/repo which they aren't supposed to do. You can see that that image (csi-attacher) isn't even defined as a test image here: https://github.com/kubernetes/kubernetes/blob/master/test/utils/image/manifest.go

Instead, even when using yaml files they should templatize them to some extent and pull the image in at runtime so that it can be overridden.

I'll create a ticket for this upstream. I don't know when I'll be able to get to it, if you feel up to it then tackling it would be appreciated.

**Comment by pohly** [comment]
Which version of the Kubernetes e2e.test suite is being used here?

`gcr.io/k8s-staging-csi` is not a registry that should ever be used in a released version. Kubernetes 1.20.0 and 1.21.0 don't use it. We may have had to use it temporarily while preparing a release, so perhaps that's how it got into Sonobuoy v0.20.0.

The correct registry is `k8s.gcr.io/sig-storage` and that one is handled by `test/utils/image/manifest.go`.

**Comment by johnSchnake** [comment]
v1.18.6 is what they initially reported their cluster as; which should match the e2e.test version.

@rajeshsingh624 if you could provide the results tarball that would be even more helpful in case we have small followup questions.

**Comment by pohly** [comment]
The e2e.test from v1.18.6 also didn't use gcr.io/k8s-staging-sig-storage.

**Comment by mkrupczakVMware** [comment]
> You're right on the nose; the tests hard-code the image/repo which they aren't supposed to do. You can see that that image (csi-attacher) isn't even defined as a test image here: https://github.com/kubernetes/kubernetes/blob/master/test/utils/image/manifest.go
> 
> Instead, even when using yaml files they should templatize them to some extent and pull the image in at runtime so that it can be overridden.
> 
> I'll create a ticket for this upstream. I don't know when I'll be able to get to it, if you feel up to it then tackling it would be appreciated.

Encountering this right now with a team I'm on, it appears that the image registry is hard-coded and we're unable to get around rate limiting. Will likely create an issue for this specifically

**Comment by mkrupczakVMware** [comment]
Tried using some YAML key:values from [this file](https://github.com/vmware-tanzu/sonobuoy/blob/master/site/content/docs/v0.14.0/airgap.md) to get it to work as expected, but it doesn't look like that worked either

**Comment by johnSchnake** [comment]
Can you provide the results tarball so we can check some of the output?

**Comment by mkrupczakVMware** [comment]
Sure, we should be able to upload a tar  of some of the command we ran and their output before EOD today. We're on the channel #mapbu-platform-services-bootcamp on the VMware Slack

**Comment by mkrupczak3** [comment]
Ok, so it looks like we may have had a confusion when following the instructions on [this heading of the readme.md](https://github.com/vmware-tanzu/sonobuoy#sonobuoy-pod).

When it asked for `sonobuoy run --sonobuoy-image projects.registry.vmware.com/sonobuoy/sonobuoy:<VERSION>` we thought our tag needed to be something like `amd64` or `amd64-master` (for the machine architecture) , but those didn't work.

The only image that actually worked was `sonobuoy:v0.51.0`, which I think is what we got when using the default `latest` tag when we tried to deploy to another cluster

**Comment by mkrupczak3** [comment]
I will submit a pull request to update the `readme.md` to add a line just to clarify that `<VERSION>` likely means a specific release number used as a Docker tag

**Comment by mkrupczak3** [comment]
We also encountered a similar issue with what has been described recently with certain image locations being hard-coded and un-modifiable. The one we were wrestling with just recently was for the DaemonSets, but I'm sure other elements are likewise hard-coded despite all the possible flags we passed the command. Thus we were blocked by Docker's rate limiting

**Comment by johnSchnake** [comment]
Anytime you feel like an image is hardcoded, be sure to submit an issue to sonobuoy and/or upstream (tag me in it if you do). Occasionally those slip in but we always get those patched to be configurable (at the registry level).

**Comment by mkrupczakVMware** [comment]
Hi John,

Thanks for taking a look at this. We were trying to deploy sonobouy manually earlier, but were running into some issues due the aforementioned hard coded for certain image(s).

We found for our specific use scenario, we were better off just using Tanzu Mission Control's automated deployment and interactions with Sonobouy. 

This allowed us to work around the issue for our specific use case, it's unclear however what effect these might have on others with different use cases. 

Again thanks for the help, really appreciate being able to get a dev on the line. We're happy to provide more feedback from the deployment side of things as such opportunities arrive

**Comment by johnSchnake** [comment]
Absolutely Matthew, happy to help however I can. Please let us know any issues you encounter so we can try and head them off for other users. Sounds like I can close this? Reopen if there is something else I can do to help.
