### ISSUE TITLE
E2E tests failing due to unschedulable nodes

### ISSUE THREAD

**Issue by AndrewPToi** [vmware-tanzu/sonobuoy#1273]
**What steps did you take and what happened:**
I have the same problem as bug #1091 but when I attempt to use the solution, the e2e pod still reports those nodes as unschedulable and loops until the timeout.

**What did you expect to happen:**
I expected the --non-blocking-taints passed via the e2e args to make the e2e pod ignore the nodes with those taints.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Sonobuoy version: 0.50.0
- Kubernetes version: (use `kubectl version`): 1.18.16
- Kubernetes installer & version:
- Cloud provider or hardware configuration: AWS EC2 instances
- OS (e.g. from `/etc/os-release`): 
- Sonobuoy tarball (which contains * below) sonobuoy_0.50.0_darwin_amd64.tar.gz

**Comment by johnSchnake** [comment]
Can you attach the logs from the run so I can help you diagnose the issue?

The test starup logic is very finicky and I wouldn't be surprised if there were a legitimate bug  in some part of it. It can also be easily misconfigured. The logs from sonobuoy will help us see 1) what you ran 2) what the nodes were tainted as 3) the logs from the run and hopefully which nodes were giving it the problem.

**Comment by AndrewPToi** [comment]
Thank you - we tried a couple of ways, here are a couple of runs (ec2 ip address host names removed to protect the innocent/comply with security disclosure requirements):

kubectl logs sonobuoy-e2e-job-834000a6ba2d4138 e2e -n sonobuoy
+ /gorunner
sep is " " args are "“--non-blocking-taints=kaim-server,stable”"split [“--non-blocking-taints=kaim-server,stable”]
2021/05/14 18:01:06 Running command:
Command env: []
Run from directory: 
Executable path: /usr/local/bin/ginkgo
Args (comma-delimited): /usr/local/bin/ginkgo,--focus=Pods should be submitted and removed,--skip=,--noColor=true,/usr/local/bin/e2e.test,--,--disable-log-dump,--repo-root=/kubernetes,--provider=local,--report-dir=/tmp/results,--kubeconfig=,“--non-blocking-taints=kaim-server,stable”
2021/05/14 18:01:06 Now listening for interrupts
I0514 18:01:07.591413      25 test_context.go:410] Using a temporary kubeconfig file from in-cluster config : /tmp/kubeconfig-464088907
I0514 18:01:07.591428      25 test_context.go:423] Tolerating taints "node-role.kubernetes.io/master" when considering if nodes are ready
I0514 18:01:07.591506      25 e2e.go:124] Starting e2e run "04ceced8-2609-4f86-802a-4c7253b4cca5" on Ginkgo node 1
{"msg":"Test Suite starting","total":1,"completed":0,"skipped":0,"failed":0}
Running Suite: Kubernetes e2e suite
===================================
Random Seed: 1621015266 - Will randomize all specs
Will run 1 of 4994 specs

May 14 18:01:07.602: INFO: >>> kubeConfig: /tmp/kubeconfig-464088907
May 14 18:01:07.604: INFO: Waiting up to 30m0s for all (but 0) nodes to be schedulable
May 14 18:01:07.638: INFO: Unschedulable nodes:
May 14 18:01:07.638: INFO: -> ec2.internal Ready=true Network=false Taints=[{dedicated stable NoSchedule <nil>}] NonblockingTaints:node-role.kubernetes.io/master
May 14 18:01:07.638: INFO: -> ec2.internal Ready=true Network=false Taints=[{dedicated monitoring NoSchedule <nil>}] NonblockingTaints:node-role.kubernetes.io/master
May 14 18:01:07.638: INFO: -> ec2.internal Ready=true Network=false Taints=[{dedicated monitoring NoSchedule <nil>}] NonblockingTaints:node-role.kubernetes.io/master
May 14 18:01:07.638: INFO: -> ec2.internal Ready=true Network=false Taints=[{dedicated kiam-server NoSchedule <nil>}] NonblockingTaints:node-role.kubernetes.io/master
May 14 18:01:07.638: INFO: -> ec2.internal Ready=true Network=false Taints=[{dedicated kiam-server NoSchedule <nil>}] NonblockingTaints:node-role.kubernetes.io/master
May 14 18:01:07.638: INFO: -> ec2.internal Ready=true Network=false Taints=[{dedicated stable NoSchedule <nil>}] NonblockingTaints:node-role.kubernetes.io/master
May 14 18:01:07.638: INFO: -> ec2.internal Ready=true Network=false Taints=[{dedicated monitoring NoSchedule <nil>}] NonblockingTaints:node-role.kubernetes.io/master
May 14 18:01:07.638: INFO: -> ec2.internal Ready=true Network=false Taints=[{dedicated stable NoSchedule <nil>}] NonblockingTaints:node-role.kubernetes.io/master
May 14 18:01:07.638: INFO: -> ec2.internal Ready=true Network=false Taints=[{dedicated kiam-server NoSchedule <nil>}] NonblockingTaints:node-role.kubernetes.io/master


Run 2: trying to isolate the taint list to see if we could get at least one to go:

kubectl logs sonobuoy-e2e-job-4045ceb3efa04cef e2e -n sonobuoy
+ /gorunner
sep is " " args are "“--non-blocking-taints=dedicated monitoring NoSchedule”"split [“--non-blocking-taints=dedicated monitoring NoSchedule”]
2021/05/14 18:22:31 Running command:
Command env: []
Run from directory: 
Executable path: /usr/local/bin/ginkgo
Args (comma-delimited): /usr/local/bin/ginkgo,--focus=Pods should be submitted and removed,--skip=,--noColor=true,/usr/local/bin/e2e.test,--,--disable-log-dump,--repo-root=/kubernetes,--provider=local,--report-dir=/tmp/results,--kubeconfig=,“--non-blocking-taints=dedicated,monitoring,NoSchedule”
2021/05/14 18:22:31 Now listening for interrupts
I0514 18:22:31.937800      24 test_context.go:410] Using a temporary kubeconfig file from in-cluster config : /tmp/kubeconfig-104645444
I0514 18:22:31.937818      24 test_context.go:423] Tolerating taints "node-role.kubernetes.io/master" when considering if nodes are ready
I0514 18:22:31.937895      24 e2e.go:124] Starting e2e run "f651bda6-7207-4ee8-aa88-ce6f4fc4811d" on Ginkgo node 1
{"msg":"Test Suite starting","total":1,"completed":0,"skipped":0,"failed":0}
Running Suite: Kubernetes e2e suite
===================================
Random Seed: 1621016551 - Will randomize all specs
Will run 1 of 4994 specs

May 14 18:22:31.949: INFO: >>> kubeConfig: /tmp/kubeconfig-104645444
May 14 18:22:31.951: INFO: Waiting up to 30m0s for all (but 0) nodes to be schedulable
May 14 18:22:31.981: INFO: Unschedulable nodes:
May 14 18:22:31.981: INFO: -> ec2.internal Ready=true Network=false Taints=[{dedicated monitoring NoSchedule <nil>}] NonblockingTaints:node-role.kubernetes.io/master
May 14 18:22:31.981: INFO: -> ec2.internal Ready=true Network=false Taints=[{dedicated monitoring NoSchedule <nil>}] NonblockingTaints:node-role.kubernetes.io/master
May 14 18:22:31.981: INFO: -> ec2.internal Ready=true Network=false Taints=[{dedicated kiam-server NoSchedule <nil>}] NonblockingTaints:node-role.kubernetes.io/master
May 14 18:22:31.981: INFO: -> ec2.internal Ready=true Network=false Taints=[{dedicated kiam-server NoSchedule <nil>}] NonblockingTaints:node-role.kubernetes.io/master
May 14 18:22:31.981: INFO: -> ec2.internal Ready=true Network=false Taints=[{dedicated stable NoSchedule <nil>}] NonblockingTaints:node-role.kubernetes.io/master
May 14 18:22:31.981: INFO: -> ec2.internal Ready=true Network=false Taints=[{dedicated monitoring NoSchedule <nil>}] NonblockingTaints:node-role.kubernetes.io/master
May 14 18:22:31.981: INFO: -> ec2.internal Ready=true Network=false Taints=[{dedicated kiam-server NoSchedule <nil>}] NonblockingTaints:node-role.kubernetes.io/master
May 14 18:22:31.981: INFO: -> ec2.internal Ready=true Network=false Taints=[{dedicated stable NoSchedule <nil>}] NonblockingTaints:node-role.kubernetes.io/master
May 14 18:22:31.981: INFO: -> ec2.internal Ready=true Network=false Taints=[{dedicated stable NoSchedule <nil>}] NonblockingTaints:node-role.kubernetes.io/master

**Comment by johnSchnake** [comment]
Something does seem off with the quoting/etc of the non-blocking taints.

In the logs you can see it just lists the master taint as the only non-blocking taint despite you trying to do it above.
> Tolerating taints "node-role.kubernetes.io/master" when considering if nodes are ready

It is unintuitive how to write the line since we're via the sonobuoy CLI we're telling the plugin to set an environment variable which changes the CLI values for ginkgo.

However, a tiny example I just ran on my own kind cluster:
> Tolerating taints "foo,bar" when considering if nodes are ready

To get that I provided:
`sonobuoy run --plugin-env=e2e.E2E_EXTRA_ARGS=--non-blocking-taints=foo,bar`

**Comment by johnSchnake** [comment]
You need to make the list of taints a comma-separated list:

`... --plugin-env=e2e.E2E_EXTRA_ARGS=--non-blocking-taints=dedicated,stable,NoSchedule`

Thats the way it looks in your logs; that they are separate taints. As you wrote it (`dedicated=stable:NoSchedule`) it thinks that is one value (since there are no commas).

That should fix you up; going to close but reopen if this doesn't resolve the issue.

**Comment by AndrewPToi** [comment]
that did it!  thanks much!
