### ISSUE TITLE
E2E test failed on some nodes

### ISSUE THREAD

**Issue by jwz-ecust** [vmware-tanzu/sonobuoy#1282]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

I am working on an x86 platform. Something wrong happened on the docker command on four nodes. I want sonobuoy not to avoid the above nodes. I tried two methods: set taints on those nodes and cordon these nodes. 

**What did you expect to happen:**
I expect that sonobuoy could avoid those undesirable nodes. However, both two methods failed. I wonder whether there are any commands to select testing nodes.

**Environment:**
- Sonobuoy version: 
- Kubernetes version: v0.50.0
- Kubernetes installer & version: 1.20
- OS:   x86_64 x86_64 x86_64 GNU/Linux

**Comment by johnSchnake** [comment]
> I want sonobuoy not to avoid the above nodes

You mean you want sonobuoy to avoid them?

And what do you mean that you want Sonobuoy to avoid them? You mean you want the e2e tests to avoid them? Or you want the sonobuoy aggregator (the sonobuoy pod itself) to avoid them?

If you can clarify those questions and potentially send me any relevant logs that would be helpful for me to understand/recommend a course of action. There isn't a way to tell the e2e tests which nodes to test, you do have to just taint the undesireable nodes but then you also have to add another flag to tell the e2e tests to startup even though some nodes are unschedulable. See https://github.com/vmware-tanzu/sonobuoy/issues/1273 for an example.

**Comment by johnSchnake** [comment]
Also, just to add to this, there is a flag to specify where to place the aggregator:
```
      --aggregator-node-selector nodeSelectors   Node selectors to add to the aggregator. Values can be given multiple times and are in the form key:value (default map[])
```

**Comment by johnSchnake** [comment]
Closing due to age.
