### ISSUE TITLE
Image url problem

### ISSUE THREAD

**Issue by jwz-ecust** [vmware-tanzu/sonobuoy#1283]
**What steps did you take and what happened:**
For my testing environment, it could not access the k8s.gcr.io URL.  So, I manually pull these images and push to my testing environment. I found some image URLs are unreachable.

**What did you expect to happen:**
here is the image list:
docker.io/gluster/glusterdynamic-provisioner:v1.0
docker.io/library/busybox:1.29
docker.io/library/httpd:2.4.38-alpine
docker.io/library/httpd:2.4.39-alpine
docker.io/library/nginx:1.14-alpine
docker.io/library/nginx:1.15-alpine
docker.io/library/perl:5.26
docker.io/library/redis:5.0.5-alpine
gcr.io/authenticated-image-pulling/alpine:3.7
gcr.io/k8s-authenticated-test/agnhost:2.6
gcr.io/kubernetes-e2e-test-images/apparmor-loader:1.0
gcr.io/kubernetes-e2e-test-images/cuda-vector-add:1.0
gcr.io/kubernetes-e2e-test-images/cuda-vector-add:2.0
gcr.io/kubernetes-e2e-test-images/echoserver:2.2
gcr.io/kubernetes-e2e-test-images/ipc-utils:1.0
gcr.io/kubernetes-e2e-test-images/jessie-dnsutils:1.0
gcr.io/kubernetes-e2e-test-images/kitten:1.0
gcr.io/kubernetes-e2e-test-images/metadata-concealment:1.2
gcr.io/kubernetes-e2e-test-images/nautilus:1.0
gcr.io/kubernetes-e2e-test-images/nonewprivs:1.0
gcr.io/kubernetes-e2e-test-images/nonroot:1.0
gcr.io/kubernetes-e2e-test-images/regression-issue-74839-amd64:1.0
gcr.io/kubernetes-e2e-test-images/resource-consumer:1.5
gcr.io/kubernetes-e2e-test-images/sample-apiserver:1.17
gcr.io/kubernetes-e2e-test-images/volume/gluster:1.0
gcr.io/kubernetes-e2e-test-images/volume/iscsi:2.0
gcr.io/kubernetes-e2e-test-images/volume/nfs:1.0
gcr.io/kubernetes-e2e-test-images/volume/rbd:1.0.1
invalid.com/invalid/alpine:3.1
k8s.gcr.io/build-image/debian-iptables:buster-v1.3.0
k8s.gcr.io/conformance:v1.20.1
k8s.gcr.io/e2e-test-images/agnhost:2.21
k8s.gcr.io/etcd:3.4.13-0
k8s.gcr.io/pause:3.2
k8s.gcr.io/prometheus-dummy-exporter:v0.1.0
k8s.gcr.io/prometheus-to-sd:v0.5.0
k8s.gcr.io/sd-dummy-exporter:v0.2.0
k8s.gcr.io/sig-storage/nfs-provisioner:v2.2.2
sonobuoy/sonobuoy:v0.50.0
sonobuoy/systemd-logs:v0.3

I found serveral image URLs not exist:
invalid.com/invalid/alpine:3.1

gcr.io/authenticated-image-pulling/alpine:3.7
gcr.io/authenticated-image-pulling/windows-nanoserver:v1
gcr.io/k8s-authenticated-test/agnhost:2.6

**Environment:**

- Sonobuoy version: v0.50.0
- Kubernetes version: 1.20

**Comment by johnSchnake** [comment]
So the tests upstream work so I don't think those are missing; its just that those are authenticated registries and fail to pull without auth.

The auth info is here: https://github.com/kubernetes/kubernetes/blob/master/test/e2e/common/node/runtime.go#L290-L297 

It does raise the question how to automatically pull those images if we also don't want to be extremely tied to variations in the upstream code. I don't think there is a great choice there besides hardcoding those into Sonobuoy. @wilsonehusin Do you have an idea?

**Comment by wilsonehusin** [comment]
> It does raise the question how to automatically pull those images if we also don't want to be extremely tied to variations in the upstream code.

I think you're quite spot on there. One thing I can think of is to modify the output from conformance image such that they are more than list of strings. Something like:

```yaml
public:
-  k8s.gcr.io/etcd:3.4.13-0

...

private:
- gcr.io/authenticated-image-pulling/alpine:3.7
```

which almost raises the question: should we just obscure those images in the first place, such that conformance pretends like those images aren't used? for example:
- `invalid.com/invalid/alpine:3.1` is never going to resolve ever (or at least that's the desired state).
- `gcr.io/authenticated-image-pulling/alpine:3.7` [used by a test that may not work in airgap](https://github.com/kubernetes/kubernetes/blob/ec1228f6525ae23ca6995d6c6a268ec22b041df4/test/e2e_node/runtime_conformance_test.go#L35).
- `gcr.io/k8s-authenticated-test/agnhost:2.6` doesn't seem to be used anymore based on a quick search.

**Comment by johnSchnake** [comment]
Thats a good point about the 2nd one you listed; I even linked to that code as an example but didnt stop to realize that if you move the file it still wont work since the auth info is completely hardcoded.

We could do something to obscure those (the invalid one especially) but another question would be whether or not all conformance tests should be able to pass in an airgap setting. I dont think that is considered explicit even though the whole image list/manifest exists to facilitate it.

We could easily add a field on the manifest items which would help list/not list the image name based on the flag info. Cobra even allows flags like this where `//no flag -> dont list images`, `--show-images. -> show all public images`, `--show-images=all   --> even show the private images if the users needed them for some processing` or something like that
