### ISSUE TITLE
Plugin caching/management

### ISSUE THREAD

**Issue by johnSchnake** [vmware-tanzu/sonobuoy#1292]
**Describe the solution you'd like**
It would be good to improve the way sonobuoy handles multiple plugins.

Currently users can run plugins from a file or URL which is great, but its not as if they are going to keep a list of URLs for the plugins they want. They can download them but if it is just a matter of downloading, storing, and updating them then sonobuoy should be able to do that.

We've talked about something like adding a `.sonobuoy` folder where users can do things like:

```
// download a plugin from a url
sonobuoy plugin get <url>

// run a plugin you have locally; its it .sonobuoy and not having to point to a file directly now
sonobuoy run -p foo

...
// list plugins we have locally
sonobuoy plugins list
```

Need a DD about this to flush out edge cases about updates or filenames/plugin names.

**Anything else you would like to add:**
Unsure if it would be possible or desireable to move the e2e plugin itself out of sonobuoy and support it this way too. Benefits would be:

 - could have a few preconfigured plugins instead of the `--mode` flag
 - ideally we get away from the static/dynamic plugin code. That is a mess and very confusing but was necessary to maintain historical functionality for all the flags
 - may get away from some extra flags; again that just makes the code easier to maintain and consistent between all the plugins

**Comment by vladimirvivien** [comment]
Awesome start of a real plugin management feature in Sonobuoy @johnSchnake

**Comment by johnSchnake** [comment]
Actively working on https://docs.google.com/document/d/1RzwYwI43TBFyHBxZ4mKDtfTAq6wJgXsfW7sFCHJjXxw/edit?usp=sharing . Anyone, feel free to comment.
