### ISSUE TITLE
Mac "identified developer" issue

### ISSUE THREAD

**Issue by johnSchnake** [vmware-tanzu/sonobuoy#1294]
On a mac, I get a security warning because it says Sonobuoy wasn't provided by an identified developer. Can we resolve that easily?

**Comment by johnSchnake** [comment]
https://discussions.apple.com/thread/7488189

$99/yr to get a cert from Apple and then we'd modify our process to sign that as well.

As opposed to just having folks allow sonobuoy manually. For now I vote for the latter, but if lots of folks complain then I guess we can revisit this. Going to leave this open for visibility but may close in a few months if nothing changes.

**Comment by vladimirvivien** [comment]
@johnSchnake let's check internally to see how this is done with other OSS projects. VMw may already have a solution.
