### ISSUE TITLE
certified-conformance test stuck with no results

### ISSUE THREAD

**Issue by Wenshiqi222** [vmware-tanzu/sonobuoy#1314]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
i jutst tested my k8s cluster with sonobuoy as for certified-conformance , as the test continued,i keep watchting the  sonobuoy logs, until i found the logs show:
```
[root@master1 wenshiqi]# sonobuoy logs
namespace="sonobuoy" pod="sonobuoy-systemd-logs-daemon-set-1b649f0da14446c0-swhcf" container="systemd-logs"
unable to retrieve container logs for docker://5c976989736df770a8b7db4e0affb32e0d0f7ba88aa27c431432e3316ee9c668namespace="sonobuoy" pod="sonobuoy-systemd-logs-daemon-set-1b649f0da14446c0-swhcf" container="sonobuoy-worker"
unable to retrieve container logs for docker://8419e7451a5bfaa5a1eb3965726a5e79eaf4628bec00d960ea613f130daa9ae3
```
and sonobuoy status didn't show if  the e2e plugin or systemd-log plugin pass or not,it only show me a few message like below,so that i donot konw if the testing is completed :
```
[root@master1 wenshiqi]# sonobuoy status
WARN[0000] no pods found with label "sonobuoy-component=aggregator" in namespace sonobuoy 
WARN[0000] retrying with deprecated label "run=sonobuoy-master" 
WARN[0000] no pods found with label "run=sonobuoy-master" in namespace sonobuoy 
WARN[0000] Aggregator pod not found, using default pod name "sonobuoy": no pods found with label "run=sonobuoy-master" in namespace sonobuoy 
ERRO[0000] error attempting to run sonobuoy: could not retrieve sonobuoy pod 
```
the i checked the pods status which shows only one pod continue to be existed ：
```
[root@master1 wenshiqi]# kubectl get pods -n sonobuoy
NAME                                                      READY   STATUS        RESTARTS   AGE
sonobuoy-systemd-logs-daemon-set-1b649f0da14446c0-swhcf   1/2     Terminating   2          52m
```
then i  checked this  terminating pod's  log:
```
Events:
  Type     Reason          Age   From               Message
  ----     ------          ----  ----               -------
  Normal   Scheduled       52m   default-scheduler  Successfully assigned sonobuoy/sonobuoy-systemd-logs-daemon-set-1b649f0da14446c0-swhcf to node1.localdomain
  Normal   Pulling         52m   kubelet            Pulling image "sonobuoy/systemd-logs:v0.3"
  Normal   Pulled          52m   kubelet            Successfully pulled image "sonobuoy/systemd-logs:v0.3" in 23.80319526s
  Normal   Created         52m   kubelet            Created container systemd-logs
  Normal   Started         52m   kubelet            Started container systemd-logs
  Normal   Pulled          52m   kubelet            Container image "sonobuoy/sonobuoy:v0.51.0" already present on machine
  Normal   Created         52m   kubelet            Created container sonobuoy-worker
  Normal   Started         52m   kubelet            Started container sonobuoy-worker
  Warning  NodeNotReady    24m   node-controller    Node is not ready
  Normal   SandboxChanged  21m   kubelet            Pod sandbox changed, it will be killed and re-created.
  Normal   Pulling         21m   kubelet            Pulling image "sonobuoy/systemd-logs:v0.3"
  Normal   Pulled          20m   kubelet            Successfully pulled image "sonobuoy/systemd-logs:v0.3" in 19.892845718s
  Normal   Created         20m   kubelet            Created container systemd-logs
  Normal   Started         20m   kubelet            Started container systemd-logs
  Normal   Pulled          20m   kubelet            Container image "sonobuoy/sonobuoy:v0.51.0" already present on machine
  Normal   Created         20m   kubelet            Created container sonobuoy-worker
  Normal   Started         20m   kubelet            Started container sonobuoy-worker
  Warning  BackOff         20m   kubelet            Back-off restarting failed container
  Warning  InspectFailed   16m   kubelet            Failed to inspect image "sonobuoy/sonobuoy:v0.51.0": rpc error: code = Unknown desc = Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
  Warning  Failed          16m   kubelet            Error: ImageInspectError
```
it seems the docker daemon's problem?? 

**What did you expect to happen:**
 test passed!

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
1. at the beginning of the test procedure, the pods in the namespace "sonobuoy" are four, as the test continue, i found the some pods are in error status, i don't know if this is the correct status as the sonobuoy test needs, or this shows my test has some problems.
2. as the test continue,i found one of my cluster node seems to be restart, cause i found my ssh client lost the connection, is this also the sonobuoy test procedure need?

**Environment:**

- Sonobuoy version: 
```
- Sonobuoy Version: v0.51.0
MinimumKubeVersion: 1.17.0
MaximumKubeVersion: 1.99.99
GitSHA: 2175943b5975e1e287d0179f4d18765f80819051
```
- Kubernetes version: (use `kubectl version`):
```
- Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:10:43Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:02:01Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

- Kubernetes installer & version:
```
- [root@master1 ~]# kubectl get nodes
NAME                  STATUS   ROLES                  AGE    VERSION
master1.localdomain   Ready    control-plane,master   6d1h   v1.20.5
node1.localdomain     Ready    <none>                 6d1h   v1.20.5
```
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`): 
```
- - NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

```
- Sonobuoy tarball (which contains * below)

**Comment by johnSchnake** [comment]
> Failed to inspect image "sonobuoy/sonobuoy:v0.51.0": rpc error: code = Unknown desc = Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

Yes I agree with the assessment that something is wrong with the docker daemon and at that point I can't really provide much assistance. 

> at the beginning of the test procedure, the pods in the namespace "sonobuoy" are four, as the test continue, i found the some pods are in error status, i don't know if this is the correct status as the sonobuoy test needs, or this shows my test has some problems.

Makes sense to me since you have 1) the sonobuoy aggregator pod 2) the e2e plugin pod 3&4) the systemd-logs pod on each node. As those pods finish they would shut down so the # would go down.

> as the test continue,i found one of my cluster node seems to be restart, cause i found my ssh client lost the connection, is this also the sonobuoy test procedure need?

Sonobuoy itself doesn't do anything like that so you may have had other issues with the node. It is possible that an e2e test tried to restart a node, but I don't think anything like that runs during certified conformance runs. The 'destructive tests' I think are more about policy/roles on a cluster level.

To me it seems like some sort of issue happened for your nodes that caused a node to restart, breaking your ssh connection and restarting the docker daemon causing the other issue.

If I were you I'd try and dig into those types of logs/events to see if you can find why the node restarted. If you have the tarball from `sonobuoy retrieve`, there are lots of logs in there that may help assist. You can also look in the kube-system podlogs (sonobuoy can be configured to grab those as well or you can just look through them with kubectl).

Good luck

**Comment by Wenshiqi222** [comment]
> > Failed to inspect image "sonobuoy/sonobuoy:v0.51.0": rpc error: code = Unknown desc = Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
> 
> Yes I agree with the assessment that something is wrong with the docker daemon and at that point I can't really provide much assistance.
> 
> > at the beginning of the test procedure, the pods in the namespace "sonobuoy" are four, as the test continue, i found the some pods are in error status, i don't know if this is the correct status as the sonobuoy test needs, or this shows my test has some problems.
> 
> Makes sense to me since you have 1) the sonobuoy aggregator pod 2) the e2e plugin pod 3&4) the systemd-logs pod on each node. As those pods finish they would shut down so the # would go down.
> 
> > as the test continue,i found one of my cluster node seems to be restart, cause i found my ssh client lost the connection, is this also the sonobuoy test procedure need?
> 
> Sonobuoy itself doesn't do anything like that so you may have had other issues with the node. It is possible that an e2e test tried to restart a node, but I don't think anything like that runs during certified conformance runs. The 'destructive tests' I think are more about policy/roles on a cluster level.
> 
> To me it seems like some sort of issue happened for your nodes that caused a node to restart, breaking your ssh connection and restarting the docker daemon causing the other issue.
> 
> If I were you I'd try and dig into those types of logs/events to see if you can find why the node restarted. If you have the tarball from `sonobuoy retrieve`, there are lots of logs in there that may help assist. You can also look in the kube-system podlogs (sonobuoy can be configured to grab those as well or you can just look through them with kubectl).
> 
> Good luck
really thanks for your reply, i just found that my node machine is OOM,maybe that is why the node is shutdown and the docker daemon is lost, cause my node is a vm machine set 1 GB RAM, maybe i will try 2GB RAM this time to see if it is enough to run the 
test,BTW, to run sonobuoy test , how much RAM and CPU to set is recommanded?

**Comment by johnSchnake** [comment]
> how much RAM and CPU to set is recommended?

When I just googled for it I found a few different sites/articles mentioning 2GB/node as a lower bound. Sonobuoy itself doesn't require much, the workloads are typically not terribly intensive (unless designed to be so) so its just the RAM for a functioning k8s cluster.
