### ISSUE TITLE
Retry KubernetesOnWindows

### ISSUE THREAD

**Issue by johnSchnake** [vmware-tanzu/sonobuoy#1320]
Originally I had wanted to do the bulk of the Windows work on KubernetesForWindows but I ran into a few issues that delayed my adoption.

If it is able to work out now, I'd love to:
 - amend our blog to mention k8s on windows project
 - set up/document process for manually testing with that project and avoiding azure so more people can test without extra accounts and fees

**Comment by johnSchnake** [comment]
Amended the blog because it seems I may have unique problems and as open source I know different people may have different tolerances for debugging those things.

I've put up some tiny PRs and have a cluster up but am so far unable to run sonobuoy on the cluster.

@jayunit100 I'm trying thge sonobuoy e2e plugin for windows and now I've tried `image: mcr.microsoft.com/dotnet/framework/samples:aspnetapp`. It seems to get scheduled but nothing after that seems to happen.

In the samples app it gets stuck in container creating for some reason (no error events or any unusual behavior; says it pulls the image OK too) and for sonobuoy it says it is running but I cant get logs and there otherwise seems to be no error at all. Just times out when I try to get logs so I'm not sure if the networking is quite right. I wouldn't think the pod would get to `running` state if the control plane couldnt communicate with the worker though.

Thoughts?

**Comment by johnSchnake** [comment]
Getting a new machine and will retry again to see if updates lately have fixed that problem.

**Comment by johnSchnake** [comment]
Unfortunately I'm not making much progress. `vagrant up` seems to get nodes up but after 20+m of provisioning I still ended here:

```
    winw1: This may take several seconds if the vSwitch needs to be created.
    winw1: Waiting for Calico initialisation to finish...
    winw1: Waiting for Calico initialisation to finish...StoredLastBootTime , CurrentLastBootTime 20210802101406.813459-420
    winw1: Waiting for Calico initialisation to finish...StoredLastBootTime , CurrentLastBootTime 20210802101406.813459-420
    winw1: Waiting for Calico initialisation to finish...StoredLastBootTime , CurrentLastBootTime 20210802101406.813459-420
    winw1: Waiting for Calico initialisation to finish...StoredLastBootTime , CurrentLastBootTime 20210802101406.813459-420
```

And kubectl shows both nodes:

```
kubectl get nodes
NAME           STATUS   ROLES                  AGE   VERSION
controlplane   Ready    control-plane,master   31m   v1.21.0
winw1          Ready    <none>                 19m   v1.21.2-rc.0
```

Then when I run sonobuoy it starts running but I can't get logs or status info and the IIS server container seems to have a problem too:

```
$ kubectl logs windows-server-iis-7985c648cc-k8qnc
Error from server (NotFound): the server could not find the requested resource ( pods/log windows-server-iis-7985c648cc-k8qnc)
$ sonobuoy logs
error streaming logs from container [kube-sonobuoy]: the server could not find the requested resource ( pods/log sonobuoy)%
```

**Comment by jayunit100** [comment]
Hmmmmm just saw this

**Comment by jayunit100** [comment]
Your right we are missin logs bc of the way we have private_networks set up in vagrant . I need to send the node IP correctly .  

Can you file an issue in the sig windows dev tools repo? Will try to fix it tomorrow AM!

**Comment by johnSchnake** [comment]
Things working now; closing. Another ticket is tracking building/documenting a testing strategy for windows using this.
