### ISSUE TITLE
v0.52  sonobuoy-systemd-logs deamonset NotReady

### ISSUE THREAD

**Issue by HaveFun83** [vmware-tanzu/sonobuoy#1322]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
`sonobuoy run` on v0.52  don't deploy the sonobuoy-systemd-logs deamonset correctly and it goes into NotReady / Crashloopbackoff

**What did you expect to happen:**
sonobuoy-systemd-logs deamonset should be deployed in an ready state

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
```
❯ diff -u v0.51_systemd-logs.yaml v0.52-systemd-logs.yaml
--- v0.51_systemd-logs.yaml     2021-06-23 14:30:12.769534884 +0200
+++ v0.52-systemd-logs.yaml     2021-06-23 14:30:27.413461363 +0200
@@ -6,8 +6,7 @@
   command:
   - /bin/sh
   - -c
-  - /get_systemd_logs.sh && while true; do echo "Sleeping for 1h to avoid daemonset
-    restart"; sleep 3600; done
+  - /get_systemd_logs.sh
   env:
   - name: CHROOT_DIR
     value: /node
```

v0.51 works as aspect.

**Environment:**

- Sonobuoy version: v0.52
- Kubernetes version: (use `kubectl version`): v1.21.1
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):  debian 10 / flatcar
- Sonobuoy tarball (which contains * below)

**Comment by HaveFun83** [comment]
I patched the v0.52.0 manifest from `sonobuoy gen` with:
```patch
@@ -113,7 +113,7 @@
       command:
       - /bin/sh
       - -c
-      - /get_systemd_logs.sh
+      - /get_systemd_logs.sh && while true; do echo "Sleeping for 1h to avoid daemonset restart"; sleep 3600; done
```
and the daemonset is running now

**Comment by johnSchnake** [comment]
Thanks for the bug report! I will repro this and check back in.

I had made changes to the sonobuoy worker which I thought was going to keep the pod alive but k8s may be trying to still just restart the container.

I would have thought in that flow the plugin would have still submitted results initially and sonobuoy wouldn't have had a problem. But I guess the k8s daemonset logic & sonobuoy monitoring logic consider that a problem.

**Comment by johnSchnake** [comment]
FWIW this is also one of the reasons we'd love to pull out those plugins from sonobuoy core; I want to just patch that yaml but it will require a whole point release to fix 👎

**Comment by johnSchnake** [comment]
Confirmation of the above; the plugins ran quickly and passed when I just ran the systemd-logs plugin on their own.

When I run the e2e plugin along with it, the plugin finishes as before, but k8s sees the container exit so it restarts the container and enters crash backoff loop.

```
sonobuoy status
         PLUGIN     STATUS   RESULT   COUNT
            e2e    running                1
   systemd-logs   complete                3

Sonobuoy is still running. Runs can take up to 60 minutes.
```
```
kubectl get pods -n sonobuoy
NAME                                                      READY   STATUS             RESTARTS   AGE
sonobuoy                                                  1/1     Running            0          2m38s
sonobuoy-e2e-job-1a135857fa6142d0                         2/2     Running            0          2m37s
sonobuoy-systemd-logs-daemon-set-c7564a4fe6f74ccc-h4wpc   1/2     CrashLoopBackOff   4          2m37s
sonobuoy-systemd-logs-daemon-set-c7564a4fe6f74ccc-tl9kx   1/2     CrashLoopBackOff   4          2m37s
sonobuoy-systemd-logs-daemon-set-c7564a4fe6f74ccc-wpf82   1/2     CrashLoopBackOff   4          2m37s
```

I let it run for about 10m and nothing really changed; I thought that perhaps the aggregator would get upset about the state of those containers but it doesn't. So k8s shows it as CrashLoopBackoff but there seems to be no consequence beyond that.

I'll patch the yaml though to put the sleep back. The change where that was removed still resolved the issue that was occurring before I think though since the 409s were handled more appropriately. I'll look that change over more.

**Comment by johnSchnake** [comment]
Just put a PR to restore this and improve it a bit. Let me know your thoughts.

**Comment by liggitt** [comment]
I'm seeing this as well... is this fix released?
