### ISSUE TITLE
Incorrect link in windows-e2e-tests-with-sonobuoy blog post

### ISSUE THREAD

**Issue by superlime** [vmware-tanzu/sonobuoy#1323]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

Towards the end of the article, there's a link to "sonobuoy-plugins" that points at https://github.com/vmware-tanzu/sonobuoy-plugins/windows-e2e, but it should actually point at https://github.com/vmware-tanzu/sonobuoy-plugins/tree/master/windows-e2e

**What did you expect to happen:**

Link to go to the correct source path

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

Looks like fix is on line 145 of the md.  :)

**Environment:**

- Sonobuoy version: N/A
- Kubernetes version: N/A
- Kubernetes installer & version: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from `/etc/os-release`): N/A
- Sonobuoy tarball (which contains * below) N/A

**Comment by johnSchnake** [comment]
💯 Thanks, fixing that now.

**Comment by johnSchnake** [comment]
#1327
