### ISSUE TITLE
Sonobuoy v0.51.0 with TKGi 1.10, K8s 1.19.9 and NCP 3.1 fails for [sig-network] Tests

### ISSUE THREAD

**Issue by tim-nussbaumer** [vmware-tanzu/sonobuoy#1326]
**While running Sonobuoy on TKGi Kubernetes Cluster it leads to the following Errors:**

Failed tests:
[sig-network] Services should have session affinity timeout work for service with type clusterIP [LinuxOnly] [Conformance]
[sig-network] Services should be able to switch session affinity for service with type clusterIP [LinuxOnly] [Conformance]
[sig-network] Services should have session affinity work for service with type clusterIP [LinuxOnly] [Conformance]

Those Tests are expected to pass for the CNC Certification

In the NCP 3.1 Release Notes it's stated as followed:
_For a Kubernetes service of type ClusterIP, Client-IP based session affinity is not supported
NCP does not support Client-IP based session affinity for a Kubernetes service of type ClusterIP.
Workaround: None_
https://docs.vmware.com/en/VMware-NSX-T-Data-Center/3.1/rn/NSX-Container-Plugin-31-Release-Notes.html

What workaround can be used to pass the Conformance tests?

**Environment:**

- Sonobuoy version: v0.51.0
- Kubernetes version: 1.19.9 
- Kubernetes installer & version: 
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`): 
- Sonobuoy tarball (which contains * below)
- NCP 3.1

**Comment by johnSchnake** [comment]
If a feature is not supported that conformance requires, I do not know that any sort of workaround is possible. To my knowledge, there isn't a sort of 'certification with exceptions'. Closing this and will track internally.
