### ISSUE TITLE
Mirror sonobuoy images in harbor

### ISSUE THREAD

**Issue by johnSchnake** [vmware-tanzu/sonobuoy#1337]
Sonobuoy images (sonobuoy itself and the systemd-logs plugin image) are in dockerhub which added rate limited for unauthorized users. This is often a problem in CI where lots of pulls may occurpul

- We should provide a mirror for users to use as an alternative so they can get around the limit
- Consider making harbor the default. Its nice to just say `sonobuoy/sonobuoy` and harbor would be more verbose, but it would work better in many situations. 

Need to just move the images over, I'd say from v0.50 and later of sonobuoy (just the version tags are fine) and 1-2 images of systemdlogs.

**Comment by johnSchnake** [comment]
docker pull projects.registry.vmware.com/sonobuoy/sonobuoy:v0.50.0
docker pull projects.registry.vmware.com/sonobuoy/sonobuoy:v0.51.0
docker pull projects.registry.vmware.com/sonobuoy/sonobuoy:v0.52.0
docker pull projects.registry.vmware.com/sonobuoy/systemd-logs:v0.3

The above images have been moved over. Going to close this for how and just post in slack that this is an option for folks. If we get a lot of use/discussion then maybe we will move to that as the default.

**Comment by discordianfish** [comment]
By default sonobuoy still uses the docker.io images. Might make sense to change that default.
