### ISSUE TITLE
How to set the "ImagePullPolicy" to IfNotPresent

### ISSUE THREAD

**Issue by Wenshiqi222** [vmware-tanzu/sonobuoy#1362]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Since some machines in my cluster cannot connect to the gcr ,i need to prepare the images previously! And luckily  i have a control-plane machie which can pull all the images successfully! 
So i want to push all the images to my private Registry and let other machines pull the necessary images form that private Registry,so that other machines can do the sonobuoy test. ---------But the sonobuoy seems set the ImagePullPolicy with "Always",whcih means even if the machies have all the images needed  but cannot connet the to the gcr Registry will still fail .

**What did you expect to happen:**
I want to Set the ImagePullPolicy with "IfNotPresent",so all test process don't need to connect to the gcr Registry but to  find the images locally!

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
I wannt to do all the test plugins for my k8s cluster,so i need all images .

**Environment:**

- Sonobuoy version: v0.51.0
- Kubernetes version: (use `kubectl version`):1.20.5
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`): CentOS 7

**Comment by johnSchnake** [comment]
ImagePullPolicy can be set with the `--imagePullPolicy` flag. In addition, it sounds like the airgap posts/documentation would be useful for you: 
 - https://sonobuoy.io/docs/v0.52.0/airgap/
 - https://sonobuoy.io/isolated-to-conformant/

You can also do `sonobuoy gen` to see/save the full YAML sonobuoy would be using then edit directly and use `sonobuoy run -f updatedvalues.yaml`

**Comment by Wenshiqi222** [comment]
> ImagePullPolicy can be set with the `--imagePullPolicy` flag. In addition, it sounds like the airgap posts/documentation would be useful for you:
> 
> * https://sonobuoy.io/docs/v0.52.0/airgap/
> * https://sonobuoy.io/isolated-to-conformant/
> 
> You can also do `sonobuoy gen` to see/save the full YAML sonobuoy would be using then edit directly and use `sonobuoy run -f updatedvalues.yaml`

thanks，but when i pull the image with command“Sonobuoy images pull”，some images cannot be pulled by the 
```
ERRO[0006] failed with following error after 1 retries: 
ERRO[0006] Error response from daemon: Get https://gcr.io/v2/: proxyconnect tcp: dial tcp 192.168.137.1:1080: connect: connection refused 
INFO[0006] Pulling image: gcr.io/kubernetes-e2e-test-images/nonroot:1.0 ... 
ERRO[0007] failed with following error after 1 retries: 
ERRO[0007] Error response from daemon: Get https://gcr.io/v2/: proxyconnect tcp: dial tcp 192.168.137.1:1080: connect: connection refused 
INFO[0007] Pulling image: docker.io/library/busybox:1.29 ... 
ERRO[0008] failed with following error after 1 retries: 
ERRO[0008] Error response from daemon: Get https://registry-1.docker.io/v2/: proxyconnect tcp: dial tcp 192.168.137.1:1080: connect: connection refused 

```
so i cannot pull the images fully ,what can i do to sovle this problem? @johnSchnake
