### ISSUE TITLE
The sonobuoy report logs to error channel even if there is no error on execution

### ISSUE THREAD

**Issue by jifwang-microsoft** [vmware-tanzu/sonobuoy#1364]
**What steps did you take and what happened:**
Try to execute the sonobuoy with our developed version of test. And in Windows platform, we will see:
~~~~~~~~~~~~~~
  PS C:\agent\work\1\s> sonobuoy delete --wait
  sonobuoy : time="2021-07-21T20:24:47-07:00" level=info msg=deleted kind=namespace namespace=sonobuoy
  At line:1 char:1
  sonobuoy delete --wait
      CategoryInfo          : NotSpecified: (time="2021-07-2...espace=sonobuoy:String) [], RemoteException
      FullyQualifiedErrorId : NativeCommandError
   
  time="2021-07-21T20:24:47-07:00" level=info msg=deleted kind=clusterrolebindings
  time="2021-07-21T20:24:47-07:00" level=info msg=deleted kind=clusterroles
~~~~~~~~~~~~~~~

**What did you expect to happen:**
You can see from the output that it is actually just a message, but it report to the stderr, so it makes the call failed

**Anything else you would like to add:**
Please refer to this: https://github.com/sirupsen/logrus/blob/master/README.md
~~~~~~~~
  // Output to stdout instead of the default stderr
  // Can be any io.Writer, see below for File example
  log.SetOutput(os.Stdout)
~~~~~~~~~~

The source code: 
https://github.com/sirupsen/logrus/blob/master/logger.go#L87
~~~~~~~~~~~~~~~~
func New() *Logger {
	return &Logger{
        Out:          os.Stderr,
        Formatter:    new(TextFormatter),
        Hooks:        make(LevelHooks),
        Level:        InfoLevel,
        ExitFunc:     os.Exit,
        ReportCaller: false,
	}
}
~~~~~~~~~~~~~~~~~~

As the default output is stderr. it is no proper to not set this. Also try this on a small program that can easily reproduce.
~~~~~~~~
package main

import (
    "os"
    "fmt"
    "rsc.io/quote"
    "github.com/sirupsen/logrus"
)

func main() {
    logrus.SetOutput(os.Stdout)
    log := logrus.WithFields(logrus.Fields{
        "name":      "My Name",
        "namespace": "My Namespace",
        "resource":  "My Resource",
    })
    log.Print("Create object 1")
    fmt.Println(quote.Go())
}
~~~~~~~~~

**Environment:**

- Sonobuoy version: 0.52
- Kubernetes version: (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`): 
- Sonobuoy tarball (which contains * below)

**Comment by johnSchnake** [comment]
So the logs go to stderr by design, regardless of whether we use `logrus.Infof` or `logrus.Errorf`; the purpose of this is so that you/we can more easily differentiate normal command output (which we just use `fmt.Print...` in most cases) and log output which may be trace data or other misc warnings and info.

The existence of output on stderr is not what causes a command to fail, only the exit code does that. So its possible to see `logrus.Infof` messages on stderr and get either a passing command or a failing one.
