### ISSUE TITLE
Create a community use page

### ISSUE THREAD

**Issue by johnSchnake** [vmware-tanzu/sonobuoy#1371]
**Describe the solution you'd like**
Recommended by @salaboy and I think its a great idea: we should have a page which shows different projects and their use of Sonobuoy. We can let folks submit their own projects just to be linked for visibility and knowledge sharing. Blog posts, plugins, CI scripts, etc.

**Comment by salaboy** [comment]
100% this would be great to have.. as people can see how other projects are using sonobuoy for reference and reusing standard practices.

**Comment by salaboy** [comment]
@johnSchnake In Knative, we just created an issue to track this: https://github.com/knative/community/issues/696 it might be a simple and quick starting point.

**Comment by johnSchnake** [comment]
Sounds good; thats very simple too and wont require PRs. I'll be sure to link to it from the Community/docs pages when I can too

**Comment by johnSchnake** [comment]
I feel like I'm going crazy; I could have sworn we had an issue like that a _long_ time ago and I cant find it. Going to search a bit more and maybe will reopen it if I find it. Otherwise I'll recreate.

**Comment by johnSchnake** [comment]
I shamelessly copied most of the post from Knative, I hope thats ok. I tweaked it to make it clear that I am OK with selfpromotion of sonobuoy related blog posts or scripts/plugins/etc.

Thanks @salaboy for the recommendation and resource
