### ISSUE TITLE
Change from 'master' to 'main' for all Sonobuoy repos

### ISSUE THREAD

**Issue by jonasrosland** [vmware-tanzu/sonobuoy#1396]
This is a requested change for all our open source projects, to be aligned with VMware's inclusive terminology.

**Comment by johnSchnake** [comment]
Mostly done on vmware-tanzu-sonobuoy; its technically done but I need to update a bunch of the doc references and scripts etc. In the meantime it seems GH will redirect since it can tell we just renamed it.

**Comment by johnSchnake** [comment]
#1401 and #1402 close this.
