### ISSUE TITLE
Sonobuoy v0.50.0 Error attempting to run sonobuoy

### ISSUE THREAD

**Issue by fabianKingKong** [vmware-tanzu/sonobuoy#1400]
I tried to run sonobuoy with the command `sonobuoy run --mode=certified-conformance`. After that a sonobuoy pod will come up but when trying to get sonobuoy status the following output appears:

`ERRO[0000] error attempting to run sonobuoy: missing status annotation "sonobuoy.hept.io/status"`

What could be the issue?

**Comment by johnSchnake** [comment]
Closed due to inactivity.
