### ISSUE TITLE
Sonobuoy v0.53.2 : Plugin timeout while waiting for results so there are no results

### ISSUE THREAD

**Issue by otaqatqa** [vmware-tanzu/sonobuoy#1403]
**What steps did you take and what happened:**
I pulled/tagged/ pushed the sonobuoy images to bcmt-registry:5000

And created the custom repo file

cat << EOF > /root/custom-repo-config.yaml
buildImageRegistry: bcmt-registry:5000
dockerGluster: bcmt-registry:5000
dockerLibraryRegistry: bcmt-registry:5000
e2eRegistry: bcmt-registry:5000
e2eVolumeRegistry: bcmt-registry:5000
gcRegistry: bcmt-registry:5000
gcEtcdRegistry: bcmt-registry:5000
promoterE2eRegistry: bcmt-registry:5000
sigStorageRegistry: bcmt-registry:5000
 
EOF

Then I ran sonobuoy as following:
sonobuoy run --sonobuoy-image bcmt-registry:5000/sonobuoy:v0.53.2 \
   --kube-conformance-image bcmt-registry:5000/conformance:v1.21.0 \
   --systemd-logs-image bcmt-registry:5000/systemd-logs:v0.3 \
   --plugin-env=e2e.E2E_EXTRA_ARGS="--non-blocking-taints=is_control,is_edge" \
   --e2e-repo-config /root/custom-repo-config.yaml \
   --mode=certified-conformance

The test ran for couple of hours and after that i collected the results

[root@eindhoven-v331-allinone-0 ~ (Active)]# outfile=$(sonobuoy retrieve)
[root@eindhoven-v331-allinone-0 ~ (Active)]# sonobuoy results --mode detailed --plugin e2e $outfile |  jq '.  | select(.status ==                                                                       "failed") | .details'
parse error: Invalid numeric literal at line 1, column 11
[root@eindhoven-v331-allinone-0 ~ (Active)]# sonobuoy results --mode detailed --plugin e2e $outfile
e2e|Plugin timeout while waiting for results so there are no results. Check pod logs or other cluster details for more informatio                                                                      n as to why this occurred. {"error":"Plugin timeout while waiting for results so there are no results. Check pod logs or other cl                                                                      uster details for more information as to why this occurred."}[root@eindhoven-v331-allinone-0 ~ (Active)]#
[root@eindhoven-v331-allinone-0 ~ (Active)]#

**What did you expect to happen:**
Can't check the sonobuoy results from the tarball and i found the following error message:
{"error":"Plugin timeout while waiting for results so there are no results. Check pod logs or other cluster details for more information as to why this occurred."}

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Sonobuoy version: 
[root@eindhoven-v331-allinone-0 ~ (Active)]# sonobuoy version
Sonobuoy Version: v0.53.2
MinimumKubeVersion: 1.17.0
MaximumKubeVersion: 1.99.99
GitSHA: 981a3ffd4368600eb1a5bca3f12a251e80895d37
API Version check skipped due to missing `--kubeconfig` or other error
[root@eindhoven-v331-allinone-0 ~ (Active)]#

- Kubernetes version: (use `kubectl version`):
[root@eindhoven-v331-allinone-0 ~ (Active)]# kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:25:06Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
[root@eindhoven-v331-allinone-0 ~ (Active)]#

- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`): 
[root@eindhoven-v331-allinone-0 ~ (Active)]# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

You have new mail in /var/spool/mail/root
[root@eindhoven-v331-allinone-0 ~ (Active)]#

- Sonobuoy tarball (which contains * below)

**Comment by johnSchnake** [comment]
I'm not sure what you're asking for exactly. As the message says: "Plugin timeout while waiting for results so there are no results. Check pod logs or other cluster details for more information as to why this occurred."

Have you checked those logs? Generally, this isn't a problem with sonobuoy but a problem with the cluster causing tests to run long or hang.

If you want to post your tarball I can peek at it for you but as it stands this isnt a bug as much as it is just a typical error case. The reason we timeout at all is so that we see this error and can realize there is a problem instead of the run stalling entirely, not getting the tarball to investigate, and eating up resources/time.

If you want you can specify `--timeout=999999999` or something like that (check the help text to see if thats seconds or minutes) to extend the timeout. However, I think the timeout was extended a while back and isn't typically hit without an underlying problem.

**Comment by johnSchnake** [comment]
Closed due to inactivity. Feel free to reopen if you had more information to debug.
