### ISSUE TITLE
Brainstorming ideas about custom post-processing or plugin reporting options

### ISSUE THREAD

**Issue by johnSchnake** [vmware-tanzu/sonobuoy#1405]
Just brainstorming about where some output/presentation items may be done.

For instance:

We've considered reviving the idea of the `scanner` (but local, not SAAS) so you can have a visual sonobuoy runner rather than CLI. But what about an idea like this but just for processing output? A sonobuoy results viewer where you just point to the tarball and then you can see beautiful, detailed reports about the results?

Should this be a separate project? Should we just put this into sonobuoy proper as a selectable output format (html)?

It would be a cool idea if we _could_ chain output from plugins or have post-processing steps somehow. That way we'd have two sorts of plugins: plugins that gather data (the ones we have now) and plugins that just are meant to be post-processors of data that is already gathered. This way if "developer dave" wants to have a nice, custom report for all his e2e testing he doesn't have to write a dockerfile to wrap the e2e tests etc etc. Instead he could just say something like "take output from plugin e2e and run this script to generate new data".

Part of the motivation for any/all of these is the visual appeal but another is just the real value that can come from breaking down the data in different ways. Why not make it easy to see tables of which types of tests failed by tag? It would make it easier to debug if you quickly saw that all the tests failed that had certain tags or all failed in 5.0m or something like that. What about if you could graphically see that all the tests passed until time X and then a few tests failed in a row?

Just brainstorming. Ideas and feedback are welcome.

**Comment by johnSchnake** [comment]
FYI @vladimirvivien @eleanor-millman

**Comment by johnSchnake** [comment]
- [ ] Would this be a good fit for octant? Let's take a look at that and see how it could work.

**Comment by sagar-shah-uipath** [comment]
We also require this use case where we can format result of tests at end of run like below image or it should be configurable.
![image](https://user-images.githubusercontent.com/89075615/140020751-2e147791-32ce-4ff4-b4de-c7e2ad0943a4.png)

**Comment by vladimirvivien** [comment]
@johnSchnake I think having a visual representation of the data is still a viable/useful idea. What about a plugin for [Octant](https://reference.octant.dev/?path=/docs/docs-plugins-1-getting-started--page) that would provide a file explorer to view results (just an idea).
