### ISSUE TITLE
Investigate using Brigade instead of the done files

### ISSUE THREAD

**Issue by chuckha** [vmware-tanzu/sonobuoy#141]
We could use brigade to coordinate worker pods/plugins.

https://github.com/Azure/brigade

This would allow us to use arbitrary pods as plugins and not have to customize our own images that wrap some binary with a shell script that writes outputs to a done file.

Also simplifies the `RESULTS_DIR` since that would no longer be necessary.

**Comment by johnSchnake** [comment]
Closing this for now; doing some grooming on the issue list in general and closing things if either:
 - they weren't been reported by the community
 - don't have a genuine need to get done

The reason for this is that we tended to use the issue list as a backlog of very minor or wish-list type items which we wish to clear out for now.
