### ISSUE TITLE
Should specify security context

### ISSUE THREAD

**Issue by johnSchnake** [vmware-tanzu/sonobuoy#1410]
From a conversation with @btrieger :

> Most of the admission controllers for pod security check to see that a securityContext is set as they can't see what is in the dockerfile itself...

He ran into Sonobuoy being blocked by OPA Gatekeeper. This should be able to be resolved if we simply explicitly state the RunAsUser in the podspec for the aggregator.

**Comment by btrieger** [comment]
A runAsGroup would be great as well so we can explicitly state no root user or group.
