### ISSUE TITLE
Helper for running e2e more quickly

### ISSUE THREAD

**Issue by johnSchnake** [vmware-tanzu/sonobuoy#1435]
It is possible to run many of the e2e (including conformance) tests in parallel but some do require that they are run in serial.

However, it seems like it would be a helpful configuration to share how to optimize the time to run.

It wouldn't be a replacement for the `certified-conformance` runs, but in CI systems or whatnot it would be nice to be able to cut the time to run in half (not sure the full time savings).

I think stuff like this can fit into the sonobuoy-plugins repo under the related folder. So I could make up an e2e serial/parallel configuration and so the run would look like:

```
sonobuoy run -p e2eparallel -p e2eserial
```

At first, you'd have to specify a yaml file or the URL, but with our new plugin management, it would really look like ^.

**Comment by aleksey-hariton** [comment]
@johnSchnake do you know a way to run tests in parallel? 

Flag `--e2e-parallel` even not showing in `--help` (but I can pass it without issues) and looks like sonobuoy ignoring `E2E_PARALLEL` env variable.

```
# in both cases tests are running in serial mode
E2E_PARALLEL=10 sonobuoy run --wait --mode=certified-conformance --kube-conformance-image gcr.io/google-containers/conformance:v1.19.0-rc.1
sonobuoy run --wait --e2e-parallel=10 --mode=certified-conformance --kube-conformance-image gcr.io/google-containers/conformance:v1.19.0-rc.1
```

**Comment by johnSchnake** [comment]
Its the container that needs the E2E_PARALLEL value, not the CLI environment.

Are you sure the tests aren't running parallel when you provide the flag? The gen command below shows that the flag does set the env var as expected.
```
sonobuoy gen --e2e-parallel=10 --kubernetes-version=ignore | grep PAR --context=1
```
At that point, if it doesn't run in parallel it is an upstream issue I'll need to fix.

Going to test this myself but appreciate if you can confirm as well.

**Comment by johnSchnake** [comment]
When I tried and looked in the logs I got:
```
Args (comma-delimited): /usr/local/bin/ginkgo,--focus=\[Conformance\],--skip=Serial,--noColor=true,/usr/local/bin/e2e.test,--,--disable-log-dump,--repo-root=/kubernetes,--provider=local,--report-dir=/tmp/sonobuoy/results,--kubeconfig=,--progress-report-url=http://localhost:8099/progress
```
So the focus/skip got set on the e2e invocation but not the parallel. The env var is set as expected. Going to look upstream.

**Comment by johnSchnake** [comment]
https://github.com/kubernetes/kubernetes/blob/dbebb8f2e8361db92ccc72ab9da44d7e5b38f76f/test/conformance/image/go-runner/cmd.go#L34-L40 makes it seem like you and I both just misundertand the syntax. I remember being confused from the start but I was just trying to copy whatever was there before. It seems more like you turn parallel on/off rather than set it to a value.

**Comment by johnSchnake** [comment]
When using --e2e-parallel=true then I saw this in the logs:
```
Running in parallel across 7 nodes
```
but its a bit odd since I only have a 3 node cluster :)

I'll have to dig into some but my guess is that it is all working as intended but I just dont understand it.

**Comment by johnSchnake** [comment]
The "7 nodes" comes from the number of CPUs and is part of ginkgo itself:
https://github.com/onsi/ginkgo/blob/e4cff825178c07d5f3d68cb5f61e94c4a8beccdf/ginkgo/testrunner/test_runner.go#L318

So I guess that is why parallel is just 'on' or 'off' too. So it seems the e2e-parallel should just be a boolean flag; I'll go and see if there is any reason not to make that change. It would be a breaking change but very small and easy to fix.

**Comment by johnSchnake** [comment]
```
```
SUCCESS! -- 291 Passed | 0 Failed | 0 Pending | 5376 Skipped

Ginkgo ran 1 suite in 14m54.061962467s
```
The speedup is real; 291 tests in 15m when in parallel.

**Comment by johnSchnake** [comment]
Ginkgo docs say you _can_ specfy the # of parallel though via:
```
ginkgo -nodes=N runs your tests in N parallel processes and print out coherent output in realtime
```
So maybe that was just never taken advantage of.
