### ISSUE TITLE
Failed : Events should be sent by kubelets and the scheduler about pods scheduling and running  [Conformance]

### ISSUE THREAD

**Issue by naveen04git** [vmware-tanzu/sonobuoy#1445]
**What steps did you take and what happened:**
The test-case "should be sent by kubelets and the scheduler about pods scheduling and running" fails when using a custom scheduler. This could be related to the e2e test-case around it which expects the events to be generated by the default-scheduler which will not be true in this case.

**What did you expect to happen:**
The test-case was expected to pass since the events were generated and could be listed using the kubectl get events -n <event-namespace> command.
```
kubectl get events -n events-927
LAST SEEN   TYPE     REASON      OBJECT                                                 MESSAGE
67s         Normal   Scheduled   pod/send-events-40f104d3-982e-40f8-af7c-c531be3c3c05   Successfully assigned events-927/send-events-40f104d3-982e-40f8-af7c-c531be3c3c05 to dss5vm02
66s         Normal   Pulled      pod/send-events-40f104d3-982e-40f8-af7c-c531be3c3c05   Container image "k8s.gcr.io/e2e-test-images/agnhost:2.21" already present on machine
66s         Normal   Created     pod/send-events-40f104d3-982e-40f8-af7c-c531be3c3c05   Created container p
66s         Normal   Started     pod/send-events-40f104d3-982e-40f8-af7c-c531be3c3c05   Started container p
3s          Normal   Killing     pod/send-events-40f104d3-982e-40f8-af7c-c531be3c3c05   Stopping container p
```
**Anything else you would like to add:**
The issue looks to be related how the e2e test-case checks the results in kubernetes/test/e2e/node/events.go. The test-case passes the source scheduler as "default-scheduler". We are using a custom scheduler (on the lines of https://kubernetes.io/docs/tasks/extend-kubernetes/configure-multiple-schedulers/) When using a custom scheduler, the source of events is the custom-scheduler name and not the "default-scheduler" so the test-case does not see any events and fails.

I have attached the logs for reference:

**Environment:**

- Sonobuoy version:  0.53.2
- Kubernetes version: (use `kubectl version`): 1.20.11
- Kubernetes installer & version: kubeadm 1.20.11
- Cloud provider or hardware configuration: 
- OS (e.g. from `/etc/os-release`): centos
- Sonobuoy tarball (which contains * below) 
[202110020600_sonobuoy_a5e512a1-2e8b-426e-bd87-edce1f93c538.tar.gz](https://github.com/vmware-tanzu/sonobuoy/files/7270957/202110020600_sonobuoy_a5e512a1-2e8b-426e-bd87-edce1f93c538.tar.gz)

**Comment by johnSchnake** [comment]
Sonobuoy itself isn't responsible for the e2e tests; those are implemented by upstream kubernetes/kubernetes and the respective special interest groups (SIGs) that have the domain-specific knowledge that is relevant.

- If you think this test case is invalid then you'll need to make an [issue](https://github.com/kubernetes/kubernetes/issues/new?assignees=&labels=kind%2Fbug&template=bug-report.md) upstream.
- When making the issue you'll want to review their guidelines to help get it triaged more quickly. Since this involves the scheduler you should add (on its own line) `/sig scheduling` and also `/area conformance`
