### ISSUE TITLE
Unable to retrieve sonobuoy results after upgrading to 0.54.0

### ISSUE THREAD

**Issue by neha-viswanathan** [vmware-tanzu/sonobuoy#1475]
**What steps did you take and what happened:**
We are running the sonobuoy quick test on our EKS cluster and we are unable to retrieve the test results, This is happening after we upgraded to v0.54.0.
`error retrieving results: no valid entries in result`

**What did you expect to happen:**
```
Extracting run results:
###############################################################################
Plugin: e2e
Status: passed
Total: 5484
Passed: 1
Failed: 0
Skipped: 5483
Plugin: systemd-logs
Status: passed
Total: 8
Passed: 8
Failed: 0
Skipped: 0
###############################################################################
         PLUGIN     STATUS   RESULT   COUNT   PROGRESS
            e2e   complete   passed       1           
   systemd-logs   complete   passed       8           
Sonobuoy has completed. Use `sonobuoy retrieve` to get results.
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Sonobuoy version: 0.54.0
- Kubernetes version: (use `kubectl version`): 1.19.15
- Kubernetes installer & version: eksctl 0.69.0
- Cloud provider or hardware configuration: EKS
- OS (e.g. from `/etc/os-release`): 
- Sonobuoy tarball (which contains * below)
[sonobuoy-quick-logs.txt](https://github.com/vmware-tanzu/sonobuoy/files/7368659/sonobuoy-quick-logs.txt)

**Comment by johnSchnake** [comment]
Are you using a custom config at all? I'm running into a similar issue on a dev branch but its clear that I'm running into it because I was modifying the results_dir values in the config.

**Comment by neha-viswanathan** [comment]
We do not have any custom config. This is the command we use:
```
./sonobuoy run \
    --kubernetes-version "auto" \
    --plugin-env=e2e.E2E_EXTRA_ARGS="--allowed-not-ready-nodes=$(kubectl get nodes -l "node.kubernetes.io/instancegroup!=default" --no-headers | wc -l | tr -d ' ')" \
    --mode quick
 ```

**Comment by neha-viswanathan** [comment]
@johnSchnake had to improve some tests on our end to get this working. Thanks again for your help.
