### ISSUE TITLE
sonobuoy run --plugin-env key=value does not set environmental variables for the side car container

### ISSUE THREAD

**Issue by rapatchi** [vmware-tanzu/sonobuoy#1510]
**What steps did you take and what happened:**
We have a scenario where we need to deploy a side car container along with the main plugin container.
And we were passing environmental variable to the main plugin container using --plugin-env flag of sonobuoy cli. This does not seem to set those environmental variables to the side car container.

**What did you expect to happen:**
The expectation is that the environmental variables passed through --plugin-env flag should be set on the side car container as well.
Or, Please suggest a way for us to pass them to the sidecar as well.

**Environment:**

- Sonobuoy version: v0.53.2
- Kubernetes version: (use `kubectl version`):
  Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"windows/amd64"}
  Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.9", GitCommit:"ed93e7ea8f833824d05578765c2ad3efbebbfebe", GitTreeState:"clean", BuildDate:"2021-10-21T03:31:08Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}
- Kubernetes installer & version: AKS 1.20
- Cloud provider or hardware configuration: AKS
- OS (e.g. from `/etc/os-release`): Ubuntu 16.04
- Sonobuoy tarball (which contains * below)

**Comment by johnSchnake** [comment]
Hey, we actually found this to be a problem too and just recently added it! It'll be in the next release, v0.55.0 which I was just starting to prep. See #1485

**Comment by rapatchi** [comment]
Thanks!. When is the next release scheduled ?.

**Comment by johnSchnake** [comment]
I have a branch for adding docs and tagging it now; it should be out within an hour.

**Comment by johnSchnake** [comment]
It is available now https://github.com/vmware-tanzu/sonobuoy/releases/tag/v0.55.0 I'm running some checks out and going to rewrite the release notes. Let me know if this resolves your issue or there is still something lacking.
