### ISSUE TITLE
Sonobuoy v0.55.0 is not honouring the results dir volume mount passed in the config

### ISSUE THREAD

**Issue by rapatchi** [vmware-tanzu/sonobuoy#1512]
**What steps did you take and what happened:**
With the latest version of sonobuoy the default volume mount has been changed from "/tmp/results" to "/tmp/sonobuoy/results". This is breaking our existing plugins which were hardcoding this path in the plugin code.

Is there a way to override the results directory and point it to the old location?.  
Or, is the expected breaking change and we need to fix our plugins to honor according to "RESULTS_DIR" env variable?.
Currently I have tried the adding the below in plugin config but sonobuoy does not seem to honour that. 
```
  volumeMounts:
  - mountPath: /tmp/results
    name: results
```

**What did you expect to happen:**
sonobuoy should have honored the volumemount configuration provided in the plugin config.

**Environment:**

- Sonobuoy version: v0.55.0
- Kubernetes version: (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.9", GitCommit:"ed93e7ea8f833824d05578765c2ad3efbebbfebe", GitTreeState:"clean", BuildDate:"2021-10-21T03:31:08Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}
- Kubernetes installer & version: AKS
- Cloud provider or hardware configuration: Azure AKS
- OS (e.g. from `/etc/os-release`): windows
- Sonobuoy tarball (which contains * below)

**Comment by johnSchnake** [comment]
Hey, thanks for the ticket.

The issue is one of priority; so your plugin is specifying a unique mount volume for results but you're using the default sonobuoy config presumably which defaults to /tmp/sonobuoy/results

If you want to use /tmp/results just provide your own sonobuoy config via:
```
sonobuoy gen config|jq '.ResultsDir="/tmp/results"'
```
That generates the default config then edits that results dir value.

Let me know if you run into problems.
