### ISSUE TITLE
Progress for e2e when in parallel is broken

### ISSUE THREAD

**Issue by johnSchnake** [vmware-tanzu/sonobuoy#1519]
**What steps did you take and what happened:**
Run with `--e2e-parallel=true`
Periodically check `sonobuoy status`
Tests completed goes up/down. For example:
```
➜  sonobuoy git:(main) ✗ sonobuoy status
         PLUGIN     STATUS   RESULT   COUNT             PROGRESS
            e2e    running                1   38/-1 (0 failures)
   systemd-logs   complete                3

Sonobuoy is still running. Runs can take 60 minutes or more depending on cluster and plugin configuration.
➜  sonobuoy git:(main) ✗ sonobuoy status
         PLUGIN     STATUS   RESULT   COUNT             PROGRESS
            e2e    running                1   24/-1 (0 failures)
   systemd-logs   complete                3

Sonobuoy is still running. Runs can take 60 minutes or more depending on cluster and plugin configuration.
```

**What did you expect to happen:**
Should monotonically go up

xref #1435 for confusion about parallel in general
I don't think this is related to #1507 ; I think that is about a conflict between different plugins sending updates that sometimes clash.

I think this is just a case of how the ginkgo/reporter/parallel code works. Normally when you send updates you need to actually send a new count for completed/failed/etc but when it runs in parallel, no single thread has all that info so the threads are sending incompatible updates and we just see the most current one at any given time.

I think a solution to this may be two-fold:
 - changing code upstream and see if we can set up a single source of truth across those threads
 - updating sonobuoy progress logic to allow for different types of updates; one where you send all the info and another where you just patch the info. It wouldnt be a full HTML patch, but effectively just a way to say 'another passed' or 'this one failed' and the aggregator would just handle the totals/list itself.

**Comment by NikhilSharmaWe** [comment]
@johnSchnake please inform if I can collaborate in anyway to solve this issue.

**Comment by johnSchnake** [comment]
Confirmed on a parallel run that each 'runner' (# runners = # cpus) produces its own junit xml file as well. Sonobuoy does process those all properly though and gives full results.

**Comment by johnSchnake** [comment]
So looking at how ginkgo works a bit, it creates a client/server setup where the server is the source of truth and owns the queue of tests which it distributes to the completely separate clients. I haven't found a way for the clients to communicate routinely in the reporters or anything.

So I think the best thing that we can do is to support appending to results rather than just writing them entirely.

Thinking about where the 'work' of this should belong, I'm starting to lean towards it existing solely in the 'worker'. So the plugin has to be aware to some extent that it is writing these results differently, so it seems reasonable that it could write them to a different URL (e.g. /progress/append or something). And in that case the worker will have to keep track of a progress object itself and update it before sending it onto the aggregator.

Alternatively, we may be able to get away from the extra URL if we just do something like set the worker into an 'appendProgress' mode so we reuse the URL but modify the behavior.

Lastly, we could potentially expand the progressUpdate object to include another field(s) which would be the append values. If those are set, we append, otherwise we just set the progress to the given value.

The last option seems like it may be the easiest to code and groc as a user. It avoids extra URLs, different progress modes, etc. Just a tiny change to the progress type and to the aggregator logic handling the updates.

**Comment by johnSchnake** [comment]
So the data type would look like this then:
```
{
# Existing values; used if the plugin wants to report things on its own
total tests to run
total pass
total fail
total skip
list of failed tests

# Existing values; used in either case
last msg

# New values; used to just inform of incremental progress. Will not overwrite totals if using these fields.
appendToTotals: true (in case they set the totals at the start and want to just send progress of results without double counting results)
appendPass: 3
appendFailures [test1, test2]
appendSkips 1
}
```
So the last 4 fields would be optional and for the e2e plugin may even be the default. Then the aggregator is responsible for just appending those values to a running tally.

So a plugin now could just send a series of one-off messages that get aggregated into a useful whole.
