### ISSUE TITLE
Add collecting and viewing of pod failures

### ISSUE THREAD

**Issue by bemeyert** [vmware-tanzu/sonobuoy#1525]
**View pod failures**
I like to be able to view errors/failures which happened in pods.

Currently whenever a failure happens in a Sonobuoy run we have to find the pod in which the error happened and get the logs from the container. We could redirect STDERR with `2>&1`. But that would "break" the output (e.g. invalid JSON).

This is a bit tedious, especially when running Sonobuoy unattended (e.g. nightly builds). We must then leave the Sonobuoy namespace until we are able to retrieve the logs. Only then we can remove the Sonobuoy namespace.
With a 'get-logs/get-errors' command, we could handle everything in the pipeline. E.g. Sonobuoy fails, we retrieve the errors and delete the namespace.

Currently we use 0.54.0, since we didn't have the time yet to adjust to 0.55.0.

**Comment by johnSchnake** [comment]
Is it accurate that this covers your use case:
 - a pod starts
 - a pod outputs something to stderr
 - pod exits non-zero status

Is the 3rd point necessary, or in your case is it not actually exiting? Just trying to formulate the test case to work on to fix this.

When the pod exits non-zero the aggregator should realize it and mark it as a failure. It gets the failing pod msg from the API info on the container.

I thought kubectl logs and sonobuoy logs both got stdout and stderr, thats not the case? I've never had a situation that made it clear I guess.

**Comment by bemeyert** [comment]
@johnSchnake It all works as it should with `sonobuoy logs`, STDOUT/STDERR all there. So "mea culpa". It was a severe case of RTFM on my side. Closing this one.
