### ISSUE TITLE
can not pull image from china: docker pull k8s.gcr.io/conformance:v1.22.1

### ISSUE THREAD

**Issue by dalei2019** [vmware-tanzu/sonobuoy#1535]
Hi teams:

I am trying to use sonobuoy to test the k8s cluster built with kubeadm.

During the test startup process, I got stuck in the image pull.

I tried to pull the mirror separately and reported the following error.

Is there a good way to download this mirror image in China?

code: 
```
# ./sonobuoy images
INFO[0000] e2e image to be used: k8s.gcr.io/conformance:v1.22.1
INFO[0000] Pulling image: k8s.gcr.io/conformance:v1.22.1 ...
ERRO[0031] failed with following error after 1 retries:
ERRO[0031] Error response from daemon: Get "http://k8s.gcr.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

```

**Comment by dalei2019** [comment]
How can list all images that need for run test .
I try this :

1. set image conf 
```
cat <<EOF > conformance-image-config.yaml

dockerLibraryRegistry: my.harb.com/private/k8s.gcr.io
EOF
```
2. run test
```
./sonobuoy run --mode=certified-conformance --sonobuoy-image my.harb.com/private/sonobuoy/sonobuoy:v0.55.1 --e2e-repo-config conformance-image-config.yaml
```
3. and find this in log
```
Back-off pulling image "k8s.gcr.io/e2e-test-images/busybox:1.29-1"

```

It seems that the mirror is not downloaded from a private source.



my question:

1. How to get a list of all the mirrors to be downloaded?

2. How to set sonobuoy to automatically use our private mirror for testing?

Hope someone can provide some help, I have spent 4 days on starting the test...

**Comment by johnSchnake** [comment]
Sorry for the frustration; airgap (and airgap-like) e2e testing is a thorn in everyones side.

Most likely, that image is referencing a different named registry and not `dockerLibraryRegistry`. Let me look a few things up and get you that extra info.

**Comment by johnSchnake** [comment]
Here is the current registry list you can fill out: https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/test/utils/image/manifest.go#L32-L44

You can see that busybox used the `promoterE2eRegistry`, not the `dockerLibraryRegistry`

I havent used this yet but it looks like other folks got tired of the multiple-registry overwriting too and made this issue https://github.com/kubernetes/kubernetes/pull/93510 which seems like you can set `--plugin.env=e2e.KUBE_TEST_REPO=<your registry>` and it will just assume that registry for every image.

Hope these bits help. Feel free to reopen if you have more questions.
