### ISSUE TITLE
Aggregator permissions issue?

### ISSUE THREAD

**Issue by johnSchnake** [vmware-tanzu/sonobuoy#1536]
Trying to utilize the new aggregator permissions flag:

```
$ sonobuoy run --aggregator-permissions=namespaced --mode=quick

INFO[0000] create request issued                         name=sonobuoy namespace= resource=namespaces
INFO[0000] create request issued                         name=sonobuoy-serviceaccount namespace=sonobuoy resource=serviceaccounts
ERRO[0000] error attempting to run sonobuoy: failed to create object: failed to create API resource sonobuoy-serviceaccount-sonobuoy: the server does not allow this method on the requested resource
```

We did gen tests but may not have actually tried runs. Need to dive in; probably a small change to what the template does in the namespaced option.

Using gen, I think the issue is that even though we change the `kind` of the role, `roleref` still shows this:
```
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
```
so we probably just need to adjust that as well.

@NikhilSharmaWe

**Comment by NikhilSharmaWe** [comment]
@johnSchnake 
**Confirming**: So we just need to change kind to Rolebinding in [here(https://github.com/NikhilSharmaWe/sonobuoy/blob/cdf69c82ff167fee39dd671c0e683639bfc0829e/test/integration/testdata/gen-aggregator-permissions-namespaced.golden#L23)

**Comment by johnSchnake** [comment]
No there are numerous issues with the feature that will have to be corrected.
 - dont create the namespace
 - role/binding have a namespace label (why?) but are cluster-wide since they are not just set as the metadata.namespace
 - namespaced roles cant have non-resource URLs set
 - when running with those limited permissions, most (all?) of the queries will fail and currently sonobuoy handles that very poorly causing nothing to work.

I'm going to take this one up myself since it is relatively extensive. These changes in the template are also so wonky that I think it is time we abandon the template in general and turn it into go code itself. Thats a bit tedious but will be much nicer to read and maintain with all of these options we've added.

**Comment by johnSchnake** [comment]
Currently all the `gen` issues are fixed but we are left with a busted run due to the inability to read nodes. Will discuss this on the originating issue #1470

**Comment by johnSchnake** [comment]
Closing this issue since it doesn't add much else now.
