### ISSUE TITLE
Running Sonobuoy with custom labels and annotations for namespaces

### ISSUE THREAD

**Issue by johnqa** [vmware-tanzu/sonobuoy#1538]
Currently I am trying to run Sonobuoy on a Rancher cluster with OTA Gatekeeper enabled with some restrictions regarding the existence of certain labels and annotations.

Executing in such environment is not possible, as the namespaces created by e2e tests/plugin are not coming with these labels and annotations and I am not aware of any way of adding them.

Best Regards,
John

**Comment by johnSchnake** [comment]
Sonobuoy provides a way for our own pods/namespace to be labeled/annotated (you can use `sonobuoy gen` and modify output as desired and plugins can be tweaked via their definition which can specify podspec details).

However, if this is in relationship to the namespaces/pods/etc that the e2e plugin itself creates then that will have to be taken up as an upstream issue. You may want to reach out to #sig-testing and see if there is some workaround that I'm not aware of.
