### ISSUE TITLE
Hunch: WSL testing of sonobuoy client might be necessary?

### ISSUE THREAD

**Issue by jayunit100** [vmware-tanzu/sonobuoy#1543]
**What steps did you take and what happened:**

We were just using sonobuoy 0.55 on a customer site and using 

`sonobuoy run --plugin e2e --e2e-focus="Volume" --e2e-skip="Disruptive|Slow|6"`

Resulted in ALL TESTS being skipped when run from a WSL terminal, but not when being run from other terminals.

**What did you expect to happen:**

the `e2e-skip` flag would not skip all tests...

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Sonobuoy version: 0.55

**Comment by johnSchnake** [comment]
Can you give me the output of `sonobuoy gen --plugin e2e --e2e-focus="Volume" --e2e-skip="Disruptive|Slow|6"`?

If this occurs as described, I'm assuming its just WSL quoting is wonky? I'm very curious what `sonobuoy` got as the flag argument in this case. Once we get the argument it doesn't ever get processed via the terminal again, so it has to be on the input side.
