### ISSUE TITLE
sonobuoy images command error

### ISSUE THREAD

**Issue by zzzkl** [vmware-tanzu/sonobuoy#1546]
**What steps did you take and what happened:**
exec **sonobuoy images --level trace**

get this error log: 

> [root@RqiNodeUat08 kbuser]# sonobuoy images --level trace
TRAC[0000] Invoked command images with args [] and flags [level=trace]
INFO[0000] e2e image to be used: k8s.gcr.io/conformance:v1.23.0
DEBU[0000] Running: /bin/docker [docker inspect --type=image k8s.gcr.io/conformance:v1.23.0]
DEBU[0000] Image: k8s.gcr.io/conformance:v1.23.0 present locally
DEBU[0000] Running: /bin/docker [docker run --rm k8s.gcr.io/conformance:v1.23.0 e2e.test --list-images]
ERRO[0001] unable to collect images of plugins: failed to gather test images from e2e image: exit status 1  trace="exit status 1\nfailed to gather test images from e2e image\ngithub.com/vmware-tanzu/sonobuoy/cmd/sonobuoy/app.collectPluginsImages\n\t/home/runner/work/sonobuoy/sonobuoy/cmd/sonobuoy/app/images.go:426\ngithub.com/vmware-tanzu/sonobuoy/cmd/sonobuoy/app.listImages\n\t/home/runner/work/sonobuoy/sonobuoy/cmd/sonobuoy/app/images.go:257\ngithub.com/vmware-tanzu/sonobuoy/cmd/sonobuoy/app.NewCmdImages.func1\n\t/home/runner/work/sonobuoy/sonobuoy/cmd/sonobuoy/app/images.go:73\ngithub.com/spf13/cobra.(*Command).execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914\ngithub.com/spf13/cobra.(*Command).Execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864\nmain.main\n\t/home/runner/work/sonobuoy/sonobuoy/main.go:27\nruntime.main\n\t/opt/hostedtoolcache/go/1.16.10/x64/src/runtime/proc.go:225\nruntime.goexit\n\t/opt/hostedtoolcache/go/1.16.10/x64/src/runtime/asm_amd64.s:1371\nunable to collect images of plugins\ngithub.com/vmware-tanzu/sonobuoy/cmd/sonobuoy/app.listImages\n\t/home/runner/work/sonobuoy/sonobuoy/cmd/sonobuoy/app/images.go:259\ngithub.com/vmware-tanzu/sonobuoy/cmd/sonobuoy/app.NewCmdImages.func1\n\t/home/runner/work/sonobuoy/sonobuoy/cmd/sonobuoy/app/images.go:73\ngithub.com/spf13/cobra.(*Command).execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914\ngithub.com/spf13/cobra.(*Command).Execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864\nmain.main\n\t/home/runner/work/sonobuoy/sonobuoy/main.go:27\nruntime.main\n\t/opt/hostedtoolcache/go/1.16.10/x64/src/runtime/proc.go:225\nruntime.goexit\n\t/opt/hostedtoolcache/go/1.16.10/x64/src/runtime/asm_amd64.s:1371"

**What did you expect to happen:**
list the e2e test images

**Anything else you would like to add:**

**Environment:**

- Sonobuoy version: v0.55.1
- Kubernetes version: (use `kubectl version`): v1.23.0
- Kubernetes installer & version: kubeadm v1.23.0
- Cloud provider or hardware configuration: 
- OS (e.g. from `/etc/os-release`): centos7
- Sonobuoy tarball (which contains * below)

**Comment by johnSchnake** [comment]
```
➜   sonobuoy images --kubernetes-version v1.23.0
INFO[0000] e2e image to be used: k8s.gcr.io/conformance:v1.23.0
INFO[0000] Pulling image: k8s.gcr.io/conformance:v1.23.0 ...
ERRO[0007] unable to collect images of plugins: failed to gather test images from e2e image: exit status 1
➜  sonobuoy images --kubernetes-version v1.22.0
INFO[0000] e2e image to be used: k8s.gcr.io/conformance:v1.22.0
INFO[0000] Pulling image: k8s.gcr.io/conformance:v1.22.0 ...
ERRO[0009] unable to collect images of plugins: failed to gather test images from e2e image: exit status 1
➜  sonobuoy images --kubernetes-version v1.21.0
INFO[0000] e2e image to be used: k8s.gcr.io/conformance:v1.21.0
INFO[0000] Pulling image: k8s.gcr.io/conformance:v1.21.0 ...
gcr.io/authenticated-image-pulling/alpine:3.7
gcr.io/authenticated-image-pulling/windows-nanoserver:v1
...
...
```

Seems to be an issue starting with v1.22.0; I'll investigate.

**Comment by johnSchnake** [comment]
When debugging I get that the conformance image returned:
```
2021/12/15 17:01:00 failed to create log file /tmp/results/e2e.log: open /tmp/results/e2e.log: no such file or directory
```
It shouldn't be trying to do that _at all_ since its just trying to output the images.

This seems related to an upstream PR about this though; someone was trying to run the conformance image just in docker rather than via sonobuoy and it assumed it had that results directory mounted (but it wasnt mounted the way they invoked it).

A fix just went in for that but we need to mitigate that here; will have to see what changed from v1.21 and v1.22 to cause it though.

**Comment by johnSchnake** [comment]
I modified the code to mount the pwd there and see what happens: it looks like they changed the way the image works and now `kubeconformance` is invoked and the entire test suite is trying to run:

```
➜  ~ docker ps
CONTAINER ID   IMAGE                            COMMAND                  CREATED              STATUS              PORTS                       NAMES
8b3163fe566d   k8s.gcr.io/conformance:v1.23.0   "kubeconformance e2e…"   About a minute ago   Up About a minute                               objective_elgamal
➜  ~ docker logs 8b3163fe566d
2021/12/15 17:15:28 Running command:
Command env: []
Run from directory:
Executable path: /usr/local/bin/ginkgo
Args (comma-delimited): /usr/local/bin/ginkgo,--focus=\[Conformance\],--skip=,--noColor=true,/usr/local/bin/e2e.test,--,--disable-log-dump,--repo-root=/kubernetes,--provider=local,--report-dir=/tmp/results,--kubeconfig=
2021/12/15 17:15:28 Now listening for interrupts
```

You can see that the `--list-images` flag isn't visible at all in the args.

**Comment by johnSchnake** [comment]
Fix incoming. By setting the entrypoint I was able to get the images from v1.22 and v1.23.

**Comment by johnSchnake** [comment]
Thanks for this bug report @zzzkl !

**Comment by sheltonsuen** [comment]
Glad to see the fix here,  is there anyway to workaround this for now?

**Comment by johnSchnake** [comment]
If you need an official release you'll just have to wait for the next one (probably just after the new year with the holidays).

If you just need it for yourself, I'd just grab main and run go install to use the latest version from the main branch.

**Comment by sheltonsuen** [comment]
> If you need an official release you'll just have to wait for the next one (probably just after the new year with the holidays).
> 
> If you just need it for yourself, I'd just grab main and run go install to use the latest version from the main branch.

Aha, never mind, I’ll try to build locally, thanks for the reply
