### ISSUE TITLE
Document `sonobuoy query`

### ISSUE THREAD

**Issue by johnSchnake** [vmware-tanzu/sonobuoy#1558]
New refactoring actually resulted in a new command that si useful and honestly kind of fun to use. We need its own documentation page for this IMO or maybe a tiny blog post.

**Comment by NikhilSharmaWe** [comment]
@johnSchnake I would like to work on it, could you please provide more info it.

**Comment by johnSchnake** [comment]
I'm happy to have you take a crack at it, but since this is a documentation issue, providing the info in detail _is_ the task more or less.

I'm happy to collaborate though; if you want to put up a first draft and I can edit/modify to make sure it is consistent with our other docs.

Just get the version of Sonobuoy from `main` (just build from main via `go install`) and have a local cluster up and try out `sonobuoy query` and look at `sonobuoy query -h`

The gist is that these queries were run from the aggregator (and still are) but now you can run them by themselves locally. You don't have to even run sonobuoy or bother launching pods and waiting for processing etc. Just run `sonobuoy query`.

I look forward to seeing your draft! How long do you think it will take for you to put up a draft? It doesn't have to be a large page but tinker with the command yourself and think about how you would describe the use of the command to someone and what tips they should know or pitfalls to avoid.

**Comment by NikhilSharmaWe** [comment]
@johnSchnake https://hashnode.com/preview/61ca9c505e8b9423aa068647
- As I don't have much info about the command, this might be not very accurate and detailed.

**Comment by johnSchnake** [comment]
If you can put it up as a PR I can comment on the sections/lines but in general it looks pretty great.

A few notes:
 - The point of adding the `--config` option isn't anything about `sonobuoy run` options since this doesn't involve running any pods. However, the config object also includes query options. For now you can just state that, but I think the query options themselves are also pretty poorly documented right now (I could be wrong, but I dont recall seeing docs for those).
 - I wouldn't spend so much time talking about the time/message/level since thats all pretty normal logging info. You can say that the logs are generated via logrus (https://github.com/sirupsen/logrus) since they may already be familiar with that format or can look there at source code if curious about specifics
 
Otherwise, small nits in writing but we can get those when its in a PR.

I also loved the screenshot, I would just advise cropping out your taskbar at the bottom and I'd increase the font size a bit.

**Comment by NikhilSharmaWe** [comment]
@johnSchnake where should I add the content in the repo for making a PR.

**Comment by NikhilSharmaWe** [comment]
@johnSchnake How can I put this blogS content as a PR ?

**Comment by NikhilSharmaWe** [comment]
@johnSchnake where should I add the content in the repo for making a PR.

**Comment by johnSchnake** [comment]
The text is in a markdown format that gets consumed by the site tools; see files in https://github.com/vmware-tanzu/sonobuoy/tree/main/site/content/docs/main and copy the format.

For the image, https://github.com/vmware-tanzu/sonobuoy/tree/main/site/content/docs/main/img
