### ISSUE TITLE
Document single e2e-repo support

### ISSUE THREAD

**Issue by johnSchnake** [vmware-tanzu/sonobuoy#1559]
See #1557; a few pages in docs may need updated to showcase this. It doesn't need its own page though. Airgap and e2e pages though will need it I'm sure.

**Comment by johnSchnake** [comment]
@NikhilSharmaWe if you wanted a hand at updating docs (you offered to write a whole new page on another ticket) then this may be a bit easier since it is just editing a few pages. Let me know if you want to try this instead of the other one.

**Comment by NikhilSharmaWe** [comment]
@johnSchnake I would like to work on it.

**Comment by johnSchnake** [comment]
Trying out the feature is a bit frustrating since it requires pushing/pulling images to different repos and running the e2e tests.

However, you could try and just set the env var to some non-sense value and see if the tests try and use that bogus repo as expected.

Once you try it out and see that it is working, try and patch the documentation. Let me know if you run into specific issues.

**Comment by NikhilSharmaWe** [comment]
@johnSchnake I tried to open the latest version of sonobuoy app `v0.56.0` but when I open it, it says that device is not applicable.
This my device specification : 
```
Device name	DESKTOP-ISNGT7P
Processor	Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz   2.71 GHz
Installed RAM	8.00 GB (7.88 GB usable)
Device ID	68E9F59B-4AA1-4DE6-91B9-CBEA08A5C61E
Product ID	00330-50195-54949-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display
```
Windows 10 Pro.

Although I have understood a little about what new function of environment variable `KUBE_TEST_REPO` is to be added.
