### ISSUE TITLE
Document aggregator permissions

### ISSUE THREAD

**Issue by johnSchnake** [vmware-tanzu/sonobuoy#1569]
We now have 3: clusterAdmin, clusterRead, and namespaceAdmin (previously namespaced)

We need to make a docs page to describe them and the motivations/use cases for having them at all.

**Comment by NikhilSharmaWe** [comment]
@johnSchnake I would like to work on it.

**Comment by johnSchnake** [comment]
👍 Sounds great; just like the other doc PRs you put up:
 - put it under the 'main' set of docs, not a certain version (when we cut a new version it will get put there from now on)
 - Put up the PR for me to review, I'll help you wrap it up
 - Make sure it links to some main page. I think this could even go under the main README under known issues (e.g. if you have an issue with permissions in your cluster but you still want to run Sonobuoy ...). Just know that editing the readme is a bit different than other doc pages. You need to edit the README.md thats in the root of the project, not the README.md thats in the docs. Then run the `./scripts/sync_readme.sh` script (I think thats the name, I could be off slightly). Its just weird because the README gets used by Github and the docs site, and the links have to be formatted differently for each.

**Comment by NikhilSharmaWe** [comment]
@johnSchnake This is about the feature we added [here](https://github.com/vmware-tanzu/sonobuoy/pull/1472). Looking forward writing document on it. 

Thanks again

**Comment by johnSchnake** [comment]
Correct; theres now:
 - clusterAdmin
 - clusterRead
 - namespaceAdmin (you had added it as namespaced, I changed the name after it got fixed up and the others were added. Just makes it more consistent).

- clusterAdmin is the default. Able to do pretty much everything on everything. Most of these are required for the e2e conformance tests to work since they create/destroy namespaces, pods, etc etc
- namespaceAdmin is just ability to do CRUD ops in a single namespace. Sonobuoy does not create the namespace so it needs to already exist and you have to run `--skip-preflight` to avoid Sonobuoy complaining about that. e2e tests WILL NOT work in this mode, they won't even start because it has startup logic that requires looking in kube-system and checking nodes. Daemonsets will also not work in this mode because we monitor them in a way that we require `GET` on `/nodes` so that we know which nodes were responding with results. Since we have NO cluster permissions, we can't get nodes, so we can't know which results to get or wait for, so we just ignore daemonsets.
- clusterRead was a compromise between those two. Adds ability to GET any resource from the API so that the sonobuoy queries work OK, we are able to get nodes so daemonsets run fine, and e2e tests can _technically_ start. We can't create namespaces so e2e tests can't run in this mode in any useful manner either. However, this may be a more reasonable mode to run less intrusive, custom plugins in. In this mode we don't create the namespace either so it has to be created first and sonobuoy run with the `--skip-preflight` flag.

Let me know if you have other questions about the feature.
