### ISSUE TITLE
Unintuitive naming for ProgressUpdate fields

### ISSUE THREAD

**Issue by johnSchnake** [vmware-tanzu/sonobuoy#1591]
When trying to code with the ProgressUpdate type I (who was the one who wrote the type!) was confused because of the naming/implementation.

When we consider the e2e plugin, it reports failing tests, completed, at total. The confusing thing is that failing tests are NOT counted in with the `completed`. But the skipped tests are. So its really a passed+skipped or non-failing/completed.

You can see this in how we report the numbers on `sonobuoy status`, we have to add the failing to the completed.

This caused an issue because in another implementation (updates while in parallel mode) I had forgotten this and so I was double counting tests (failing were counted in completed).

All of this is to say: we need more documentation about that. Ideally we would fix it/change the type naming. However, being implemented in numerous e2e versions takes precedent and so I think we just need to smooth it out for future users.

**Comment by NikhilSharmaWe** [comment]
@johnSchnake I would like to work on the documentation. Please inform if I can help in it and also elaborate on where we need these changes and how can I research more for explaining the users more thoroughly.
