### ISSUE TITLE
Sonobuoy delete does not remove all namespaces

### ISSUE THREAD

**Issue by mauricewittek** [vmware-tanzu/sonobuoy#1593]
I'm running sonobuoy on all of our clusters once a day with a subset of the e2e conformance tests. After retrieving the test results, I use `sonobuoy delete --wait` to clean up the resources created during the tests.

However, after running the tests for a few days now I noticed that on almost all of our clusters (~100) some of the test namespace (dns-4711, proxy-0815, kubectl-1234) were not deleted. 

Environment:

Sonobuoy version: 0.55.0
Kubernetes version: (use kubectl version): 1.20.11

If you need any additional information or logs please let me know.

**Comment by johnSchnake** [comment]
Yes, thats just an issue with the cleanup logic of the k8s code.

Sonobuoy can handle deleting those if you just provide the `--all` flag (https://sonobuoy.io/docs/v0.55.1/#leaked-end-to-end-namespaces)

We don't do that by default in case you are debugging older runs or running other e2e tests simultaneously.

Let me know if you run into any other problems.
