### ISSUE TITLE
Darwin arm64 builds

### ISSUE THREAD

**Issue by palnabarun** [vmware-tanzu/sonobuoy#1614]
**Describe the solution you'd like**

I would like darwin-arm64 builds of Sonobuoy as part of the official releases.

**Anything else you would like to add:**

I noticed that the goreleaser config explicitly ignores building darwin-arm64 variants. Is that intentional? Is there a technical blocker? 

https://github.com/vmware-tanzu/sonobuoy/blob/c7e914ce8dc88d79edfdcc25a3e9ce89084a544d/.goreleaser.yml#L18-L19

If needed, I am happy to test the binary locally on my machine.

**Environment:**

Not Applicable

**Comment by johnSchnake** [comment]
Thanks for the issue.

So apparently Go just started supporting darwin/arm64 lately; totally on board to support it. I would need you to help test that it works as expected though.

You can just do a `GOOS=darwin GOARCH=arm64 go install; sonobuoy gen` to try it out. If it works would you mind putting up the PR to update goreleaser?

**Comment by johnSchnake** [comment]
I'm working on releasing today by the way. If you can confirm, great. Otherwise there shouldn't be any harm in just adding it anyways and we will work it out since its new to golang anyways.

**Comment by palnabarun** [comment]
Thank John! Let me test and get back to you.

Do you need me to run any other tests?

**Comment by palnabarun** [comment]
`GOOS=darwin GOARCH=arm64 go install; sonobuoy gen` works on my machine!
