### ISSUE TITLE
ARM images for Sonobuoy

### ISSUE THREAD

**Issue by johnSchnake** [vmware-tanzu/sonobuoy#1627]
User @fish in #sonobuoy had requested ARM images at some point for Sonobuoy so that you could run on Raspberry Pis. Not unreasonable since k8s supports it and we want to support k8s :)

**Comment by NikhilSharmaWe** [comment]
@johnSchnake What kind of images does Sonobuoy supports currently ? 

I would like to collaborate for adding this enhancement, please inform if I can help in anyway.

**Comment by johnSchnake** [comment]
We currently build for Windows and Linux, including linux/arm64; I'm assuming the requesting user needed armv6 or v7?

(Note that we build the binary for many more os/arch, that is trivial with Go.)

The biggest hurdle for us historically on ARM has been that we dont readily have arm devices on which to test and I'm not sure about virtualization for arm.

At some point we tried to remove arm support entirely but some people in the community did say they use it and we just took a hands off approach and said we'd publish it but relied on the community to report issues on that arch since we weren't testing it ourselves.

**Comment by johnSchnake** [comment]
You can look at the os/arch supported here https://hub.docker.com/layers/sonobuoy/sonobuoy/main/images/sha256-e49fd131e727455e548efbcb0e4e57140a6751f1e46017d82fa0d3dce6bd2a61?context=explore

**Comment by johnSchnake** [comment]
https://kubernetes.io/releases/download/ shows the k8s build versions which includes an `arm` and `arm64`.

GOOS supports an `arm` option which is a 32bit and that aligns with what the original post was regarding raspberry pi (which also is just 32bit).

We can try adding that but we would just be depending on the community for feedback.

For the time being I'm not going to pick this up but wait someone with some arm systems to reengage. I can assist but then we can get confirmation of functionality at that time.
