### ISSUE TITLE
namespaceAdmin: Enable running in namespaces where Resource Quotas are set

### ISSUE THREAD

**Issue by tanmay-g** [vmware-tanzu/sonobuoy#1651]
**Describe the solution you'd like**
Usage of the namespaceAdmin mode allows running in an existing namespace. 

The [kubernetes docs](https://kubernetes.io/docs/concepts/policy/resource-quotas/) state:

> If quota is enabled in a namespace for compute resources like cpu and memory, users must specify requests or limits for those values; otherwise, the quota system may reject pod creation.

However, currently sonobuoy doesn't seem to have a way to define its resource requests and limits.
Accordingly, when attempting to run in a namespace with defined resource quotas, the following error is seen:
```
./sonobuoy run --skip-preflight --aggregator-permissions namespaceAdmin ...
[...]
time="2022-03-22T09:00:43Z" level=error msg="error attempting to run sonobuoy: failed to create object: failed to create API resource sonobuoy: pods \"sonobuoy\" is forbidden: failed quota: cpu-ram-ephemeral-quota: must specify limits.cpu,limits.memory,requests.cpu,requests.memory"
```

Possible solutions could be to set default resource requests & limits for the sonobuoy pod, or alternatively, allow the user to toggle setting the defaults and/or specify the values themselves.

**Environment:**

- Sonobuoy version: v0.56.2
- Kubernetes version: (use `kubectl version`): v1.21.5
- Kubernetes installer & version: Varies (incl e.g. vanilla & OpenShift)
- Cloud provider or hardware configuration: Varies
- OS (e.g. from `/etc/os-release`): Varies

**Comment by johnSchnake** [comment]
> However, currently sonobuoy doesn't seem to have a way to define its resource requests and limits.

This is partially correct; there isn't a way to do it from the CLI.

However, despite being a unique case we can support this by using the `sonobuoy gen` workflow.

Simply use `sonobuoy gen... > runconfig.yaml` with all of your options/flags set. Then manually edit the aggregator pod definition in there. Likewise, you can set all of your plugins' podspecs as well if necessary.

Does that satisfy your use case? I'm not certain that the combination of namespaceAdmin permissions and ResourceQuotas is common enough to necessitate any sort of built-in option at this time.

**Comment by tanmay-g** [comment]
> Simply use `sonobuoy gen... > runconfig.yaml` with all of your options/flags set. Then manually edit the aggregator pod definition in there. Likewise, you can set all of your plugins' podspecs as well if necessary.

That allows setting the resources for the aggregator, but not for the plugin pods' `sonobuoy-worker` container (the resources for the custom container can be set in the plugin definition).

We ended up having to modify `CreateWorkerContainerDefintion` to set the resources for the worker, and since the source had to be changed anyway, the aggregator's resources were also set in `generateAggregatorAndService`.

Since you have indicated that you don't see this fitting a built-in option, we'll keep this change in our fork for now.
