### ISSUE TITLE
namespaceAdmin: Allow running with a custom service account

### ISSUE THREAD

**Issue by tanmay-g** [vmware-tanzu/sonobuoy#1653]
**Describe the solution you'd like**

We would like to be able run sonobuoy in cases where we are restricted to a namespace, don't have permissions to create RBAC resources, and are so required to use a pre-created serviceaccount.

That would mean sonobuoy would need to run with a serviceaccount whose name is provided by the user, and sonobuoy would not itself attempt to create any RBAC resources.

For our internal usage, we already have a [fork which contains this change](https://github.com/vmware-tanzu/sonobuoy/compare/main...nokia:customServiceAccount), so if this proposal sounds reasonable, we could open a new Pull request to discuss specifics.

The version built from the fork is triggered in the mentioned restricted mode with:
```
--skip-preflight --aggregator-permissions namespaceAdmin --rbac Disable --service-account <existing_serviceaccount_name>
```

**Environment:**

- Sonobuoy version: v0.56.2
- Kubernetes version: (use `kubectl version`): v1.21.5
- Kubernetes installer & version: Varies
- Cloud provider or hardware configuration: Varies
- OS (e.g. from `/etc/os-release`): Varies

**Comment by johnSchnake** [comment]
Hey @tanmay-g, sounds good to me. It's narrowly scoped and you've already put the work in it looks like. If you put up a PR I'm happy to review it.
