### ISSUE TITLE
Switch to projects.registry.vmware.com registry by default

### ISSUE THREAD

**Issue by z0rc** [vmware-tanzu/sonobuoy#1680]
**Describe the solution you'd like**
Running sonobuoy on medium sized clusters (tens of nodes) often triggers ErrImagePull on `sonobuoy/sonobuoy` and `sonobuoy/systemd-logs` containers from sonobuoy's DaemonSet, due to Docker Hub rate limit. I'm aware about https://github.com/vmware-tanzu/sonobuoy#docker-hub-rate-limit (also it doesn't cover `--systemd-logs-image` argument), but it's inconvenient and requires for me to track systemd-logs image version in addition to sonobuoy itself.

It would be much preferable to pull sonobuoy containers from official Harbor by default, instead of using Docker Hub.

**Anything else you would like to add:**
Nope

**Environment:**

- Sonobuoy version: v0.56.2
- Kubernetes version: (use `kubectl version`): 1.22.6
- Kubernetes installer & version: EKS 1.22
- Cloud provider or hardware configuration: AWS EKS
- OS (e.g. from `/etc/os-release`): Bottlerocket OS

**Comment by johnSchnake** [comment]
I agree. Not a big reason to stay on dockerhub; we currently support both anyways. Need to just update the values for the default plugins.

We could try and phase it in but I think thats honestly a bigger a headache than necessary. These are just default values for the plugins and can be overridden if necessary, so we won't hard-block anyone if we change it. Most likely, we just help others avoid that issue.

**Comment by z0rc** [comment]
Not stale.

**Comment by z0rc** [comment]
That's a shame.
