### ISSUE TITLE
Incomplete test status and failure to retrieve test results

### ISSUE THREAD

**Issue by jcstanaway** [vmware-tanzu/sonobuoy#1682]
**What steps did you take and what happened:**

In our automation, we execute:

```
sonobuoy delete --wait
sonobuoy run --e2e-focus=\[Conformance\] --e2e-skip=\[Slow\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]|(should\sbe\sable\sto\schange\sthe\stype\sfrom\sExternalName\sto\sNodePort)|(should\sbe\sable\sto\screate\sa\sfunctioning\sNodePort\sservice)|(should\shave\ssession\saffinity\swork\sfor\sNodePort\sservice)|(should\shave\ssession\saffinity\stimeout\swork\sfor\sNodePort\sservice)|(should\ssupport\sOIDC\sdiscovery\sof\sservice\saccount\sissuer)|(should\sbe\sable\sto\sswitch\ssession\saffinity\sfor\sNodePort\sservice) --sonobuoy-image ourmirror.com/docker.io/sonobuoy/sonobuoy:v0.56.1 --kube-conformance-image ourmirror.com/k8s.gcr.io/conformance:v1.21.10 --e2e-repo-config /build/tests/resources/sonobuoy/custom_repo_config.yaml --systemd-logs-image ourmirror.com/gcr.io/heptio-images/sonobuoy-plugin-systemd-logs:latest --plugin-env=e2e.E2E_EXTRA_ARGS=--progress-report-url=http://localhost:8099/progress --non-blocking-taints=workload,node-role.kubernetes.io/master
```

Then we start polling for status waiting for the run to complete using:

```
sonobuoy status --json
```

We eventually get the following status:

```
{'node': 'global',
 'plugin': 'e2e',
 'progress': {'completed': 323,
              'msg': 'Test Suite completed',
              'name': 'e2e',
              'node': 'global',
              'timestamp': '2022-04-21T10:44:13.114513564Z',
              'total': 323},
 'result-counts': None,
 'result-status': '',
 'status': 'complete'}
```

Notice that `status` is `complete`, but `result-counts` and `result-status` have empty values.

We wait 2 minutes to give some time for the the complete result to be generated and then attempt to retrieve the results using:

```
sonobuoy retrieve /config/_sonobuoy_output --filename=2022-04-21_sonobuoy_azure.tar.gz
```

but that fails with:

```
error retrieving results: no valid entries in result
```

We wait and retry `sonobuoy retrieve` several times before failing.

**What did you expect to happen:**

The following output from `sonobuoy status --json`:

```
{'node': 'global',
 'plugin': 'e2e',
 'progress': {'completed': 323,
              'msg': 'Test Suite completed',
              'name': 'e2e',
              'node': 'global',
              'timestamp': '2022-04-22T10:29:03.114081947Z',
              'total': 323},
 'result-counts': {'passed': 323, 'skipped': 5450},
 'result-status': 'passed',
 'status': 'complete'}
```

And no error from `sonobuoy retrieve`.

**Anything else you would like to add:**

This failure does not consistently occur.

We deploy k8s to both AWS and Azure, but this failure only seems to occur in our Azure deployments.

**Environment:**

- Sonobuoy version: 0.56.1
- Kubernetes version: (use `kubectl version`): 1.21.10
- Kubernetes installer & version: custom
- Cloud provider or hardware configuration: Azure
- OS (e.g. from `/etc/os-release`): Rocky Linux 8.5
- Sonobuoy tarball (which contains * below): unavailable - that's part of the issue

**Comment by johnSchnake** [comment]
Thanks for the ticket. I'd love to try and repro on Azure.

I can mention that some things make sense:
 - the progress updates stating the suite is complete comes from the plugin itself. Those counts are independent of the 'result-counts' actually
 - the result-counts are derived from the aggregator applying post-processing on the results actually submitted to the aggregator.

I'd be curious what the output of `sonobuoy logs` when one of these situations occur. It seems like the results have a problem getting sent to the aggregator or there is an error during post-processing. Without more logs (or repro'ing) I can't tell more though but it's a start.

**Comment by jcstanaway** [comment]
We have sonobuoy in this status at the moment. We're checking if there is anything the `sonobuoy logs` that should be redacted. However, we are also seeing:
```
$ sonobuoy status
         PLUGIN     STATUS   RESULT   COUNT                                PROGRESS
            e2e   complete                1   Passed:322, Failed:  1, Remaining:  0
   systemd-logs   complete               12
   systemd-logs    running                1

Sonobuoy is still running. Runs can take 60 minutes or more depending on cluster and plugin configuration.
```
long after sonobuoy should already have completed. It is not clear why sonobuoy is still running or why the systemd-logs plugin reports both completed and running.

We are considering if we should disable the systemd-logs plugin.

**Comment by johnSchnake** [comment]
The systemd-logs plugin is a daemonset so you're seeing that you have 12 instances of it completed, one still running so it looks like a 13 node cluster? I'd look at the daemonset and see if there isn anything useful in its status; presumably it either:
 - ran/finished but its results arent seen
 - wasn't able to run, maybe due to a scheduling/capacity issue

**Comment by johnSchnake** [comment]
I'd be curious why the DS hung; please let me know in case we can better identify that failure mode.

However, if you don't routinely utilize the data from the systemd logs disabling it is a perfectly good option. Just add the `-p e2e` flag to specify you just want the e2e plugin.

**Comment by jcstanaway** [comment]
There should have only been 12 instances. It's a "phoenix" cluster that we deploy from scratch, run various tests (including sonobuoy) and then tear down.

I have the logs from `sonobuoy logs` - what's the best way to provide those? ~20K entries.

**Comment by jcstanaway** [comment]
I wonder if there was an unexpected scaleup resulting in an additional instance, but it went away but sonobuoy was still expecting results from 13 ds pods.

**Comment by jcstanaway** [comment]
Looking through the `sonobuoy logs` it appears that's exactly what happened.

At the beginning of the logs, it reports:

`time="2022-05-04T10:49:51Z" level=info msg="Starting server Expected Results: [{global e2e} {dp-phoenix-az-eastus-etcd-1000000 systemd-logs} {dp-phoenix-az-eastus-etcd-2000000 systemd-logs} {dp-phoenix-az-eastus-etcd-3000000 systemd-logs} {dp-phoenix-az-eastus-master-1000000 systemd-logs} {dp-phoenix-az-eastus-master-2000000 systemd-logs} {dp-phoenix-az-eastus-master-3000000 systemd-logs} {dp-phoenix-az-eastus-worker-default-1000000 systemd-logs} {dp-phoenix-az-eastus-worker-default-1000003 systemd-logs} {dp-phoenix-az-eastus-worker-default-1000005 systemd-logs} {dp-phoenix-az-eastus-worker-default-2000000 systemd-logs} {dp-phoenix-az-eastus-worker-default-2000003 systemd-logs} {dp-phoenix-az-eastus-worker-default-3000001 systemd-logs} {dp-phoenix-az-eastus-worker-default-3000005 systemd-logs}]"`

There are 13 nodes listed there. However dp-phoenix-az-eastus-worker-default-1000005 was on it's way out.

The logs then start a looping process "Waiting up to 10m0s for all pods (need at least 0) in namespace 'kube-system' to be running and ready".

For several minutes, it reports that "171 / 180 pods in namespace 'kube-system' are running and ready" and that pods on dp-phoenix-az-eastus-worker-default-1000005 are not ready.

Eventually, that node is removed and we see:

```
May  4 10:55:03.536: INFO: 171 / 171 pods in namespace 'kube-system' are running and ready (290 seconds elapsed)
May  4 10:55:03.536: INFO: expected 40 pod replicas in namespace 'kube-system', 40 are Running and Ready.
May  4 10:55:03.536: INFO: Waiting up to 5m0s for all daemonsets in namespace 'kube-system' to start
May  4 10:55:03.552: INFO: 12 / 12 pods ready in namespace 'kube-system' in daemonset 'calico-node-nft' (0 seconds elapsed)
May  4 10:55:03.552: INFO: 12 / 12 pods ready in namespace 'kube-system' in daemonset 'here-custom-node-exporter' (0 seconds elapsed)
May  4 10:55:03.552: INFO: 0 / 0 pods ready in namespace 'kube-system' in daemonset 'link-fixer' (0 seconds elapsed)
May  4 10:55:03.552: INFO: 12 / 12 pods ready in namespace 'kube-system' in daemonset 'nmi' (0 seconds elapsed)
May  4 10:55:03.552: INFO: 12 / 12 pods ready in namespace 'kube-system' in daemonset 'node-exporter' (0 seconds elapsed)
May  4 10:55:03.552: INFO: 12 / 12 pods ready in namespace 'kube-system' in daemonset 'node-local-dns-nft' (0 seconds elapsed)
May  4 10:55:03.552: INFO: 12 / 12 pods ready in namespace 'kube-system' in daemonset 'node-problem-detector-dp' (0 seconds elapsed)
May  4 10:55:03.552: INFO: 12 / 12 pods ready in namespace 'kube-system' in daemonset 'prometheus-blackbox-exporter' (0 seconds elapsed)
```

However, sonobuoy continues to wait for results from 13 systemd plugin instances.

Just before running sonobuoy we do execute a scale up/down test, but that test is _supposed_ to block until the scale fully completed before moving on to sonobuoy. So we can investigate why the blocking might not be working.

However, should sonobuoy at some point verify how many systemd-log results it should actually expect? Perhaps after the "waits"?

```
Waiting up to 30m0s for all (but 0) nodes to be schedulable
Waiting up to 10m0s for all pods (need at least 0) in namespace 'kube-system' to be running and ready
Waiting up to 5m0s for all daemonsets in namespace 'kube-system' to start
```

**Comment by jcstanaway** [comment]
Appreciate the insight. We have gone ahead and disabled the systemd-logs plugin as you suggested.
