### ISSUE TITLE
Sonoboy retrieve fails saving on a different path

### ISSUE THREAD

**Issue by betoredhat** [vmware-tanzu/sonobuoy#1689]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Running sonobuoy retrieve fails if the path specified using -f contains a path to a directory.

```
$ sonobuoy retrieve -f /tmp/work/results.tar.gz
error retrieving results: non-zero data ¸ (byte 184) read after tar EOF
$ sonobuoy retrieve 
202205050313_sonobuoy_9e1c1194-9068-4899-b8b2-000c8bb19fd1.tar.gz
$ sonobuoy retrieve -f /tmp/work/results.tar
error retrieving results: non-zero data ¸ (byte 184) read after tar EOF
$ sonobuoy retrieve -f results.tar
results.tar
```

**What did you expect to happen:**
Able to save the results tar ball on a directory different to where the  sonobouy binary  is located

**Environment:**

- Sonobuoy version: v0.56.4

**Comment by johnSchnake** [comment]
👍 thanks for the report. In reproducing this, it is actually just a problem if the directory path doesnt exist:

```
> sonobuoy retrieve
202204281423_sonobuoy_5e4ffa01-f4ea-495e-9dc4-20e962768631.tar.gz
> sonobuoy retrieve -f foo.tar.gz
foo.tar.gz
> sonobuoy retrieve -f ./doesntexist/foo.tar.gz
error retrieving results: non-zero data Ý (byte 221) read after tar EOF
> mkdir exists
> sonobuoy retrieve -f ./exists/foo.tar.gz
exists/foo.tar.gz
```

No reason we shouldn't make that path though; I would have thought we already did.

**Comment by johnSchnake** [comment]
Looking at this further, you _can_ do what you want but in a wonky way.

`sonobuoy retrieve <dir path> -f <filename>` will create the directories for you.

This needs corrected though just to be more predictable.

**Comment by johnSchnake** [comment]
And it makes sense why the error is occurring now. It tries to make the file `<dir doesnt exist>/<file>` which fails for `os.Create` but the method has a defer block that checks we drained the reader. Since we didnt (because of the creation error) it complains.

**Comment by betoredhat** [comment]
@johnSchnake thanks for checking, I think that the issue is happening when using an absolute path.

```
$ ll /tmp/work/
total 0
$ ./sonobuoy retrieve -f /tmp/work/results.tar.gz
error retrieving results: non-zero data u (byte 117) read after tar EOF
$ mkdir report
$ ./sonobuoy retrieve -f report/results.tar.gz
report/results.tar.gz
$ mkdir /home/user/test
$ ./sonobuoy retrieve -f /home/user/test/results.tar.gz
error retrieving results: non-zero data u (byte 117) read after tar EOF
```
