### ISSUE TITLE
Failed to pull image for container e2e within 5m0s. Container is in state ImagePullBackOff

### ISSUE THREAD

**Issue by jepsonhu** [vmware-tanzu/sonobuoy#1706]
Plugin: e2e
Status: failed
Total: 1
Passed: 0
Failed: 1
Skipped: 0

Failed tests:
Failed to pull image for container e2e within 5m0s. Container is in state ImagePullBackOff

Plugin: systemd-logs
Status: failed
Total: 3
Passed: 0
Failed: 3
Skipped: 0

Failed tests:
Failed to pull image for container sonobuoy-worker within 5m0s. Container is in state ErrImagePull
Failed to pull image for container systemd-logs within 5m0s. Container is in state ImagePullBackOff
Failed to pull image for container sonobuoy-worker within 5m0s. Container is in state ErrImagePull

Run Details:
API Server version: v1.20.4
Node health: 3/3 (100%)
Pods health: 122/128 (95%)
Details for failed pods:
beecloud/ffffff-bke-apiserver-demo2-7d57f9f859-rddjj Ready:False: ContainersNotReady: containers with unready status: [bke-apiserver-demo2]
sonobuoy/sonobuoy-e2e-job-4fb0bdf8375d47d3 Ready:False: ContainersNotReady: containers with unready status: [e2e]
sonobuoy/sonobuoy-systemd-logs-daemon-set-a5991355f58743fa-289zt Ready:False: ContainersNotReady: containers with unready status: [systemd-logs sonobuoy-worker]
sonobuoy/sonobuoy-systemd-logs-daemon-set-a5991355f58743fa-86vdd Ready:False: ContainersNotReady: containers with unready status: [systemd-logs sonobuoy-worker]
sonobuoy/sonobuoy-systemd-logs-daemon-set-a5991355f58743fa-jxg5k Ready:False: ContainersNotReady: containers with unready status: [systemd-logs]
zgw-test-channel/ceshi-7b4b56d65b-mg4bc Ready:False: ContainersNotReady: containers with unready status: [zag]
Errors detected in files:
Errors:
674 podlogs/kube-system/traefik-5d99d4964f-v8d54/logs/traefik.txt
282 podlogs/kube-system/trimaran-679f86cffd-fd8pz/logs/trimaran.txt
136 podlogs/kube-system/calico-node-knr5w/logs/calico-node.txt
 45 podlogs/kube-system/coredns-65944cbcb8-8f85x/logs/coredns.txt
 36 podlogs/kube-system/calico-node-v5gq9/logs/calico-node.txt
 26 podlogs/kube-system/trimaran-679f86cffd-fd8pz/logs/load-watcher.txt
 12 podlogs/kube-system/nodelocaldns-x9tfh/logs/node-cache.txt
 11 podlogs/kube-system/nodelocaldns-8xxnj/logs/node-cache.txt
 10 podlogs/kube-system/nodelocaldns-xwhmd/logs/node-cache.txt
  4 podlogs/kube-system/kube-proxy-8phb4/logs/kube-proxy.txt
  3 podlogs/kube-system/calico-node-d5c57/logs/calico-node.txt
  2 podlogs/kube-system/kube-proxy-rclbd/logs/kube-proxy.txt
  2 podlogs/kube-system/kube-controller-manager-master2/logs/kube-controller-manager.txt
  2 podlogs/kube-system/calico-kube-controllers-7fc49b8c4-p49js/logs/calico-kube-controllers.txt
  1 podlogs/kube-system/kube-scheduler-master2/logs/kube-scheduler.txt
  1 podlogs/kube-system/kube-proxy-7dd7v/logs/kube-proxy.txt
  1 podlogs/kube-system/kube-controller-manager-master3/logs/kube-controller-manager.txt
  1 podlogs/kube-system/kube-controller-manager-master1/logs/kube-controller-manager.txt
  1 podlogs/kube-system/kube-apiserver-master1/logs/kube-apiserver.txt
  1 podlogs/kube-system/kube-scheduler-master3/logs/kube-scheduler.txt
Warnings:
4 podlogs/kube-system/kube-scheduler-master3/logs/kube-scheduler.txt
3 podlogs/kube-system/kube-proxy-8phb4/logs/kube-proxy.txt
3 podlogs/kube-system/coredns-65944cbcb8-8f85x/logs/coredns.txt
3 podlogs/kube-system/kube-scheduler-master2/logs/kube-scheduler.txt
2 podlogs/kube-system/kube-controller-manager-master2/logs/kube-controller-manager.txt
1 podlogs/sonobuoy/sonobuoy/logs/kube-sonobuoy.txt
1 podlogs/kube-system/calico-kube-controllers-7fc49b8c4-p49js/logs/calico-kube-controllers.txt
1 podlogs/kube-system/kube-proxy-7dd7v/logs/kube-proxy.txt
1 podlogs/kube-system/kube-proxy-rclbd/logs/kube-proxy.txt

**Comment by johnSchnake** [comment]
Hi 👋 Sorry you're having a problem.

Can you provide more information:
 - output of `sonobuoy version`
 - output of `kubectl version`
 - the command you used to start this run
 - output of `sonobuoy gen <with the same options as above>`

I ran `sonobuoy run -m quick --kubernetes-version=v1.20.4 --wait` without problems on sonobuoy v0.56.4 so all those images exist where they should. The above information will help identify that you're targeting the proper images. After that the question would be whether or not you are in some sort of restricted environment.

It seems very odd since the aggregator and worker containers should be the same image but your info seems like the aggregator worked fine but the workers was causing a problem.

**Comment by johnSchnake** [comment]
Since its been almost 2mo since the original ticket I'm going to assume that you figured out the issue. If you're still having problems, feel free to reopen and provide additional information.
