### ISSUE TITLE
Container e2e is in a terminated state

### ISSUE THREAD

**Issue by little-helper-001** [vmware-tanzu/sonobuoy#1712]
**What steps did you take and what happened:**
Setup a minimal Kubernetes cluster using kubeadm with a single controlplane and single worker node.
Installed Calico.
Installed Sonobuoy to a Client with full access to the cluster.
Run Sonubuoy until it failed with the following error messages.

**What did you expect to happen:**
Successfully return results.

**Anything else you would like to add:**

**Environment:**

- Sonobuoy version: v0.56.6
- Kubernetes version: (use `kubectl version`): 1.23.6
- Kubernetes installer & version: Kubeadm 1.24.0
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`): Rocky Linux 8.5
- Sonobuoy tarball (which contains * below)

See complete terminal output below:
[sonubuoy_fail.txt](https://github.com/vmware-tanzu/sonobuoy/files/8695769/sonubuoy_fail.txt)

**Comment by johnSchnake** [comment]
If you could provide any logs for the e2e or worker containers that would be great. The `--wait` output is helpful to see as things run but it doesn't have the entirety of the info needed to debug a problem.

If you can either look in the tarball under `podlogs...` and/or the output from `sonobuoy logs -p e2e`, that would be helpful.

**Comment by johnSchnake** [comment]
I've confirmed that v0.56.6 of sonobuoy and v1.23.6 k8s on a 2 node cluster like yours works fine, but I'm using a kind cluster.

If its a matter of it failing but only for calico or for kubeadm I'd be very curious why.

**Comment by little-helper-001** [comment]
Thank you for your quick response. Attached you will find the `sonobuoy logs -p e2e`.

[sonobuoy.logs.e2e.txt](https://github.com/vmware-tanzu/sonobuoy/files/8701960/sonobuoy.logs.e2e.txt)

**Comment by johnSchnake** [comment]
It seems odd because the pods read as the phase "RUNNING" but the containers seem to be not ready. You should look into the status of those pods and see if you can fix those and rerun sonobuoy.

**Comment by little-helper-001** [comment]
Thank you for your help. I found the issue and indeed it was not Sonobuoy. I did open the port for Calico in the firewall but forgot to make the rule permanent , so the pods failed after a restart. I works now.
