### ISSUE TITLE
Add a known field in the YAML output format for summary information

### ISSUE THREAD

**Issue by johnSchnake** [vmware-tanzu/sonobuoy#1721]
**Describe the solution you'd like**
A place to store short messages that we want sonobuoy to print regarding a test. The data type has a `details map[string]interface{}` and junit has fields `system-out` and `failure` which we put there.

However, the post-processor sidecar makes it easier to tweak results and add information/context to a result. We _could_ append to failure/system-out but the issue is that those fields (from the e2e results at least) are extremely verbose. We wouldn't usually want to print that all of that data.

In addition, what if the test in question passed but we still want to add some data that may be printed in some context? We need a generic field that Sonobuoy knows is for this sort of user-facing data.

In addition, during `sonobuoy results` should print this data for failures and potentially consider printing the `failure` fields as well (less verbose than the system-out field but maybe give options for this).

**Comment by johnSchnake** [comment]
Going to add this; I think `summary` works well but is often used in other contexts too. I could be more clear and say `shortsummary` or `short` to emphasize that it should be shorter in length.

Going to work on this but I'm open to renaming.

**Comment by 26tanishabanik** [comment]
@johnSchnake , are you still working on this?
