### ISSUE TITLE
Switch from k8s.gcr.io to registry.k8s.io

### ISSUE THREAD

**Issue by z0rc** [vmware-tanzu/sonobuoy#1734]
**Describe the solution you'd like**
Kubernetes project is working on switching to new registry by 1.25 release. See https://github.com/kubernetes/k8s.io/issues/1834 and https://github.com/kubernetes/kubernetes/pull/109938. Sonobuoy should follow this change eventually. There are multiple places in code that reference `k8s.gcr.io` now.

**Anything else you would like to add:**
Announcement at https://groups.google.com/g/kubernetes-sig-testing/c/U7b_im9vRrM/m/7qywJeUTBQAJ.

**Comment by johnSchnake** [comment]
Thanks! 👍 

We will make sure to track this.

**Comment by johnSchnake** [comment]
> We have come to the point where we have a proxy in front of [k8s.gcr.io](http://k8s.gcr.io/) named [registry.k8s.io](http://registry.k8s.io/)...

I wonder if we really need to do anything if they've already put a proxy in front to redirect the important traffic. Investigating. There are lots of threads to read so if someone knows the answer, feel free to point me to it directly.

**Comment by z0rc** [comment]
AFAIK proxy setup will be like this for transition period, but it isn't clear how long this period will last. Nonetheless Kubernetes 1.25 is expected to switch to new registry by default, so I _guess_ old registry will be available for 1-2 releases after 1.25 until it's completely deprecated.

**Comment by johnSchnake** [comment]
Trying to just tinker to be more confident with the change and got this:

```
docker pull registry.k8s.gcr.io/conformance:v1.23.3
Error response from daemon: Get "https://registry.k8s.gcr.io/v2/": x509: certificate is valid for *.googlecode.com, *.cloud.google.com, *.code.google.com, *.codespot.com, *.developers.google.com, *.clients6.googlesource.com, *.googlesource.com, googlesource.com, *.u.googlecode.com, gcr.io, *.gcr.io, pkg.dev, *.pkg.dev, googlecode.com, not registry.k8s.gcr.io
```

Same thing when I tried `skopeo list-tags ...`

Investigating.

**Comment by johnSchnake** [comment]
Tried to just confirm that all the images we expect (all the conformance images) are available in both locations; confirmed via `skopeo list tags...` to each registry and diff'd them. No differences.

Making change 👍
