### ISSUE TITLE
`--mode` ignores `--e2e-skip` silently

### ISSUE THREAD

**Issue by datosh** [vmware-tanzu/sonobuoy#1767]
**What steps did you take and what happened:**

`sonobuoy run --mode certified-conformance --e2e-skip "\[sig-network\]"`

My goal was to temporarily disable some e2e tests in my environment using the `certified-conformance` test suite, because my pipeline was failing, due to a known issue in my tooling.

Sonobuoy ignored the skip value silently.

**What did you expect to happen:**

I exptected the tests specified in `--e2e-skip` to be ignored.

**Anything else you would like to add:**

More explicit documentation or a warning that skip will be ignored when using mode would be helpful as a user.

**Environment:**

- Sonobuoy version: 0.56.4
- Kubernetes version: (use `kubectl version`): 1.23.x
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`): 
- Sonobuoy tarball (which contains * below)

**Comment by johnSchnake** [comment]
I did confirm that the start of the run does give a warning:

```
$ sonobuoy run --mode certified-conformance --e2e-skip "\[sig-network\]"
WARN[0000] mode flag and e2e-focus/skip flags both provided and may cause unintended behavior
```

However, we it does seem like we should just error here. There isn't any use case for doing this, especially since we don't document what Sonobuoy is doing under the hood so even advanced users aren't doing this to get some specific behavior.

**Comment by johnSchnake** [comment]
We can also add some extra info in docs (site or CLI); but even without the doc change, erroring out will prevent any future confusion.

**Comment by datosh** [comment]
Yes, I can confirm the warning as well. Sorry, must have missed that in CI pipeline output.

On the other hand, when using `E2E_SKIP` envar no warning is printed.

**Comment by johnSchnake** [comment]
Thats a good point; the CLI flag is really just setting an env var, but the warning doesnt catch that path.
