### ISSUE TITLE
Issues with a custom plugin not returning results

### ISSUE THREAD

**Issue by johnSchnake** [vmware-tanzu/sonobuoy#1774]
See https://kubernetes.slack.com/archives/C6L3G051C/p1655103763401889?thread_ts=1653988487.029769&cid=C6L3G051C

Problem getting results from a custom plugin.

**Comment by johnSchnake** [comment]
I think the issue is that the done file being written is a directory and not a file. Typically what happens when you want the whole directory is that you tar up the directory and then write the tarfile name as the results.

I think this is a pretty simple enhancement to make though and support listing the directory itself. It would make things more simple for users too.

**Comment by johnSchnake** [comment]
A second issue is that the worker says its waiting for some period of time to allow you to alter the donefile/results.

However, it doesnt seem to re-read the donefile. I tried editing the donefile to point to the junit file and the directory is still being used as the 'results file' instead of the new value.

I'll file a separate issue for that.

**Comment by johnSchnake** [comment]
Confirmed this is the issue in code and in practice; I added a sidecar that would remove the done file and keep it 'missing' for long enough for the sonobuoy-worker to reread it and things worked as expected.

**Comment by oshoval** [comment]
Thanks John, uploading directory works awesome
