### ISSUE TITLE
sonobuoy e2e command error

### ISSUE THREAD

**Issue by weistonedawei** [vmware-tanzu/sonobuoy#1779]
**What steps did you take and what happened:**
`sonobuoy --kubeconfig=config.yaml e2e` returns the following

```
Error: no tests found with given options
Usage:
  sonobuoy e2e [flags]

Flags:
      --context string                    Context in the kubeconfig to use.
  -f, --focus string                      Return tests which match this regular expression
  -h, --help                              help for e2e
  -i, --input string                      Determines the source of the test lists. Can be [online, offline, -]. If '-' is set, tests will be read from stdin. (default "online")
      --kubeconfig Kubeconfig             Path to explicit kubeconfig file. (default )
  -m, --mode string                       Print mode. Can be one of [tags, tagCounts, tests] (default "tests")
  -s, --skip string                       Do not return tests which match this regular expression
      --version ConformanceImageVersion   Use default E2E image, but override the version. Default is 'auto', which will be set to your cluster's version if detected, erroring otherwise. 'ignore' will try version resolution but ignore errors. 'latest' will find the latest dev image/version upstream.

Global Flags:
      --level level   Log level. One of {panic, fatal, error, warn, info, debug, trace} (default info)

ERRO[0001] no tests found with given options
```

**What did you expect to happen:**
A full list of tests as shown in youtubeclip `TGI Kubernetes 183: Sonobuoy`

**Anything else you would like to add:**
Is there a way to have multiple --focus option to narrow down tests to run?

**Environment:**

- Sonobuoy version: 0.56.2, 0.56.8
- Kubernetes version: (use `kubectl version`): 1.21.14
- Kubernetes installer & version: kubeadm 1.21.14
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):  ubuntu 18.04 and wsl2 on windows
- Sonobuoy tarball (which contains * below)

**Comment by johnSchnake** [comment]
I think that version is probably just missing. I'll take a look tomorrow and it's a quick fix if that's it.

**Comment by arrowfeng** [comment]
You can filter multiple test cases by separating the symbols "|", the example is as follows:
``` bash
sonobuoy e2e --focus "CSI mock volume storage capacity exhausted|HostPath should support r/w \[NodeConformance\]"
```
![image](https://user-images.githubusercontent.com/20623365/181491286-4eb073fb-5431-4af4-a85d-b78cce7eff27.png)
