### ISSUE TITLE
Emit web events

### ISSUE THREAD

**Issue by johnSchnake** [vmware-tanzu/sonobuoy#1816]
Event web events throughout the logic of Sonobuoy aggregator and worker. Configurable where to send them.

Eventually the goal would be to be able to subscribe to certain events but it is likely that the emitting would be the same and the filtering would happen at the other end.

Emitting events for starting a run, finishing a run, starting/finishing a plugin, and other status changes such as postprocessing. Potentially even on all progress updates.

**Comment by johnSchnake** [comment]
See https://github.com/vmware-tanzu/sonobuoy/pull/1237

**Comment by 26tanishabanik** [comment]
@johnSchnake , I can see one pull request mentioned in the PR #1237, what else is remaining to do as task?
