### ISSUE TITLE
What ports and protocols are used on master and worker node to run sonobuoy conformance test

### ISSUE THREAD

**Issue by mehulgogri** [vmware-tanzu/sonobuoy#1849]
I have firewall enabled on my kubernetes cluster, due to which I have to manually add ports on both worker and master nodes. 

What ports and protocols are need to be open on master and worker node to run sonobuoy conformance test?

**Comment by franknstyle** [comment]
Hi @mehulgogri,

Sonobuoy interfaces with Kubernetes  through the client using the standard [documented ports & protocols](https://kubernetes.io/docs/reference/networking/ports-and-protocols/). Please let me know if you are seeing specific errors when running tests.
