### ISSUE TITLE
Please add support for Windows 2022

### ISSUE THREAD

**Issue by jiechen0826** [vmware-tanzu/sonobuoy#1851]
**Describe the solution you'd like**
Please add support for Windows 2022. Latest sonobuoy image was not able to run on Windows 2022 nodes due to mismatch between container OS and the host OS. 

**Anything else you would like to add:**
I was trying to run e2e test on a mix cluster with Windows 2022 nodes. I encountered the following error:
`Error: failed to start container "kube-sonobuoy": Error response from daemon: hcsshim::CreateComputeSystem kube-sonobuoy: The container operating system does not match the host operating system.`

**Environment:**

- Sonobuoy version: v.0.56.10
- Kubernetes version: (use `kubectl version`): 1.22
- Kubernetes installer & version: 1.23
- Cloud provider or hardware configuration: AWS
- OS (e.g. from `/etc/os-release`): Windows 2022

**Comment by jayunit100** [comment]
thanks for this !

**Comment by jiechen0826** [comment]
Hi there, just checking in to see if the support for Windows 2022 will be on the roadmap?
