### ISSUE TITLE
Support Kubernetes pod security admission

### ISSUE THREAD

**Issue by rtheis** [vmware-tanzu/sonobuoy#1858]
**What steps did you take and what happened:**

Ran the following against an OpenShift version 4.12 cluster.  Version 4.12 is based on Kubernetes version 1.25 and configures Kubernetes pod security admission to enforce `restricted` by default.

```
 sonobuoy run --mode=certified-conformance --dns-namespace=openshift-dns --dns-pod-labels=dns.operator.openshift.io/daemonset-dns=default --timeout 14400
```

This issued the following warning:
```
W1108 15:20:50.839688     401 warnings.go:70] would violate PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "kube-sonobuoy" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "kube-sonobuoy" must set securityContext.capabilities.drop=["ALL"]), seccompProfile (pod or container "kube-sonobuoy" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
```

OpenShift automatic pod security namespace labeling saw that the namespace needed the following labels so added them:

```
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: v1.24
```

**What did you expect to happen:**

Sonobuoy should properly configure its Kubernetes resources to support `restricted` pod security admission.

**Anything else you would like to add:**

N/A

**Environment:**

- Sonobuoy version: 0.56.10
- Kubernetes version: (use `kubectl version`): 1.25
- Kubernetes installer & version: N/A
- Cloud provider or hardware configuration: [Red Hat OpenShift on IBM Cloud](https://cloud.ibm.com/docs/openshift)
- OS (e.g. from `/etc/os-release`): N/A
- Sonobuoy tarball (which contains * below): N/A

**Comment by franknstyle** [comment]
Hi @rtheis,

[v0.56.16](https://github.com/vmware-tanzu/sonobuoy/releases/tag/v0.56.16) has just been released that adds a flag to set the enforce level. Please let me know if this is enough in your implementation and unblocks you without the optional version lock.

**Comment by rtheis** [comment]
Thank you @franknstyle.  We'll pull this version into our testing and let you know.
