### ISSUE TITLE
sig-cli test fails because WHICH executable not found in PATH

### ISSUE THREAD

**Issue by AMacedoP** [vmware-tanzu/sonobuoy#1868]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
I run the e2e sig-cli tests and the test "[sig-cli] Kubectl client Simple pod should handle in-cluster config" is failing because the conformance image doesn't have the WHICH executable. This is because since version 1.22 it is built using a distroless image and the WHICH executable is not copied to it.

**What did you expect to happen:**
Test passes normally

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
I tested against version 1.22.5 of Kubernetes, but it's still using this executable in the e2e tests of the version 1.25.4 of Kubernetes https://github.com/kubernetes/kubernetes/blob/v1.25.4/test/e2e/kubectl/kubectl.go#L706

**Environment:**

- Sonobuoy version: 0.56.7
- Kubernetes version: (use `kubectl version`): 1.22.5
- Kubernetes installer & version: kubespray
- Cloud provider or hardware configuration: baremetal
- OS (e.g. from `/etc/os-release`): ubuntu 22.04
- Sonobuoy tarball (which contains * below)

**Comment by franknstyle** [comment]
Hi @AMacedoP,

Can you please raise this issue in k/k. The sig-cli e2e tests and the conformance image are both maintained from there.
