### ISSUE TITLE
[sig-network] ClusterDns [Feature:Example] should create pod that uses dns failing 

### ISSUE THREAD

**Issue by workerus** [vmware-tanzu/sonobuoy#1878]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Running:

./sonobuoy run --mode=certified-conformance --kubeconfig /etc/rancher/k3s/k3s.yaml --kubernetes-version v1.22.16

**What did you expect to happen:**

[sig-network] ClusterDns [Feature:Example] should create pod that uses dns normally should pass but it's failing.
In the log podlogs/sonobuoy/sonobuoy-e2e-job-67f7406c56624f3a/logs/e2e.txt i find the reason it's failing

 stderr:
    error: the path "src/k8s.io/examples/staging/cluster-dns/dns-backend-rc.yaml" does not exist

when i create manually pod from the yaml file above it's working and no issues observed. Looks like this test is failing only because this file is missing.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Sonobuoy version: 0.56.14 
- Kubernetes version: (use `kubectl version`): v1.22.16
- Kubernetes installer & version: v1.22.16+k3s1
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04.5 LTS 
- Sonobuoy tarball (which contains * below)

**Comment by franknstyle** [comment]
Hi @workerus,

Can you please raise this issue in k/k. The sig-network tests are not maintained in the sonobuoy repo.
