### ISSUE TITLE
Extract queries to their own plugin

### ISSUE THREAD

**Issue by chuckha** [vmware-tanzu/sonobuoy#432]
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE REQUEST

I propose that we extract queries out of core sonobuoy into a plugin. This code makes versioning sonobuoy against k8s painful:

https://github.com/heptio/sonobuoy/blob/3c2b66bf5d3d5692111183301c210cc334f52a95/pkg/discovery/queries.go

Without this, I believe the only other place we use the k8s api is the driver code which is now, as of 1.10 or 1.11 (k8s) only using stable APIs. 

** Why? **:

We should do this for two reasons:

### Stable API

k8s has now stabilized (as of 1.10) the APIs used. We can write a little extra code to ensure we have the compatibility guarantees we've made while the older APIs get deprecated. 
After v1.12 of k8s is released we will only need to support the stable apis which is a lot nicer than the code linked to above with all of the changing / adding apis. Technically we wouldn't need to update client-go for the sonobuoy repo again until jobs or daemonset changes (but as its stable this is unlikely to happen for a while) or when some unforeseen event takes place (sonobuoy's scope expands, new drivers added that are in alpha, etc).

### Reduced scope of sonobuoy

This change would reduce the scope of sonobuoy from having to run queries against the k8s api and serializing results and all that. That would be part of the query plugin we write. Sonobuoy would then be an aggregator that spawns plugin workers and aggregates their results and nothing more.

**Comment by timothysc** [comment]
It would still be painful if it were it's own plugin.   I think prioritizing the use of the dymanic client would be more fruitful to solve the api drift problem.  

Ideally I'd like both the dymanic client and a DAG model of execution which includes the queries, but most folks use sonobuoy with a pretty singular focus.  So I think the plugin change is of less importance vs. the dynamic client.  

Thoughts?

**Comment by chuckha** [comment]
I think both would be good to do.

To me it feels like sonobuoy is the aggregator/plugin driver and beyond that is scope creep.

As for getting a DAG in place, if we want a DAG that doesn't have to make a special case for the queries, I think extracting them to a plugin would be the best way to go.

But yes, dynamic client is the higher priority issue here for sure 👍

**Comment by johnSchnake** [comment]
> So I think the plugin change is of less importance ...

This was the conclusion we just came to again. I did get the dynamic client integrated so we would be a step closer to a standalone plugin, but as it was pointed out to me: outside of Sonobuoy devs, no one has asked for queries to be their own plugin.

The only thing that has, reasonably, been requested is to turn off queries if we want to: #682

**Comment by johnSchnake** [comment]
I had always ha this as an item I wanted to get done, but 
1) no one in the community wants/needs this
2) doing this would require us to add plugin ordering so the queries run at the end
3) once all this is done, nothing is particularly easier for the end user but things could be different which just complicates things.

Closing.
