### ISSUE TITLE
create SecurityContextConstraints for use with openhift/okd

### ISSUE THREAD

**Issue by MansM** [vmware-tanzu/sonobuoy#533]
**Describe the solution you'd like**
As sonobouy needs a lot of permissions on openshift its hard to figure out which are the least amount required

**Anything else you would like to add:**
- https://docs.okd.io/latest/admin_guide/manage_scc.html

**Environment:**

- Sonobuoy version: v0.11.6
- Kubernetes version: (use `kubectl version`):
```
$ oc version
oc v3.10.0+dd10d17
kubernetes v1.10.0+b81c8f8
features: Basic-Auth

Server xxxxxx
openshift v3.9.0+71543b2-33
kubernetes v1.9.1+a0ce1bc657
```
- Kubernetes installer & version:
- Cloud provider or hardware configuration: bare metal 
- OS (e.g. from `/etc/os-release`):

**Comment by johnSchnake** [comment]
If I'm understanding correctly you're suggesting we add a special resource specifically for openshift deployments?

I dont think it likely we add such a resource at this time, but the general idea of allowing the user to specify other resources which `sonobuoy [gen|run]` would pick up has come up before. Is that all you're really asking for, e.g. a shortcut so you dont have to do `sonobuoy gen > output.yaml & <edit file with your SecurityContextConstraints & kubectl apply -f output.yaml`?

**Comment by rjhowe** [comment]
I think instead of a resource created that `sonobuoy [gen|run]` would pick up, we would need some way to pass an api call to patch an existing resource based on a variable like namespace name, or service account name.
