### ISSUE TITLE
Sonobuoy e2e conformance testing should support IPv6-Only clusters

### ISSUE THREAD

**Issue by rosskukulinski** [vmware-tanzu/sonobuoy#581]
Tracking issue of the upstream e2e conformance test suite which needs to add support for ipv6 networking stacks.

**Comment by rosskukulinski** [comment]
https://github.com/kubernetes/kubernetes/issues/70248

**Comment by johnSchnake** [comment]
Just a touchpoint; based on the linked issue this is getting close.

**Comment by johnSchnake** [comment]
Need to revisit this; may be able to close. The upstream issue is closed (done).

**Comment by rosskukulinski** [comment]
@johnSchnake I pinged the CRE team to get their input (cc: @emuetzel)

**Comment by johnSchnake** [comment]
Just re-reviewed a bit of the upstream ticket and it seems we can close this. Feel free to reopen if something is lacking.
