### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by stevesloka** [vmware-tanzu/sonobuoy#585]
**Describe the solution you'd like**
Scans can take hours to complete for a cluster, it would be neat to have a way to notify (e.g. email, slack, CRD, etc) that my job is complete and a way to get to the results. 

**Anything else you would like to add:**
Would be neat to use CRDs to manage scans, they could easily store the history of the run (similar to how Velero uses CRDs to manage backups).  But this is not a requirement and adds deployment complexity.

**Comment by Msimms20** [comment]
I agree, it takes around 2 hours 12 minutes for 1 cluster scan. What I want to do is to do a scan nightly, and receive an email alert of the status.
