### ISSUE TITLE
Allow for plugin ordering

### ISSUE THREAD

**Issue by johnSchnake** [vmware-tanzu/sonobuoy#631]
**Describe the solution you'd like**
Plugins should be able to run in a predetermined order.

**Anything else you would like to add:**
This was mentioned in #432 as being a prereq for moving the queries to their own plugin. We want to run the queries last so that we can see if there are problems with the cleanup of other plugins.

I suggested that a full DAG may be a bit overkill for the known use cases:
 - run other plugins then run queries
 - run a plugin in order to set up some condition (simulate load, break something, etc) then run a set of test or something

In both of those cases my idea of a minimal ordering implementation (mentioned in #39 and PR [here](https://github.com/heptio/sonobuoy/issues/39) ) would be sufficient.

Is there a reason we need more? Or a problem introduced by this type of approach?

**Comment by tvalasek** [comment]
Takin the thumb up away. I can solve dependencies/plugin ordering within my test files (using custom plugins feature)

**Comment by mtulio** [comment]
Hey @johnSchnake , do you know if running the ordered plugin was implemented or is there any advice to use custom plugins running ordered (example serial: A->B->C) ?
