### ISSUE TITLE
RFE: Build api coverage into default metric gathering or as a plugin

### ISSUE THREAD

**Issue by timothysc** [vmware-tanzu/sonobuoy#659]
**Describe the solution you'd like**
As a developer I would like sonobuoy to output data from either a dynamic webhook-audit log, or from api-snoop, into the sonobuoy output which would allow me to post process analyze the api-surface area of my tests. 

This will yield total api-surface used as part of `[Conformance]` or any other specified e2e.focus.

cc @clintkitson @hh

**Comment by johnSchnake** [comment]
Is there a code example I could look at for how this is done manually? I can dig into API snoop but I'm not familiar with how it is currently run so I'm starting from scratch there.

**Comment by johnSchnake** [comment]
https://github.com/cncf/apisnoop

**Comment by hh** [comment]
Currently we load from buckets:
```select * from load_audit_events('ci-kubernetes-e2e-gci-gce','1134962072287711234');```
https://github.com/cncf/apisnoop/blob/v3_rainbow/org/meta.org#call-load_audit_events
https://github.com/cncf/apisnoop/blob/v3_rainbow/apps/hasura/migrations/245_function_load_audit_event.up.sql#L37

Though it would be simple to create a webhook that instead wrote directly to the `audit_entries` table.

**Comment by hh** [comment]
https://github.com/cncf/apisnoop/tree/v3_rainbow/apps is now contains a single docker-compose.yaml that works, just need to to be fed some audit logs (currently via testgrid).

**Comment by johnSchnake** [comment]
Going to move this to next milestone; it just has been at the edge of priority so far and I haven't made progress besides initial investigations.

**Comment by hh** [comment]
We have a container we use as auditsink query the populated db to generate api coverage metrics.
- https://github.com/cncf/apisnoop/tree/master/apps/snoopdb#snoopdb

**Comment by vladimirvivien** [comment]
thanks @hh.  @wilsonehusin let's reprioritize this.

**Comment by vladimirvivien** [comment]
Not Stale

**Comment by vladimirvivien** [comment]
I did not realize there was already a request to wrap api-snoop as a plugin 🎉 
@wilsonehusin let's prioritize this for this/next quarter.
