### ISSUE TITLE
[RFE] Create a cluster loader + pbench plugin.

### ISSUE THREAD

**Issue by timothysc** [vmware-tanzu/sonobuoy#85]
Part of my desire in creating sonobuoy was to have a unified means of generating a performance report, that lived as a canonical thunk to be compared over time.

Combine cluster-loading + sonobuoy gathering + pbench data 

/cc @jeremyeder @mffiedler @sjug

**Comment by timothysc** [comment]
@carldanley @mauilion - Just as a PSA, something like this will eventually be needed todo scale out deployment validation

**Comment by johnSchnake** [comment]
The blocker for this currently is that the pbench plugin needs the `hostPID` option on the pod which we dont surface.

I'm debating one of two approaches for this:
 1) in the plugin spec, allow the user to also provide an optional `podspec` which will be merged with our templated version
 2) dont surface any of this but, as #638 suggests, consume the plugin definitions on the clientside and produce the fully pods that we want to run (they'll be missing the call home info which will be added later though to report results). This approach ensures power users _can_ do anything they want.

The downside of (2) is that it puts those power users back into the age of `run sonobuoy gen -> edit file -> kubectl apply` whereas (1) would allow the users to store those thanks in the plugin spec and still run with `sonobuoy run --plugin foo` and more easily support sharing of configs like that.

**Comment by johnSchnake** [comment]
The blocker listed here is no longer relevant; there is not a PodSpec field on the plugin definitions which can override any of the default podspec settings.

**Comment by vladimirvivien** [comment]
@wilsonehusin let us revisit this.

**Comment by vladimirvivien** [comment]
Not stale

**Comment by vladimirvivien** [comment]
@wilsonehusin I am marking this so that we can revisit this and prioritize for this year.
