### ISSUE TITLE
Cloud provider specific tests do not work for GKE

### ISSUE THREAD

**Issue by eddytruyen** [vmware-tanzu/sonobuoy#888]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
This is an iteration of https://github.com/heptio/sonobuoy/issues/881#issuecomment-531577541.

At first, the example code worked for me on GKE (`sonobuoy run --plugin-env e2e.E2E_PROVIDER=gke`)for dynamic provisioning. But thereafter it stopped working on GKE.

The test is immediately completed and the e2e.log gives the following unexpected zone error:
```
Sep 17 19:30:16.791: INFO: Failed to setup provider config: error parsing GCE/GKE region from zone "": unexpected zone:
panic:
Your test failed.
Ginkgo panics to prevent subsequent assertions from running.
Normally Ginkgo rescues this panic so you shouldn't see it.

But, if you make an assertion in a goroutine, Ginkgo can't capture the panic.
To circumvent this, you should call

        defer GinkgoRecover()

at the top of the goroutine that caused this panic
```
I have tried to migitate the issue by trying another version of sonobuoy and deploying the kubernetes cluster in another zone, but the same error occurs. I guess something has gone havoc with my Google Cloud project after the first run with sonobuoy. In attachment you find the first run and the havoc run. 

[gke-1.13_provider-1.13_Dynamic-Provisioning_DynamicProvisioner_sonobuoy_d2cd9afc-4aed-4877-881f-3f9ca129a325.tar.gz](https://github.com/heptio/sonobuoy/files/3623129/gke-1.13_provider-1.13_Dynamic-Provisioning_DynamicProvisioner_sonobuoy_d2cd9afc-4aed-4877-881f-3f9ca129a325.tar.gz)
[201909171930_sonobuoy_8e89c636-003c-4210-afc8-52a326660243.tar.gz](https://github.com/heptio/sonobuoy/files/3623130/201909171930_sonobuoy_8e89c636-003c-4210-afc8-52a326660243.tar.gz)

**What did you expect to happen:**

I'd hope that it keeps working for other cloud provider specific tests
**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Sonobuoy version: 0.14.3 mainlu
- Kubernetes version: (use `kubectl version`): 1.13
- Kubernetes installer & version: GKE
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`): Standard4 machines
[gke-1.13_provider-1.13_Dynamic-Provisioning_DynamicProvisioner_sonobuoy_d2cd9afc-4aed-4877-881f-3f9ca129a325.tar.gz](https://github.com/heptio/sonobuoy/files/3623186/gke-1.13_provider-1.13_Dynamic-Provisioning_DynamicProvisioner_sonobuoy_d2cd9afc-4aed-4877-881f-3f9ca129a325.tar.gz)
[201909171930_sonobuoy_8e89c636-003c-4210-afc8-52a326660243.tar.gz](https://github.com/heptio/sonobuoy/files/3623187/201909171930_sonobuoy_8e89c636-003c-4210-afc8-52a326660243.tar.gz)

- Sonobuoy tarball (which contains * below)

**Comment by johnSchnake** [comment]
In the code I've found that it seems to expect a zone/region as well:
```
	zone := framework.TestContext.CloudConfig.Zone
	region := framework.TestContext.CloudConfig.Region
```

In addition, those are only 2 of the gke/gce specific settings that the test context object holds:
```
	flags.StringVar(&cloudConfig.APIEndpoint, "gce-api-endpoint", "", "The GCE APIEndpoint being used, if applicable")
	flags.StringVar(&cloudConfig.ProjectID, "gce-project", "", "The GCE project being used, if applicable")
	flags.StringVar(&cloudConfig.Zone, "gce-zone", "", "GCE zone being used, if applicable")
	flags.StringVar(&cloudConfig.Region, "gce-region", "", "GCE region being used, if applicable")
	flags.BoolVar(&cloudConfig.MultiZone, "gce-multizone", false, "If true, start GCE cloud provider with multizone support.")
	flags.BoolVar(&cloudConfig.MultiMaster, "gce-multimaster", false, "If true, the underlying GCE/GKE cluster is assumed to be multi-master.")
	flags.StringVar(&cloudConfig.Cluster, "gke-cluster", "", "GKE name of cluster being used, if applicable")
```

Those can be set via flags but do not have the ability to set them via env vars (which sonobuoy can do easily). All the testContext values tend to be able to be set in a flag or in a config file, but it does not use `viper.AutomaticEnv` or anything so they cant typically be read from the env. This is why the conformance test image itself has to capture those values and set them on the command line.

For newer clusters you could use the go runner in the conformance image to specify arbitrary flags for the test run. However, I think this requires v1.16 k8s as it didnt make the v1.15 cutoff.

In addition, this is maybe a good use case for supporting custom configmaps within Sonobuoy. E.g. you could put your config into a configmap, specify it as a mount for your plugin, etc etc.

I'll have to think about this a tad. For the record, both tarballs you sent had the same panic so I don't have reference for the 'work once then never again' stated in the title.

Finally, just to be clear, you generally don't need to set the provider unless you are trying to explicitly test provider-specific functionality. Most users do not require this.

**Comment by eddytruyen** [comment]
Thank you for the quick reply!
First of all, sorry for the confusion. When retrieving the first tarball, I probably untarred another tarball in my home dir. I do remember that when I executed the `./sonobuoy results` command it reported that 0 tests were executed.  So I changed the title

So the only way to patch around it in k8 clusters < v1.16 is to create a custom image in which the flags are explicitly said when invoking the e2e test suite of Kubernetes. Could you be specific about the file that I need to change in which container image, for achieving this purpose?

**Comment by johnSchnake** [comment]
Sure!

So the conformance image is built by upstream k8s and lives here: https://github.com/kubernetes/kubernetes/tree/master/cluster/images/conformance

That page has instructions for how to build the image in general.

You'll want to do one of the following:
 - change run_e2e.sh https://github.com/kubernetes/kubernetes/blob/master/cluster/images/conformance/run_e2e.sh to set the flags you want. To prevent having to rebuild if you want to tweak those values, you should probably grab the values from env vars.
 - you can use that same image but build it for an older version of the test code. This way build the tests that correspond to your preferred release (v1.13.x) but then you can utilize the newer `E2E_USE_GO_RUNNER=true` mode which allows you to set arbitrary flags via the `E2E_EXTRA_ARGS` env var. By default, those are a space-separated list but you can also make it delimted by whatever char you want. Let me know if you need more details there.

**Comment by johnSchnake** [comment]
Just be sure, regardless of the approach, to build the test binary for the cluster you're actually testing against. Otherwise, you risk running tests that are inappropriate for your cluster.

**Comment by eddytruyen** [comment]
Ok, I added the following lines to run_e2e.sh as part of the gingko-args
```
"--gce-api-endpoint=${GCE_API_ENDPOINT}"
    "--gce-project=${GCE_PROJECT}"
    "--gce-zone=${GCE_ZONE}"
    "--gce-region=${GCE_REGION}"
    "--gke-cluster=${GKE_CLUSTER}"
```
Sorry for asking, but do you know helpful resources about retrieving the API endpoint of Google Compute Engine.

**Comment by johnSchnake** [comment]
Going to go ahead and close this since it seems your questions have been answered. Also, look for an upcoming blogpost about how to customize e2e test images for things like this. It will go into just a bit more depth than this.

Feel free to reopen if you have further questions on the topic.

**Comment by eddytruyen** [comment]
Ok.
Please notify me when you have published the blogpost.

**Comment by johnSchnake** [comment]
@eddytruyen The blogpost is live now: https://sonobuoy.io/custom-e2e-image/

**Comment by eddytruyen** [comment]
@johnSchnake Thank you for the notification. The article reads well and is clear. In short, it is a nice contribution to the community in my opinion.
