### ISSUE TITLE
Use Debian for both AMD and ARM docker images

### ISSUE THREAD

**Issue by zubron** [vmware-tanzu/sonobuoy#889]
We currently use Debian (debian:stretch-slim) as the base image for our AMD64 images, and Ubuntu (ubuntu:16.04) for our ARM64 images.

This difference has been in place since [ARM support was added](https://github.com/heptio/sonobuoy/pull/491). The difference has been questioned before (#635), but no definitive answer seems available. We should raise this question again as it would be good to use the same OS (Debian) for both to avoid possible differences in behaviour and help with maintenance of our image builds.

**Comment by johnSchnake** [comment]
Would be nice to simplify things; but not a requirement.

Closing this for now; doing some grooming on the issue list in general and closing things if either:
 - they weren't been reported by the community
 - don't have a genuine need to get done

The reason for this is that we tended to use the issue list as a backlog of very minor or wish-list type items which we wish to clear out for now.
