### ISSUE TITLE
Use non-root user in Sonobuoy docker images

### ISSUE THREAD

**Issue by zubron** [vmware-tanzu/sonobuoy#890]
Follow up from #254.

We currently run Sonobuoy as root within our images. I'm not aware of anything within Sonobuoy requiring root permissions so we can probably change this to use a non-root user.

The initial Dockerfile for the project had a commented out [USER directive ](https://github.com/heptio/sonobuoy/commit/7f69bea97ff746d3303a156fa53be8ef5472864d#diff-3254677a7917c6c01f55212f86c57fbfR23) which the user and group `nobody`. We should determine whether root is necessary, and if not change to a non-root user.

Ideally we should have some integration tests available (from #668) before making this change.

**Comment by johnSchnake** [comment]
Closing this for now; doing some grooming on the issue list in general and closing things if either:
 - they weren't been reported by the community
 - don't have a genuine need to get done

The reason for this is that we tended to use the issue list as a backlog of very minor or wish-list type items which we wish to clear out for now.
