### ISSUE TITLE
Place Sonobuoy executable and related files somewhere other than /

### ISSUE THREAD

**Issue by zubron** [vmware-tanzu/sonobuoy#891]
Follow on from #254.

We currently place all files required to run Sonobuoy within `/` in our Docker images. In the past it was suggested that we should place them somewhere other than this. This would help keep things a bit more organised within the image.

Making a change like this requires care due to expectations about the locations of files. If we were only concerned about the images, moving these files would be safe to do. However, the CLI generates a manifest that expects the files to be in a particular location when running the images. If we move the files, that contract is broken. This would be fine in the case where the CLI version matches the image version for new manifests, however it's entirely possible that we could have users with existing manifests, or using a newer image with an older CLI version. We would need to transition gradually and ensure that any changes work for both new and old clients.

To make this change safely, we should wait until we have integration testing in place which would help us verify that the changes that we are making are safe. This is being worked on as part of #668.

**Comment by johnSchnake** [comment]
Closing this for now; doing some grooming on the issue list in general and closing things if either:
 - they weren't been reported by the community
 - don't have a genuine need to get done

The reason for this is that we tended to use the issue list as a backlog of very minor or wish-list type items which we wish to clear out for now.
