### ISSUE TITLE
Failed to pull image "sonobuoy/sonobuoy:v0.16.1": rpc error: code = Unknown desc = Error response from daemon: manifest for sonobuoy/sonobuoy:v0.16.1 not found

### ISSUE THREAD

**Issue by DamianKusz** [vmware-tanzu/sonobuoy#939]
Hi, I've faced problem connected with this commit. During the docs default steps:
```
go get -u -v github.com/vmware-tanzu/sonobuoy
sonobuoy run
```
should download and run sonouboy image from registry - now docker registry sonobuoy/sonobuoy.

But no image exists there : 
```
k describe pod -n sonobuoy 
.
.
.
Events:
  Type     Reason     Age   From                  Message
  ----     ------     ----  ----                  -------
  Normal   Scheduled  11s   default-scheduler     Successfully assigned sonobuoy/sonobuoy to ksb-w2.grey
  Normal   Pulling    10s   kubelet, ksb-w2.grey  Pulling image "sonobuoy/sonobuoy:v0.16.1"
  Warning  Failed     9s    kubelet, ksb-w2.grey  Failed to pull image "sonobuoy/sonobuoy:v0.16.1": rpc error: code = Unknown desc = Error response from daemon: manifest for sonobuoy/sonobuoy:v0.16.1 not found
  Warning  Failed     9s    kubelet, ksb-w2.grey  Error: ErrImagePull
  Normal   BackOff    9s    kubelet, ksb-w2.grey  Back-off pulling image "sonobuoy/sonobuoy:v0.16.1"
  Warning  Failed     9s    kubelet, ksb-w2.grey  Error: ImagePullBackOff
```

after pointing old registry manually : 
`sonobuoy run --sonobuoy-image gcr.io/heptio-images/sonobuoy`

image has been pulled properly:
```
Events:
  Type    Reason     Age   From                  Message
  ----    ------     ----  ----                  -------
  Normal  Scheduled  10s   default-scheduler     Successfully assigned sonobuoy/sonobuoy to ksb-w2.grey
  Normal  Pulling    9s    kubelet, ksb-w2.grey  Pulling image "gcr.io/heptio-images/sonobuoy"
  Normal  Pulled     1s    kubelet, ksb-w2.grey  Successfully pulled image "gcr.io/heptio-images/sonobuoy"
  Normal  Created    0s    kubelet, ksb-w2.grey  Created container kube-sonobuoy
  Normal  Started    0s    kubelet, ksb-w2.grey  Started container kube-sonobuoy
```

Please update images in new registry.

**Environment:**

- Sonobuoy version: v1.16.1
- Kubernetes version: (use `kubectl version`): 1.14.5, 1.15.4
- Kubernetes installer & version:
- Cloud provider or hardware configuration: 
- OS (e.g. from `/etc/os-release`):   CentOS Linux release 7.5.1804 (Core) 
- Sonobuoy tarball (which contains * below)

**Comment by ttarczynski** [comment]
I think this may be related to the recent change of registry to dockerhub: #927 
There's an error when trying to pull the image from dockerhub:
```
$ docker pull sonobuoy/sonobuoy:v0.16.1
Error response from daemon: manifest for sonobuoy/sonobuoy:v0.16.1 not found: manifest unknown: manifest unknown
```

And when listing images in dockerhub (https://hub.docker.com/r/sonobuoy/sonobuoy/tags) there are currently no such tags as: `v0.16.1` or `latest`

**Comment by johnSchnake** [comment]
Yes it absolutely is that problem; we had made that change thinking that most users would _not_ be using the actual version from master and instead the latest stable but, as you point out, our README actually usese the `go get` flow and leads to this problem.

I'll push a copy of the v0.16.1 release to dockerhub so it lives in both places and avoids this.

**Comment by johnSchnake** [comment]
I just (as a stopgap) pushed the amd64 image manually and will get the manifest/arm image up a bit later today when I have a moment.

**Comment by johnSchnake** [comment]
amd/arm images are pushed as well as the manifest so `sonobuoy/sonobuoy:v0.16.1` should work for either arch. Let me know if there continue to be issues.

Thank you so much for reporting this! @DamianKusz
