### ISSUE TITLE
Add Sonobuoy blogs from CNABU blog that never got put on sonobuoy.io

### ISSUE THREAD

**Issue by johnSchnake** [vmware-tanzu/sonobuoy#955]
Some blog posts were put here https://blogs.vmware.com/cloudnative/?category_name=&s=sonobuoy before we had our own sonobuoy.io to publish blog posts on.

I'd like to move those blogs into our site for completeness; there is some good content that users wont currently find on our site.

**Comment by jonasrosland** [comment]
To make sure that we don't mess up SEO, what we can do is to have a short blurb about each one and point to the full blog over on the VMware blog. Does that work? If so, I can get on it.

**Comment by johnSchnake** [comment]
Yea that works for me. I know I've tried to link people to our blogs for xyz a few times only to realize it was on the other site. Having them discoverable via sonobuoy.io would be sufficient for me.

**Comment by johnSchnake** [comment]
I'll add links here to the ones that I see need references

**Comment by johnSchnake** [comment]
https://blogs.vmware.com/cloudnative/2019/02/21/certifying-kubernetes-with-sonobuoy/
https://blogs.vmware.com/cloudnative/2019/04/30/sonobuoy-plugins-custom-testing/
https://blogs.vmware.com/cloudnative/2019/04/02/testing-air-gapped-kubernetes-sonobuoy-0-14/

Also, I noticed on the blogs and on https://blogs.vmware.com/cloudnative/author/jschnake/ I dont have an image up. Can we fix that too?

**Comment by jonasrosland** [comment]
> Also, I noticed on the blogs and on https://blogs.vmware.com/cloudnative/author/jschnake/ I dont have an image up. Can we fix that too?

I can show you offline how to do that.

For the blog posts, I'll get those blurbs started. I'll set the to be backdated to the same dates as the original blog posts.

**Comment by jonasrosland** [comment]
https://blogs.vmware.com/cloudnative/2019/02/21/certifying-kubernetes-with-sonobuoy/
was already published as
https://sonobuoy.io/certifying-kubernetes-with-sonobuoy/
