### ISSUE TITLE
Create publishing bot and get next release published by it

### ISSUE THREAD

**Issue by johnSchnake** [vmware-tanzu/sonobuoy#967]
**Describe the solution you'd like**
A Heptio bot was formerly configured to push Sonobuoy releases. Now Sonobuoy is growing up and getting a bot of its own. Needs to be created and given enough permissions to push a release. Then the new API token created for that user and CircleCI config updated with that set as `GITHUB_TOKEN `

**Comment by zubron** [comment]
Closing this as Sonobuoy finally got its own bot and as you can see in our latest release, it was used for publishing: https://github.com/vmware-tanzu/sonobuoy/releases/tag/v0.16.3
