### ISSUE TITLE
Sonobuoy not working with Openshift 4.x

### ISSUE THREAD

**Issue by garimavsharma** [vmware-tanzu/sonobuoy#975]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

Sonobuoy not working with Openshift. Getting error 'no dns pods found with the labels [kube-dns, coredns] in namespace kube-system'.
Ideally, sonobuoy should provide an option to override the default location of the namespace for the dns pods. For Openshift 4.3 the namespace for these pods is openshift-dns.

[root@kni1-bootstrap tmate-2.3.1-static-linux-amd64]# ./sonobuoy run --wait --mode quick 
WARN[0000] Version v1.16.0-beta.2+03b33d2 is not a stable version, conformance image may not exist upstream 
ERRO[0000] Preflight checks failed                      
ERRO[0000] no dns pods found with the labels [kube-dns, coredns] in namespace kube-system 

**What did you expect to happen:**
sonobuoy should not constraint where it looks for the namespace for the dns pods. It runs fine against upstream k8s version 1.16.x.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**
[root@kni1-bootstrap tmate-2.3.1-static-linux-amd64]# ./sonobuoy run --wait --mode quick 
WARN[0000] Version v1.16.0-beta.2+03b33d2 is not a stable version, conformance image may not exist upstream 
ERRO[0000] Preflight checks failed                      
ERRO[0000] no dns pods found with the labels [kube-dns, coredns] in namespace kube-system 

Version-Release number of selected component (if applicable):
[root@kni1-bootstrap tmate-2.3.1-static-linux-amd64]# ./sonobuoy version
Sonobuoy Version: v0.16.2
MinimumKubeVersion: 1.14.0
MaximumKubeVersion: 1.16.99
GitSHA: 9b83cacc2e9c9df49d9f818f7cdd8d7d9e2d8b1c

[root@kni1-bootstrap tmate-2.3.1-static-linux-amd64]# oc get clusterversion
NAME      VERSION                        AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.3.0-0.ci-2019-10-22-133041   True        False         2d21h   Error while reconciling 4.3.0-0.ci-2019-10-22-133041: the cluster operator machine-config is degraded

- Sonobuoy version: v0.16.2
- Kubernetes version: (use `kubectl version`):1.16.99
- Kubernetes installer & version: Openshift installer 4.3.0
- Cloud provider or hardware configuration: Baremetal
- OS (e.g. from `/etc/os-release`): Red Hat CoreOS 4.3
- Sonobuoy tarball (which contains * below)

**Comment by johnSchnake** [comment]
FWIW you can skip the preflight checks; I just wanted to make sure that you knew this is not a hard blocker for you.

Not completely unreasonable to make those checks a bit more customizable though; and add a config setting for that. It would be pretty trivial since it is just a clientside check. In addition, there is already a `PreflightConfig` object but it currently just takes the name for the desired namespace to run in and assumes the namespace for the dns check.
