### ISSUE TITLE
Installation steps in README assume presence of $HOME/bin directory

### ISSUE THREAD

**Issue by willzhang** [vmware-tanzu/sonobuoy#980]
```
[root@master01 ~]# VERSION=0.16.2 OS=linux && \
> curl -L "https://github.com/vmware-tanzu/sonobuoy/releases/download/v${VERSION}/sonobuoy_${VERSION}_${OS}_amd64.tar.gz" --output $HOME/bin/sonobuoy.tar.gz && \
> tar -xzf $HOME/bin/sonobuoy.tar.gz -C $HOME/bin && \
> chmod +x $HOME/bin/sonobuoy && \
> rm $HOME/bin/sonobuoy.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   624    0   624    0     0    482      0 --:--:--  0:00:01 --:--:--   482
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0Warning: Failed to create the file /root/bin/sonobuoy.tar.gz: No such file or
Warning: directory
  0 9258k    0 16360    0     0   6140      0  0:25:44  0:00:02  0:25:42 47836
curl: (23) Failed writing body (0 != 16360)
```

**Comment by zubron** [comment]
Hi 👋 Sorry to see that you're having issues getting started with Sonobuoy.

I've tried your command locally, and believe the error is coming from the `curl -L "https://github.com/vmware-tanzu/sonobuoy/releases/download/v${VERSION}/sonobuoy_${VERSION}_${OS}_amd64.tar.gz" --output $HOME/bin/sonobuoy.tar.gz` step.

Can you confirm that `$HOME/bin` (in this case `/root/bin`) exists first? Depending on the version of curl you are using, you may be able to make use of the `--create-dirs` which will create the necessary directories for the output location.

**Comment by zubron** [comment]
Apologies, when responding before, I didn't realise that the given command was from our README. I will update the title of this issue to make it clearer for the team when it gets picked up. Thanks for the report!

**Comment by willzhang** [comment]
yes ,it just need create a bin directory
```
mkdir /root/bin
VERSION=0.15.4 OS=linux && \
curl -L "https://github.com/vmware-tanzu/sonobuoy/releases/download/v${VERSION}/sonobuoy_${VERSION}_${OS}_amd64.tar.gz" --output $HOME/bin/sonobuoy.tar.gz && \
tar -xzf $HOME/bin/sonobuoy.tar.gz -C $HOME/bin && \
chmod +x $HOME/bin/sonobuoy && \
rm $HOME/bin/sonobuoy.tar.gz
```

**Comment by zubron** [comment]
Re-opening as the README was never updated.
