### ISSUE TITLE
what version is suitable for kubernetes v1.15.5?

### ISSUE THREAD

**Issue by willzhang** [vmware-tanzu/sonobuoy#981]
sonobuoy v1.16.x support kubernetes v1.16.x,does it suport kubernetes v1.15.5？i need test that version.
but i can't find sonobuoy v1.15.5 for it.
and sonobuoy v1.15.4 support kuberntes v1.15.5, is there have a list of sonobuoy what it support for kubernetes?

**Comment by zubron** [comment]
Sonobuoy 0.16.* supports Kubernetes 1.16, 1.15, and 1.14.

It might not be prominent enough, but we do include this information in the README:
> Sonobuoy supports 3 Kubernetes minor versions: the current release and 2 minor versions before. Sonobuoy is currently versioned to track the Kubernetes minor version to clarify the support matrix. For example, Sonobuoy v0.14.x would support Kubernetes 1.14.x, 1.13.x, and 1.12.x.

I'm going to close this, but if you have any further issues in finding the correct version or have any more questions, please feel free to reopen this.

**Comment by willzhang** [comment]
ok thanks
